// 한국어の翻訳辞書。キーが無い項目は日本語(原本)にフォールバックする。
const LANG_KO = {
  ui: {
    docTitle: "일본의 여행 — 일본 국내 여행 추천 명소",
    eyebrow: "일본을 다시 발견하다.",
    heroLead: "47개 도도부현 전체에서 엄선한 {spots}곳의 명소와 {courses}개의 추천 일정. 마음에 드는 곳은 ⭐ 로 위시리스트에 담고, 다녀오면 도장을 찍어 보세요.",
    unitSpots: "{n}",
    unitCourses: "{n}",
    tabSpots: "명소 찾기",
    tabCourses: "추천 일정",
    searchPlaceholder: "명소 이름·키워드로 검색",
    prefAll: "도도부현: 전체",
    allLabel: "전체",
    wishlistToggle: "⭐ 위시리스트 ({n})",
    sortAdded: "추가한 순",
    sortRegion: "지역 순",
    exportBtn: "내보내기",
    importBtn: "가져오기",
    resultCount: "{n}곳 / 전체 {total}곳",
    emptyMsg: "조건에 맞는 명소가 없습니다",
    clearFilters: "조건을 지우고 전체 보기",
    seasonalHeading: "지금이 제철인 여행지",
    months: ["1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월", "11월", "12월"],
    bestSeasonLabel: "추천 시기",
    stayTimeLabel: "소요 시간",
    accessLabel: "가는 방법",
    mapLink: "지도 보기 →",
    hotelSearch: "🏨 주변 숙소 찾기",
    shareLabel: "공유:",
    copyUrl: "URL 복사",
    copied: "✓ 복사했습니다",
    visitedOnlyBtn: "방문한 곳만",
    stampbookTitle: "슈인초(朱印帳) — 방문 {n}곳・{m}/47 도도부현",
    feeLabel: "입장료(참고)",
    feeFree: "무료",
    feeAbout: "약 ¥{n}",
    feeRange: "¥{a}〜{b}",
    feeDisclaimer: "※ 요금은 참고용이며 변경될 수 있습니다.",
    budgetLabel: "💴 현지 비용 기준(1인): {range}",
    budgetNote: "숙박・식사・입장료 합계. 교통비는 포함되지 않습니다.",
    starAdd: "☆ 위시리스트에 추가",
    starAdded: "⭐ 위시리스트에 담김",
    visitedYes: "✓ 다녀왔어요",
    visitedNo: "○ 아직 안 갔어요",
    memoLabel: "나의 메모",
    memoPlaceholder: "궁금한 것, 먹고 싶은 것, 묵고 싶은 숙소…",
    nearbyHeading: "함께 가면 좋은 곳",
    inCoursesHeading: "이 명소가 포함된 일정",
    daysUnit: "{n}일",
    dayLabel: "{n}일차",
    backToCourses: "← 일정 목록으로",
    confirmRemove: "메모와 방문 기록도 함께 삭제됩니다. 위시리스트에서 제외할까요?",
    importError: "파일을 읽을 수 없습니다. 이 사이트에서 내보낸 JSON 파일을 선택해 주세요.",
    importNone: "유효한 명소를 찾지 못했습니다.",
    importDone: "{n}곳을 가져왔습니다.",
    exportFilename: "일본의여행-위시리스트.json",
    photoCredit: "사진: {a} ({l}) / {s}",
    footerText: "47개 도도부현 전체에서 엄선한 {n}곳의 명소와 추천 일정 가이드. 사진은 Wikimedia Commons의 것을 사용하며, 각 사진에 출처를 표기합니다. 사이트 이용 현황 파악을 위해 Google Analytics를 사용합니다.",
    ariaClose: "닫기",
    ariaStar: "{name}을(를) 위시리스트에 추가/삭제",
    ariaCardOpen: "{name} 상세 보기",
    ariaDotShow: "{name} 사진 보기",
    ariaCaption: "지금 표시 중인 사진의 명소 열기",
  },
  regions: {
    "北海道": "홋카이도", "東北": "도호쿠", "関東": "간토", "中部": "주부",
    "近畿": "긴키", "中国": "주고쿠", "四国": "시코쿠", "九州・沖縄": "규슈·오키나와",
  },
  prefectures: {
    "北海道": "홋카이도", "青森県": "아오모리현", "岩手県": "이와테현", "宮城県": "미야기현", "秋田県": "아키타현",
    "山形県": "야마가타현", "福島県": "후쿠시마현", "茨城県": "이바라키현", "栃木県": "도치기현", "群馬県": "군마현",
    "埼玉県": "사이타마현", "千葉県": "지바현", "東京都": "도쿄도", "神奈川県": "가나가와현", "新潟県": "니가타현",
    "富山県": "도야마현", "石川県": "이시카와현", "福井県": "후쿠이현", "山梨県": "야마나시현", "長野県": "나가노현",
    "岐阜県": "기후현", "静岡県": "시즈오카현", "愛知県": "아이치현", "三重県": "미에현", "滋賀県": "시가현",
    "京都府": "교토부", "大阪府": "오사카부", "兵庫県": "효고현", "奈良県": "나라현", "和歌山県": "와카야마현",
    "鳥取県": "돗토리현", "島根県": "시마네현", "岡山県": "오카야마현", "広島県": "히로시마현", "山口県": "야마구치현",
    "徳島県": "도쿠시마현", "香川県": "가가와현", "愛媛県": "에히메현", "高知県": "고치현", "福岡県": "후쿠오카현",
    "佐賀県": "사가현", "長崎県": "나가사키현", "熊本県": "구마모토현", "大分県": "오이타현", "宮崎県": "미야자키현",
    "鹿児島県": "가고시마현", "沖縄県": "오키나와현",
  },
  categories: {
    "絶景": "절경", "温泉": "온천", "グルメ": "미식", "歴史": "역사", "自然": "자연", "街歩き": "거리 산책",
  },
  spots: {
    "biei-blue-pond": { name: "비에이 푸른 연못", description: "패치워크 같은 언덕 풍경 속 신비로운 코발트블루 연못. 여름에는 라벤더도 즐길 수 있다.", bestSeason: "6〜8월", stayTime: "약 1시간", access: "아사히카와 공항에서 차로 약 40분" },
    "hakodateyama": { name: "하코다테산", description: "'세계 3대 야경'으로 불리는 부채꼴 야경. 로프웨이로 정상까지 약 3분. 산기슭 모토마치 산책도 즐겁다.", bestSeason: "연중", stayTime: "약 2시간", access: "하코다테역에서 노면전차+로프웨이로 약 30분" },
    "otaru-canal": { name: "오타루 운하", description: "석조 창고가 늘어선 레트로 운하 거리. 가스등이 켜지는 해질녘이 아름답다. 스시와 해산물덮밥 맛집도 많다.", bestSeason: "연중", stayTime: "약 3시간", access: "삿포로역에서 JR로 약 35분" },
    "shiretoko": { name: "시레토코", description: "세계자연유산. 시레토코 5호 산책과 관광선에서의 불곰·고래 관찰 등 손길 닿지 않은 자연을 만끽할 수 있다.", bestSeason: "6〜9월", stayTime: "반나절〜1일", access: "메만베쓰 공항에서 차로 약 2시간" },
    "noboribetsu-onsen": { name: "노보리베쓰 온천", description: "용출량이 홋카이도 제일인 온천 마을. 원천이 솟는 '지옥계곡'의 거친 경관은 박력 만점.", bestSeason: "연중", stayTime: "반나절 또는 1박", access: "신치토세 공항에서 차로 약 1시간" },
    "sapporo-nijo-market": { name: "삿포로 니조 시장", description: "메이지 시대부터 이어져 온 삿포로의 부엌. 아침부터 신선한 해산물덮밥을 맛볼 수 있다. 오도리 공원과 스스키노도 도보권.", bestSeason: "연중", stayTime: "약 1시간", access: "삿포로역에서 도보 약 15분" },
    "asahiyama-zoo": { name: "아사히야마 동물원", description: "펭귄 산책과 물범 원통 수조 등 '행동 전시'로 유명한 동물원. 눈 속 동물들도 겨울의 인기 볼거리.", bestSeason: "연중", stayTime: "반나절", access: "아사히카와역에서 버스로 약 40분" },
    "furano-farm-tomita": { name: "후라노 팜 도미타", description: "언덕을 보랏빛으로 물들이는 라벤더밭의 대명사. 절정인 7월에는 멜론과 꽃밭 디저트도 즐길 수 있다.", bestSeason: "6〜8월", stayTime: "약 2시간", access: "아사히카와 공항에서 차로 약 45분" },
    "toyako": { name: "도야호", description: "호숫가에 온천 마을이 펼쳐진 칼데라호. 4월 말〜10월에는 매일 밤 불꽃놀이가 열린다.", bestSeason: "4〜10월", stayTime: "반나절", access: "삿포로에서 차로 약 2시간" },
    "akanko": { name: "아칸호", description: "특별천연기념물 마리모의 호수. 호반에 아이누 코탄과 온천 마을이 있고, 겨울에는 호수 위 서리꽃도 볼 수 있다.", bestSeason: "연중", stayTime: "반나절", access: "구시로 공항에서 차로 약 1시간 10분" },
    "hakodate-asaichi": { name: "하코다테 아침시장", description: "역 앞에 약 250개 점포가 빼곡한 아침시장. 오징어 낚시 체험과 해산물덮밥으로 하코다테의 아침이 시작된다.", bestSeason: "연중", stayTime: "약 1시간 30분", access: "하코다테역에서 도보 1분" },
    "cape-kamui": { name: "가무이곶", description: "샤코탄 반도 끝에서 '샤코탄 블루' 바다를 내려다보는 곶. 끝까지 이어지는 산책로 '차렌카의 오솔길'이 상쾌하다.", bestSeason: "6〜8월", stayTime: "약 1시간 30분", access: "오타루에서 차로 약 1시간 30분" },
    "oirase-gorge": { name: "오이라세 계류", description: "도와다호에서 흘러나오는 약 14km의 계류. 산책로를 따라 폭포와 이끼 낀 바위가 이어진다. 신록과 단풍의 명소.", bestSeason: "5〜6월·10월", stayTime: "약 3시간", access: "아오모리역에서 차로 약 1시간 30분" },
    "hirosaki-castle": { name: "히로사키성·히로사키 공원", description: "현존 12천수 중 하나. 약 2,600그루의 벚꽃이 해자를 뒤덮는 봄의 벚꽃축제는 일본 굴지의 벚꽃 풍경.", bestSeason: "4월 하순〜5월 상순", stayTime: "약 2시간", access: "히로사키역에서 버스로 약 15분" },
    "chusonji": { name: "주손지 곤지키도", description: "히라이즈미의 세계유산. 오슈 후지와라 가문이 세운 금박 불당은 압권이라는 말밖에.", bestSeason: "연중", stayTime: "약 2시간", access: "히라이즈미역에서 도보 약 20분" },
    "jodogahama": { name: "조도가하마", description: "흰 유문암과 소나무의 초록, 투명한 바다가 어우러진 산리쿠 대표 절경. 푸른 동굴을 도는 작은 배도 인기.", bestSeason: "6〜9월", stayTime: "약 2시간", access: "미야코역에서 차로 약 10분" },
    "matsushima": { name: "마쓰시마", description: "일본 3경 중 하나. 260여 개 섬이 떠 있는 만을 유람선으로 돌 수 있다. 굴과 사사카마보코도 명물.", bestSeason: "연중", stayTime: "약 3시간", access: "센다이역에서 JR로 약 40분" },
    "zao-okama": { name: "자오 오카마", description: "에메랄드그린 화구호. 날씨에 따라 색이 변하는 신비한 수면을 자오 에코라인 드라이브로 만나러 간다.", bestSeason: "5〜10월", stayTime: "약 1시간", access: "센다이에서 차로 약 1시간 30분" },
    "kakunodate": { name: "가쿠노다테", description: "'미치노쿠의 작은 교토'로 불리는 무가 저택 거리. 봄에는 수양벚나무 터널이 장관.", bestSeason: "4월 하순〜5월 상순", stayTime: "약 2시간", access: "가쿠노다테역에서 도보 약 15분" },
    "nyuto-onsen": { name: "뉴토 온천향", description: "너도밤나무 숲에 7개의 온천 숙소가 흩어진 비탕 마을. 유백색 노천탕과 '순례첩'으로 도는 탕 순례가 명물.", bestSeason: "연중", stayTime: "반나절 또는 1박", access: "다자와코역에서 버스로 약 50분" },
    "ginzan-onsen": { name: "긴잔 온천", description: "다이쇼 로망 목조 여관이 강가에 늘어선 온천 마을. 가스등과 설경의 조합은 겨울의 풍물시.", bestSeason: "12〜2월", stayTime: "반나절 또는 1박", access: "오이시다역에서 버스로 약 40분" },
    "yamadera": { name: "야마데라(릿샤쿠지)", description: "절벽에 불당이 이어지는 천태종 고찰. 1,015계단을 오른 고다이도에서의 전망은 피로를 잊게 하는 절경.", bestSeason: "5〜11월", stayTime: "약 2시간", access: "야마가타역에서 JR로 약 20분 후 도보" },
    "ouchi-juku": { name: "오우치주쿠", description: "에도 시대 역참 마을의 초가지붕이 지금도 남아 있다. 파를 젓가락 삼아 먹는 '파 소바'가 명물.", bestSeason: "연중", stayTime: "약 2시간", access: "유노카미온센역에서 차로 약 10분" },
    "goshiki-numa": { name: "고시키누마", description: "반다이산 분화가 낳은 크고 작은 늪 무리. 코발트블루와 에메랄드그린으로 빛나는 늪을 탐승로로 돈다.", bestSeason: "5〜11월", stayTime: "약 2시간", access: "이나와시로역에서 버스로 약 30분" },
    "towadako": { name: "도와다호", description: "오이라세 계류의 수원인 도와다하치만타이 국립공원 중심의 칼데라호. 유람선과 호반의 '소녀상'이 정석.", bestSeason: "5〜10월", stayTime: "약 2시간", access: "하치노헤역에서 버스로 약 2시간 15분" },
    "hachinohe-yokocho": { name: "하치노헤 미로쿠 요코초", description: "포장마차 26곳이 이어진 골목. 센베이지루와 하치노헤 고등어 등 남부의 맛을 주인·단골과 어깨를 나란히 하고 즐긴다.", bestSeason: "연중", stayTime: "약 2시간", access: "혼하치노헤역에서 도보 약 10분" },
    "ryusendo": { name: "류센도", description: "일본 3대 종유동 중 하나. '드래곤 블루'라 불리는 세계 유수의 투명도를 자랑하는 지저호가 신비롭다.", bestSeason: "연중", stayTime: "약 1시간", access: "모리오카역에서 버스로 약 2시간 10분" },
    "genbikei": { name: "겐비케이", description: "구리코마산에서 발원한 이와이강이 깎아낸 계곡미. 건너편에서 밧줄을 타고 날아오는 '하늘을 나는 당고'가 명물.", bestSeason: "4〜11월", stayTime: "약 1시간", access: "이치노세키역에서 버스로 약 20분" },
    "akiu-onsen": { name: "아키우 온천", description: "'센다이의 안방'이라 불리는 오래된 온천. 근처에 낙차 55m의 아키우 대폭포와 기암이 이어지는 라이라이쿄 산책로도 있다.", bestSeason: "연중", stayTime: "반나절", access: "센다이역에서 버스로 약 50분" },
    "naruko-onsen": { name: "나루코 온천향", description: "고케시 인형과 게다 소리가 어울리는 탕치의 마을. 원천 약 370개, 일본 온천 수질의 약 70%가 모여 있다고 한다.", bestSeason: "10〜11월", stayTime: "반나절", access: "나루코온센역에서 도보 바로" },
    "tazawako": { name: "다자와호", description: "일본에서 가장 깊은(423m) 유리빛 호수. 호반에 선 황금 다쓰코상이 최고의 포토 스팟.", bestSeason: "5〜10월", stayTime: "약 2시간", access: "다자와코역에서 버스로 약 12분" },
    "oga-nyudozaki": { name: "오가반도 뉴도자키", description: "초록 대지와 파란 바다, 흑백 줄무늬 등대의 대비가 아름다운 곶. 나마하게의 고장으로도 유명하다.", bestSeason: "6〜9월", stayTime: "약 1시간 30분", access: "오가역에서 차로 약 30분" },
    "zao-onsen": { name: "자오 온천", description: "개탕 1,900년으로 전해지는 강산성 온천. 겨울에는 로프웨이에서 세계적으로도 드문 수빙 숲을 내려다볼 수 있다.", bestSeason: "12〜2월", stayTime: "반나절", access: "야마가타역에서 버스로 약 40분" },
    "sankyo-soko": { name: "사카타 산쿄 창고", description: "1893년에 지어진 쌀 창고 12동이 늘어선 항구 도시의 상징. 느티나무 가로수와 검은 벽의 경관은 영화 촬영지로도 쓰였다.", bestSeason: "연중", stayTime: "약 1시간", access: "사카타역에서 차로 약 5분" },
    "tsuruga-castle": { name: "아이즈와카마쓰 쓰루가성", description: "보신전쟁에서 한 달의 농성을 견딘 명성. 일본 유일의 붉은 기와 천수가 하늘에 빛난다.", bestSeason: "4〜11월", stayTime: "약 1시간 30분", access: "아이즈와카마쓰역에서 버스로 약 15분" },
    "kitakata": { name: "기타카타", description: "창고가 4,000동 넘게 남아 있는 '구라의 마을'. 아침부터 라멘을 먹는 '아침 라멘' 문화의 성지이기도 하다.", bestSeason: "연중", stayTime: "약 2시간", access: "기타카타역에서 도보 약 15분" },
    "hitachi-seaside-park": { name: "국영 히타치 해변공원", description: "봄에는 언덕을 파랗게 물들이는 네모필라, 가을에는 새빨간 코키아로 유명. 계절 꽃밭이 압권이다.", bestSeason: "4〜5월·10월", stayTime: "약 3시간", access: "가쓰타역에서 버스로 약 20분" },
    "fukuroda-falls": { name: "후쿠로다 폭포", description: "네 단으로 떨어지는 일본 3대 폭포 중 하나. 겨울엔 폭포 전체가 어는 '빙폭', 가을엔 단풍과의 협연이 훌륭하다.", bestSeason: "11월·1〜2월", stayTime: "약 1시간", access: "후쿠로다역에서 차로 약 10분" },
    "nikko-toshogu": { name: "닛코 도쇼구", description: "도쿠가와 이에야스를 모신 호화찬란한 세계유산. 요메이몬과 잠자는 고양이 등 볼거리가 가득. 게곤 폭포·주젠지호와 함께 돌고 싶다.", bestSeason: "연중", stayTime: "약 2시간", access: "도부닛코역에서 버스로 약 10분" },
    "ashikaga-flower-park": { name: "아시카가 플라워파크", description: "수령 160년이 넘는 대등나무 시렁이 환상적인 등꽃 명소. 겨울의 간토 3대 일루미네이션도 볼만하다.", bestSeason: "4월 중순〜5월 중순", stayTime: "약 2시간", access: "아시카가플라워파크역에서 바로" },
    "kusatsu-onsen": { name: "구사쓰 온천", description: "자연 용출량 일본 제일. 유바타케를 중심으로 온천 정취 가득한 거리가 펼쳐지고, 명물 '유모미'도 볼 수 있다.", bestSeason: "연중", stayTime: "반나절 또는 1박", access: "나가노하라쿠사쓰구치역에서 버스로 약 25분" },
    "ikaho-onsen": { name: "이카호 온천", description: "365계단 양쪽으로 숙소와 사격장이 늘어선 노스탤직한 온천 거리. 다갈색 '황금의 탕'이 명물.", bestSeason: "연중", stayTime: "반나절 또는 1박", access: "시부카와역에서 버스로 약 25분" },
    "kawagoe": { name: "가와고에", description: "'작은 에도'로 불리는 구라즈쿠리 거리. '시간의 종'과 과자 골목 등 먹으며 걷기 좋은 곳.", bestSeason: "연중", stayTime: "약 3시간", access: "가와고에역에서 도보 약 20분" },
    "nagatoro": { name: "나가토로", description: "바위 사이를 나룻배로 내려가는 뱃놀이가 명물인 계곡. 빙수 맛집과 호도산 전망도 즐겁다.", bestSeason: "4〜11월", stayTime: "약 3시간", access: "나가토로역에서 도보 약 5분" },
    "naritasan": { name: "나리타산 신쇼지", description: "천 년 넘는 역사의 부동존 신앙 총본산. 참배길 노포 장어집에서의 식도락도 즐겁다.", bestSeason: "연중", stayTime: "약 2시간", access: "나리타역에서 도보 약 10분" },
    "yoro-valley": { name: "요로 계곡", description: "보소 제일의 계곡미. 아와마타 폭포 산책과 흑탕 온천을 즐길 수 있는, 도쿄에서 가까운 힐링 마을.", bestSeason: "11월 하순〜12월 상순", stayTime: "약 3시간", access: "요로케이코쿠역에서 차로 약 10분" },
    "asakusa-sensoji": { name: "아사쿠사 센소지", description: "가미나리몬과 나카미세 거리로 유명한 도쿄에서 가장 오래된 절. 시타마치 먹거리와 인력거도 인기.", bestSeason: "연중", stayTime: "약 2시간", access: "아사쿠사역에서 바로" },
    "meiji-jingu": { name: "메이지 신궁", description: "도심이라고는 믿기지 않는 깊은 숲에 안긴 신역. 하라주쿠역 바로 옆 대도리이를 지나면 고요한 참배길이 이어진다.", bestSeason: "연중", stayTime: "약 1시간 30분", access: "하라주쿠역에서 바로" },
    "tsukiji-market": { name: "쓰키지 장외시장", description: "약 400개 점포가 빼곡한 음식의 원더랜드. 해산물덮밥과 계란말이 먹거리 탐방은 아침에 가는 것이 정답.", bestSeason: "연중", stayTime: "약 2시간", access: "쓰키지역에서 바로" },
    "kamakura": { name: "가마쿠라", description: "쓰루가오카 하치만구와 대불, 고마치 거리 먹거리, 에노덴 바닷가 열차까지 하루 종일 즐길 수 있는 고도.", bestSeason: "연중", stayTime: "반나절〜1일", access: "가마쿠라역에서 도보 약 10분" },
    "hakone-ashinoko": { name: "하코네 아시노코", description: "해적선이 떠 있는 호수 너머로 후지산을 바라보는 정통 리조트. 오와쿠다니 검은 달걀과 명탕 순례도 빼놓을 수 없다.", bestSeason: "연중", stayTime: "반나절 또는 1박", access: "하코네유모토역에서 버스로 약 35분" },
    "kairakuen": { name: "가이라쿠엔", description: "일본 3대 정원 중 하나. 약 100종 3,000그루의 매화가 피어나는 2〜3월 매화축제가 볼거리.", bestSeason: "2〜3월", stayTime: "약 1시간 30분", access: "미토역에서 버스로 약 20분" },
    "kegon-falls": { name: "게곤 폭포", description: "주젠지호의 물이 97m를 단숨에 떨어지는 일본 3대 폭포. 엘리베이터로 폭포 아래 전망대까지 내려갈 수 있다.", bestSeason: "10〜11월", stayTime: "약 1시간", access: "도부닛코역에서 버스로 약 45분" },
    "utsunomiya-gyoza": { name: "우쓰노미야 교자의 거리", description: "전문점이 200곳을 넘는 '교자의 도시'. 구운·튀긴·물교자를 가게마다 비교하며 도는 재미가 있다.", bestSeason: "연중", stayTime: "약 2시간", access: "우쓰노미야역에서 도보권" },
    "tomioka-silk-mill": { name: "도미오카 제사장", description: "1872년 개업한 관영 제사 공장으로 세계유산. 조사소와 누에고치 창고가 거의 완전한 형태로 남아 있다.", bestSeason: "연중", stayTime: "약 1시간 30분", access: "조슈토미오카역에서 도보 약 15분" },
    "shima-onsen": { name: "시마 온천", description: "'4만 가지 병을 고친다'고 전해지는 명탕. 맑고 푸른 시마강과 오쿠시마호의 '시마 블루'도 볼거리.", bestSeason: "연중", stayTime: "반나절", access: "나카노조역에서 버스로 약 40분" },
    "chichibu-hitsujiyama": { name: "지치부 히쓰지야마 공원", description: "부코산을 배경으로 약 40만 포기의 시바자쿠라가 언덕을 물들인다. 절정인 4월 중순〜5월 상순에는 노점도 늘어서 붐빈다.", bestSeason: "4〜5월", stayTime: "약 1시간 30분", access: "세이부치치부역에서 도보 약 20분" },
    "nokogiriyama": { name: "노코기리야마 니혼지", description: "절벽에서 튀어나온 '지옥 엿보기'와 일본 최대 마애대불. 로프웨이로 정상까지.", bestSeason: "연중", stayTime: "반나절", access: "하마카나야역에서 도보와 로프웨이로 약 20분" },
    "shibuya-crossing": { name: "시부야 스크램블 교차로", description: "한 번의 신호에 최대 3,000명이 오간다는 세계적 명소. 전망시설에서 내려다보는 밤의 교차로도 인기.", bestSeason: "연중", stayTime: "약 1시간", access: "시부야역에서 도보 바로" },
    "ameyoko": { name: "우에노 아메요코", description: "고가 아래 약 400개 점포가 빼곡한 상점가. 먹거리 탐방과 활기찬 호객이 즐거운 시타마치의 부엌.", bestSeason: "연중", stayTime: "약 2시간", access: "우에노역에서 도보 바로" },
    "takaosan": { name: "다카오산", description: "도심에서 전철로 약 1시간, 미슐랭 3스타의 산. 케이블카와 명물 덴구야키, 맑으면 정상에서 후지산도 보인다.", bestSeason: "11월", stayTime: "반나절", access: "다카오산구치역에서 도보 바로" },
    "yokohama-chukagai": { name: "요코하마 중화가", description: "약 600개 점포가 모인 일본 최대의 중화 거리. 길거리 음식부터 노포 명점까지, 위가 몇 개라도 모자란다.", bestSeason: "연중", stayTime: "약 3시간", access: "모토마치·주카가이역에서 도보 바로" },
    "enoshima": { name: "에노시마", description: "참배길 먹거리와 씨캔들 전망대에서 보는 사가미만. 맑은 날에는 후지산도 보이는 쇼난의 상징.", bestSeason: "연중", stayTime: "반나절", access: "가타세에노시마역에서 도보 약 15분" },
    "kiyotsu-gorge": { name: "기요쓰쿄", description: "일본 3대 협곡 중 하나. 터널 끝 '파노라마 스테이션'의 수경이 협곡을 비추는 필견의 아트 공간.", bestSeason: "4〜11월", stayTime: "약 1시간 30분", access: "에치고유자와역에서 차로 약 25분" },
    "sado-island": { name: "사도섬", description: "다라이부네(대야배)와 세계유산 금산으로 유명한 동해 최대의 섬. 센카쿠만 등 손대지 않은 해안미가 이어진다.", bestSeason: "5〜10월", stayTime: "1일 이상", access: "니가타항에서 페리로 약 2시간 30분" },
    "tateyama-kurobe": { name: "다테야마 구로베 알펜루트", description: "해발 3,000m급 산들을 탈것으로 넘는 산악 관광 루트. 봄의 '눈의 대계곡'과 구로베댐 방수가 유명하다.", bestSeason: "4〜11월", stayTime: "1일", access: "다테야마역 또는 오기자와에서 케이블카 등 환승" },
    "ainokura": { name: "고카야마 아이노쿠라 합장촌", description: "시라카와고와 함께 세계유산에 등재된 산간 합장 마을. 지나치게 관광지화되지 않은 고요함이 매력.", bestSeason: "연중", stayTime: "약 1시간 30분", access: "조하나역에서 차로 약 25분" },
    "kenrokuen": { name: "가나자와 겐로쿠엔", description: "일본 3대 정원 중 하나. 히가시차야 거리 산책과 오미초 시장의 해산물도 함께 즐기고 싶다.", bestSeason: "연중", stayTime: "약 2시간", access: "가나자와역에서 버스로 약 15분" },
    "chirihama": { name: "지리하마 나기사 드라이브웨이", description: "일본에서 유일하게 파도 옆을 차로 달릴 수 있는 약 8km의 모래사장. 석양 무렵 드라이브는 영화의 한 장면 같다.", bestSeason: "4〜11월", stayTime: "약 1시간", access: "가나자와역에서 차로 약 45분" },
    "tojinbo": { name: "도진보", description: "동해의 거친 파도가 깎아낸 주상절리 절벽. 유람선에서 올려다보는 암벽과 석양의 풍경이 압권.", bestSeason: "연중", stayTime: "약 1시간 30분", access: "아와라온센역에서 버스로 약 40분" },
    "eiheiji": { name: "에이헤이지", description: "도겐 선사가 연 조동종 대본산. 노삼나무에 둘러싸인 칠당가람을 회랑으로 돌면 마음이 고요해진다.", bestSeason: "연중", stayTime: "약 2시간", access: "후쿠이역에서 버스로 약 30분" },
    "kawaguchiko": { name: "가와구치호", description: "후지산 절경 포인트로 이름난 호수. 호반 온천 숙소에서 바라보는 '거꾸로 후지'는 각별하다.", bestSeason: "연중", stayTime: "반나절", access: "가와구치코역에서 순환버스" },
    "oshino-hakkai": { name: "오시노핫카이", description: "후지산 복류수가 솟는 8개의 맑은 연못. 초가지붕 마을 풍경과 바닥까지 보이는 푸른 수면이 아름답다.", bestSeason: "연중", stayTime: "약 1시간 30분", access: "후지산역에서 버스로 약 20분" },
    "kamikochi": { name: "가미코치", description: "아즈사강이 호타카 연봉을 비추고 갓파바시가 놓인 해발 1,500m의 산악 리조트. 여름에도 시원하게 산책할 수 있다.", bestSeason: "5〜10월", stayTime: "반나절", access: "마쓰모토역에서 버스 등으로 약 1시간 30분(자가용 규제)" },
    "matsumoto-castle": { name: "마쓰모토성", description: "북알프스를 등지고 솟은 칠흑의 현존 천수. 해자에 비치는 '거꾸로 마쓰모토성'과 성 아래 공예 상점 순례도 즐겁다.", bestSeason: "연중", stayTime: "약 2시간", access: "마쓰모토역에서 도보 약 15분" },
    "shirakawago": { name: "시라카와고", description: "합장촌 마을의 세계유산. 전망대에서 내려다보는 마을 풍경은 사계절 저마다 그림이 된다.", bestSeason: "연중", stayTime: "약 3시간", access: "다카야마에서 버스로 약 50분" },
    "takayama": { name: "히다 다카야마 옛거리", description: "격자문 상가가 이어지는 조카마치. 히다규 초밥과 아침시장 먹거리, 술도가 순례로 '히다의 작은 교토'를 만끽.", bestSeason: "연중", stayTime: "약 3시간", access: "다카야마역에서 도보 약 10분" },
    "atami-onsen": { name: "아타미 온천", description: "도쿄에서 접근성 좋은 바닷가 온천 거리. 상점가 먹거리 탐방과 해상 불꽃놀이도 인기.", bestSeason: "연중", stayTime: "반나절 또는 1박", access: "아타미역에서 도보 바로" },
    "miho-no-matsubara": { name: "미호노마쓰바라", description: "날개옷 전설의 솔밭 너머로 후지산을 바라보는 세계문화유산. 백사청송과 스루가만의 파노라마는 우키요에 그 자체.", bestSeason: "11〜2월(후지산이 잘 보임)", stayTime: "약 1시간 30분", access: "시미즈역에서 버스로 약 25분" },
    "nagoya-castle": { name: "나고야성", description: "금 샤치호코가 빛나는 오와리 도쿠가와가의 거성. 호화로운 혼마루 어전의 복원 장벽화는 필견. 긴샤치 요코초에서 미식도.", bestSeason: "연중", stayTime: "약 2시간", access: "지하철 나고야조역에서 바로" },
    "inuyama-castle": { name: "이누야마성과 조카마치", description: "기소강을 내려다보는 국보 천수와 먹거리로 붐비는 조카마치. 천수 꼭대기에서의 조망은 성주가 된 기분.", bestSeason: "연중", stayTime: "약 3시간", access: "이누야마역에서 도보 약 20분" },
    "yahiko-shrine": { name: "야히코 신사", description: "2,400년 역사의 에치고 제일 신사. 야히코산 로프웨이로 정상에 오르면 에치고 평야와 동해의 대파노라마.", bestSeason: "10〜11월", stayTime: "약 2시간", access: "야히코역에서 도보 약 15분" },
    "echigo-yuzawa": { name: "에치고유자와 온천", description: "가와바타 야스나리 『설국』의 무대가 된 온천지. 역 구내 '폰슈관'에서는 니가타 거의 모든 양조장의 사케를 시음할 수 있다.", bestSeason: "12〜3월", stayTime: "반나절", access: "에치고유자와역에서 도보 바로" },
    "kurobe-gorge": { name: "구로베 협곡 도롯코 열차", description: "일본에서 가장 깊은 V자 협곡을 창 없는 도롯코 열차로 달린다. 발아래 구로베강과 온통 단풍이 압권.", bestSeason: "10〜11월", stayTime: "반나절", access: "우나즈키온센역 바로 옆 우나즈키역에서 승차" },
    "amaharashi": { name: "아마하라시 해안", description: "도야마만 너머로 3,000m급 다테야마 연봉을 바라보는 기적의 풍경. 겨울 아침 바다 안개가 피어오르면 환상적이다.", bestSeason: "11〜2월", stayTime: "약 1시간", access: "아마하라시역에서 도보 약 5분" },
    "higashi-chaya": { name: "가나자와 히가시차야 거리", description: "격자문 찻집 건물이 이어지는 가나자와 제일의 정취. 금박 소프트아이스크림과 마치야 카페 탐방도 즐겁다.", bestSeason: "연중", stayTime: "약 2시간", access: "가나자와역에서 버스로 약 10분" },
    "omicho-market": { name: "오미초 시장", description: "약 170개 점포가 늘어선 '가나자와 시민의 부엌'. 게·단새우·노도구로, 해산물덮밥 명점에는 아침부터 줄이 선다.", bestSeason: "11〜2월", stayTime: "약 1시간 30분", access: "가나자와역에서 도보 약 15분" },
    "wakura-onsen": { name: "와쿠라 온천", description: "나나오만을 마주한 '바다의 온천'. 개탕 1,200년, 탕 순례와 노토의 해산물이 자랑.", bestSeason: "연중", stayTime: "반나절", access: "와쿠라온센역에서 차로 약 5분" },
    "mikatagoko": { name: "미카타고코 레인보라인", description: "다섯 호수가 저마다 다른 파랑으로 보이는 절경 드라이브웨이. 산정 공원의 족욕탕과 테라스에서 한눈에 담을 수 있다.", bestSeason: "4〜11월", stayTime: "약 2시간", access: "미카타역에서 차로 약 15분" },
    "echizen-ono-castle": { name: "에치젠 오노성", description: "가을부터 겨울 새벽, 운해 위에 떠오르는 '천공의 성'. 성 아래 마을은 명수의 고장으로 400년 이어진 아침시장도 있다.", bestSeason: "10〜4월", stayTime: "약 2시간", access: "에치젠오노역에서 도보 약 30분" },
    "arakurayama-sengen": { name: "아라쿠라야마 센겐 공원", description: "오층탑과 벚꽃 너머 후지산을 담는, 해외에서 가장 유명한 일본 풍경 중 하나. 398계단을 오르면 절경이 기다린다.", bestSeason: "4월", stayTime: "약 1시간 30분", access: "시모요시다역에서 도보 약 20분" },
    "hottarakashi-onsen": { name: "홋타라카시 온천", description: "해발 700m에서 고후 분지와 후지산을 내려다보는 절경 노천탕. 해돋이 1시간 전에 여는 아침탕이 명물.", bestSeason: "연중", stayTime: "약 2시간", access: "야마나시시역에서 차로 약 10분" },
    "zenkoji": { name: "젠코지", description: "'일생에 한 번은 젠코지 참배'로 친숙한 무종파 고찰. 캄캄한 회랑을 더듬어 가는 '계단 순례'는 꼭 체험해 보자.", bestSeason: "연중", stayTime: "약 2시간", access: "나가노역에서 버스로 약 10분" },
    "jigokudani-yaen": { name: "지고쿠다니 야생원숭이 공원", description: "온천에 몸을 담그는 일본원숭이 '스노 몽키'를 가까이서 관찰할 수 있는 세계 유일의 장소.", bestSeason: "12〜3월", stayTime: "약 2시간", access: "유다나카역에서 버스와 도보로 약 1시간" },
    "narai-juku": { name: "나라이주쿠", description: "나카센도의 역참 마을로 일본에서 가장 긴 약 1km의 거리가 남아 있다. 칠기와 고헤이모치, 기소지의 정취를 느끼며 걷는다.", bestSeason: "4〜11월", stayTime: "약 2시간", access: "나라이역에서 도보 바로" },
    "gero-onsen": { name: "게로 온천", description: "일본 3대 명탕에 꼽히는 '미인의 탕'. 온천 거리에 무료 족욕탕이 곳곳에 있고, '유메구리 패스'로 명탕을 돌 수 있다.", bestSeason: "연중", stayTime: "반나절", access: "게로역에서 도보 바로" },
    "gujo-hachiman": { name: "구조하치만", description: "마을 곳곳에 수로가 흐르는 '물의 도시'. 여름 구조오도리는 32일 밤 이어지며, 오본의 밤샘춤에서 절정을 맞는다.", bestSeason: "7〜8월", stayTime: "약 2시간", access: "구조하치만역에서 도보 약 20분" },
    "shuzenji-onsen": { name: "슈젠지 온천", description: "이즈에서 가장 오래된 온천장. 대나무숲 오솔길과 주홍빛 가쓰라바시, 강 가운데 솟는 '돗코의 탕'이 여정을 부른다.", bestSeason: "11월", stayTime: "반나절", access: "슈젠지역에서 버스로 약 10분" },
    "jogasaki": { name: "조가사키 해안", description: "용암이 만든 절벽 해안선. 높이 23m의 바다 위 출렁다리 '가도와키 현수교'는 스릴 만점.", bestSeason: "연중", stayTime: "약 2시간", access: "이즈코겐역에서 도보 약 35분" },
    "atsuta-jingu": { name: "아쓰타 신궁", description: "삼종신기 구사나기 검을 모시는 격식 높은 신사. 문 앞 히쓰마부시 명점도 참배와 세트로 인기.", bestSeason: "연중", stayTime: "약 1시간 30분", access: "진구마에역에서 도보 약 3분" },
    "osu": { name: "오스 상점가", description: "오스칸논 문전에 약 1,200개 점포. 전자상가·빈티지·먹거리가 뒤섞인 나고야의 카오스한 부엌.", bestSeason: "연중", stayTime: "약 2시간", access: "오스칸논역에서 도보 바로" },
    "ise-jingu": { name: "이세 신궁", description: "'오이세상'으로 친숙한 일본의 총 우지가미. 참배 후에는 오카게 요코초에서 이세 우동과 아카후쿠를.", bestSeason: "연중", stayTime: "약 3시간", access: "이스즈가와역에서 버스로 약 6분" },
    "meoto-iwa": { name: "후타미오키타마 신사·메오토이와", description: "큰 금줄로 맺어진 크고 작은 바위가 바다에 떠 있는 인연의 성지. 5〜7월에는 바위 사이로 떠오르는 아침해를 볼 수 있다.", bestSeason: "5〜7월", stayTime: "약 1시간", access: "후타미노우라역에서 도보 약 15분" },
    "hikone-castle": { name: "히코네성", description: "비와호를 내려다보는 국보 현존 천수. 겐큐엔의 차경 정원과 마스코트의 원조 히코냥도 만날 수 있다.", bestSeason: "연중", stayTime: "약 2시간", access: "히코네역에서 도보 약 15분" },
    "shirahige-shrine": { name: "시라히게 신사", description: "비와호 호수 안에 주홍 대도리이가 선 '오미의 이쓰쿠시마'. 아침노을과 달밤에 떠오르는 도리이는 숨막히게 아름답다.", bestSeason: "연중", stayTime: "약 30분", access: "오미타카시마역에서 차로 약 5분" },
    "fushimi-inari": { name: "후시미이나리 대사", description: "산꼭대기까지 이어지는 센본도리이는 이곳에서만 볼 수 있는 풍경. 이른 아침 참배가 노림수.", bestSeason: "연중", stayTime: "약 2시간", access: "JR 이나리역에서 바로" },
    "arashiyama": { name: "아라시야마", description: "도게쓰교와 대나무숲 오솔길로 유명한 교토 굴지의 절경지. 도롯코 열차와 호즈강 뱃놀이도 즐길 수 있다.", bestSeason: "11월", stayTime: "반나절", access: "아라시야마역에서 바로" },
    "kinkakuji": { name: "긴카쿠지(금각사)", description: "교코치 연못에 금빛 누각이 비치는 교토의 대명사. 눈 화장한 아침의 금각은 일생에 한 번뿐인 광경.", bestSeason: "연중", stayTime: "약 1시간", access: "교토역에서 버스로 약 40분" },
    "nara-park": { name: "나라 공원·도다이지", description: "대불전과 공원을 자유로이 거니는 약 1,200마리의 사슴. 가스가타이샤와 고후쿠지도 도보권.", bestSeason: "연중", stayTime: "약 3시간", access: "긴테쓰나라역에서 도보 약 5분" },
    "yoshinoyama": { name: "요시노산", description: "'한눈에 천 그루'라 칭송받는 일본 제일의 벚꽃 명소. 약 3만 그루의 산벚나무가 아래에서 위로 차례로 피어난다.", bestSeason: "4월", stayTime: "반나절", access: "요시노역에서 로프웨이" },
    "dotonbori": { name: "도톤보리", description: "글리코 간판과 네온이 빛나는 오사카 미나미의 중심. 다코야키·구시카쓰 등 '먹다 쓰러지는' 거리.", bestSeason: "연중", stayTime: "약 3시간", access: "난바역에서 도보 약 5분" },
    "osaka-castle": { name: "오사카성", description: "도요토미 히데요시가 쌓은 천하의 명성. 거석 석벽과 드넓은 공원은 도심의 오아시스이자 봄 벚꽃 명소.", bestSeason: "연중", stayTime: "약 2시간", access: "오사카조코엔역에서 도보 약 15분" },
    "himeji-castle": { name: "히메지성", description: "백로성이라는 이름을 가진 일본 최초의 세계문화유산. 현존 천수의 흰 벽의 아름다움은 격이 다르다.", bestSeason: "연중", stayTime: "약 2시간 30분", access: "히메지역에서 도보 약 20분" },
    "kinosaki-onsen": { name: "기노사키 온천", description: "버드나무 강가를 유카타와 게다 차림으로 걷는 외탕 순례의 온천 거리. 겨울에는 대게의 본고장으로도 유명.", bestSeason: "11〜3월", stayTime: "1박", access: "기노사키온센역에서 도보 바로" },
    "shirahama": { name: "난키시라하마 시라라하마", description: "새하얀 모래사장과 푸른 바다가 이어지는 간사이 굴지의 리조트. 일본 3고탕 시라하마 온천과 엔게쓰섬의 석양도 볼거리.", bestSeason: "6〜9월", stayTime: "반나절 또는 1박", access: "시라하마역에서 버스로 약 15분" },
    "nachi-falls": { name: "나치 폭포·구마노나치 대사", description: "낙차 133m 일본 제일의 명폭과 주홍 삼중탑이 나란한 구마노 신앙의 성지. 다이몬자카 돌계단을 걸어 참배하고 싶다.", bestSeason: "연중", stayTime: "약 3시간", access: "기이카쓰우라역에서 버스로 약 30분" },
    "okage-yokocho": { name: "오카게 요코초", description: "이세 신궁 내궁 앞, 에도〜메이지의 이세 길을 재현한 거리. 아카후쿠 본점과 이세 우동, 먹거리 천국.", bestSeason: "연중", stayTime: "약 2시간", access: "이세시역에서 버스로 약 15분" },
    "enryakuji": { name: "히에이잔 엔랴쿠지", description: "사이초가 열고 1,200년 '불멸의 법등'이 타오르는 천태종 총본산. 세계유산의 산 전체가 수행의 장.", bestSeason: "10〜11월", stayTime: "반나절", access: "교토역에서 전철과 케이블로 약 1시간" },
    "kiyomizudera": { name: "기요미즈데라", description: "'기요미즈의 무대'에서 교토 시가를 한눈에 담는 세계유산. 니넨자카·산넨자카 참배길 걷기도 여행의 묘미.", bestSeason: "4월·11월", stayTime: "약 2시간", access: "교토역에서 버스와 도보로 약 25분" },
    "gion": { name: "기온 하나미코지", description: "찻집이 이어지는 돌바닥 하나마치. 해질녘에는 마이코를 만날 수 있을지도.", bestSeason: "연중", stayTime: "약 1시간 30분", access: "기온시조역에서 도보 약 5분" },
    "nishiki-market": { name: "니시키 시장", description: "400년 역사의 '교토의 부엌'. 약 130개 점포에서 교토 절임·유바·두유 도넛을 먹으며 걷는다.", bestSeason: "연중", stayTime: "약 1시간 30분", access: "가라스마역에서 도보 약 3분" },
    "amanohashidate": { name: "아마노하시다테", description: "일본 3경 중 하나, 전장 3.6km의 사주. 전망대에서 '가랑이 사이로 보기'를 하면 하늘에 걸린 다리처럼 보인다.", bestSeason: "연중", stayTime: "반나절", access: "아마노하시다테역에서 도보 바로" },
    "ine-funaya": { name: "이네의 후나야", description: "바다 위에 약 230채의 후나야가 늘어선 어촌. 해상 택시에서 보는 마을 풍경은 마치 수상 도시.", bestSeason: "연중", stayTime: "약 2시간", access: "아마노하시다테역에서 버스로 약 1시간" },
    "horyuji": { name: "호류지", description: "현존하는 세계에서 가장 오래된 목조 건축군. 오층탑과 백제관음, 교과서에서 본 아스카의 세계를 걷는다.", bestSeason: "연중", stayTime: "약 2시간", access: "호류지역에서 도보 약 20분" },
    "hasedera": { name: "하세데라", description: "399계단의 등랑을 오르는 '꽃의 사찰'. 모란과 수국, 단풍까지 사계절 꽃에 파묻히는 산사.", bestSeason: "4〜6월", stayTime: "약 2시간", access: "하세데라역에서 도보 약 15분" },
    "asuka": { name: "아스카무라", description: "이시부타이 고분과 다카마쓰즈카 고분이 전원에 점재하는 일본의 원풍경. 자전거를 빌려 아스카 시대를 돈다.", bestSeason: "3〜5월·9〜11월", stayTime: "반나절", access: "아스카역에서 자전거로 각지로" },
    "shinsekai": { name: "신세카이 쓰텐카쿠", description: "구시카쓰에 도테야키, 화려한 간판들. 쓰텐카쿠를 중심으로 쇼와 레트로 가득한 오사카의 딥한 지대.", bestSeason: "연중", stayTime: "약 2시간", access: "에비스초역에서 도보 약 3분" },
    "minoo-falls": { name: "미노오 폭포", description: "오사카 시내에서 전철로 30분 만에 닿는 낙차 33m의 명폭. 폭포길 단풍과 명물 '단풍잎 튀김'이 가을 풍물시.", bestSeason: "11월", stayTime: "약 2시간", access: "미노오역에서 도보 약 40분" },
    "arima-onsen": { name: "아리마 온천", description: "도요토미 히데요시도 사랑한 일본 3고탕. 철분으로 붉게 물든 '금천'과 무색투명한 '은천'을 순례한다.", bestSeason: "연중", stayTime: "반나절", access: "고베전철 아리마온센역에서 도보 약 5분" },
    "takeda-castle": { name: "다케다성 터", description: "가을 새벽 운해 위에 떠오르는 '천공의 성'. 맞은편 리쓰운쿄에서 바라보는 석벽 실루엣은 숨이 멎는다.", bestSeason: "9〜11월", stayTime: "약 2시간", access: "다케다역에서 텐쿠버스로 약 20분" },
    "koyasan": { name: "고야산", description: "구카이가 연 해발 800m의 종교 도시. 오쿠노인의 삼나무숲, 사찰 숙소의 정진 요리와 아침 근행으로 마음이 정돈된다.", bestSeason: "5〜11월", stayTime: "1일", access: "고쿠라쿠바시역에서 케이블로 약 5분" },
    "kumano-kodo": { name: "구마노고도 다이몬자카", description: "수령 800년 삼나무 가로수 아래 이끼 낀 돌길이 이어지는 참배길. 다이몬자카에서 나치 폭포까지 성지로의 약 2.5km를 걷는다.", bestSeason: "3〜5월·10〜11월", stayTime: "약 2시간", access: "기이카쓰우라역에서 버스로 약 20분" },
    "tottori-sakyu": { name: "돗토리 사구", description: "일본 최대급 사구. 낙타 타기와 샌드보드 체험이 가능하고, 인접한 모래 미술관도 볼만하다.", bestSeason: "연중", stayTime: "약 2시간", access: "돗토리역에서 버스로 약 20분" },
    "mizuki-shigeru-road": { name: "미즈키 시게루 로드", description: "177개의 요괴 동상이 늘어선 사카이미나토의 상점가. 밤에는 요괴 그림자가 길에 떠올라 낮과 다른 얼굴을 보여준다.", bestSeason: "연중", stayTime: "약 2시간", access: "사카이미나토역에서 바로" },
    "izumo-taisha": { name: "이즈모 대사", description: "인연 맺기의 신으로 이름 높은 고사. 거대한 금줄은 박력 만점. 몬젠마치의 이즈모 소바도 명물.", bestSeason: "연중", stayTime: "약 2시간", access: "이즈모시역에서 버스로 약 25분" },
    "adachi-museum": { name: "아다치 미술관", description: "'살아있는 일본화'로 불리는 정원이 미국 잡지 일본 정원 랭킹에서 연속 1위. 요코야마 다이칸 컬렉션도 필견.", bestSeason: "연중", stayTime: "약 2시간", access: "야스기역에서 무료 셔틀버스로 약 20분" },
    "kurashiki": { name: "구라시키 미관지구", description: "흰 벽 창고 저택과 버드나무가 이어지는 운하 마을. 나룻배 유람과 데님 스트리트 산책이 즐겁다.", bestSeason: "연중", stayTime: "약 3시간", access: "구라시키역에서 도보 약 15분" },
    "korakuen": { name: "오카야마 고라쿠엔", description: "오카야마성을 차경으로 삼은 일본 3대 정원 중 하나. 드넓은 잔디와 곡수가 주는 개방감은 다른 명원에 없는 매력.", bestSeason: "연중", stayTime: "약 1시간 30분", access: "오카야마역에서 버스로 약 15분" },
    "itsukushima": { name: "이쓰쿠시마 신사", description: "바다에 떠 있는 대도리이로 유명한 세계유산. 썰물 때는 도리이까지 걸어갈 수 있다. 미야지마 명물 아나고메시와 모미지만주도.", bestSeason: "연중", stayTime: "약 3시간", access: "미야지마구치에서 페리로 약 10분" },
    "genbaku-dome": { name: "원폭 돔·평화기념공원", description: "핵무기의 참화를 오늘에 전하는 세계유산. 자료관과 함께 조용히 평화를 기원하고 싶은 곳.", bestSeason: "연중", stayTime: "약 2시간", access: "히로시마역에서 노면전차로 약 15분" },
    "onomichi": { name: "오노미치", description: "언덕과 고양이와 절의 마을. 센코지에서 보는 오노미치 수도, 골목 산책, 오노미치 라멘까지 즐거움이 가득.", bestSeason: "연중", stayTime: "반나절", access: "오노미치역에서 도보 바로" },
    "tsunoshima-bridge": { name: "쓰노시마 대교", description: "에메랄드그린 바다 위로 일직선으로 뻗은 약 1,780m의 다리. 드라이브 절경의 대명사.", bestSeason: "5〜9월", stayTime: "약 1시간", access: "신시모노세키역에서 차로 약 1시간" },
    "kintaikyo": { name: "긴타이교", description: "5연속 목조 아치가 니시키강에 걸린 일본 3대 명교. 벚꽃과 가마우지 낚시 철에는 한층 그림이 된다.", bestSeason: "4월·6〜8월", stayTime: "약 1시간 30분", access: "이와쿠니역에서 버스로 약 20분" },
    "motonosumi-shrine": { name: "모토노스미 신사", description: "123기의 주홍 도리이가 바다를 향해 이어지는 절경 신사. 일본에서 가장 넣기 어려운 새전함(도리이 위)에도 도전을.", bestSeason: "연중", stayTime: "약 1시간", access: "나가토시역에서 차로 약 20분" },
    "misasa-onsen": { name: "미사사 온천", description: "세계 유수의 라돈천. 미토쿠강 물소리를 들으며 즐기는 강가 노천탕과 레트로한 온천 거리가 매력.", bestSeason: "연중", stayTime: "반나절", access: "구라요시역에서 버스로 약 25분" },
    "matsue-castle": { name: "마쓰에성", description: "전국에 12곳뿐인 현존 천수 중 하나로 국보. 해자 유람선에서 바라보는 성 아래 마을도 정취 가득.", bestSeason: "연중", stayTime: "약 2시간", access: "마쓰에역에서 버스로 약 10분" },
    "tamatsukuri-onsen": { name: "다마쓰쿠리 온천", description: "『이즈모국 풍토기』에도 등장하는 미인탕. 다마유강을 따라 곡옥 다리와 족욕탕이 이어지고 밤에는 등불이 켜진다.", bestSeason: "연중", stayTime: "반나절", access: "다마쓰쿠리온센역에서 차로 약 5분" },
    "bitchu-matsuyama-castle": { name: "빗추 마쓰야마성", description: "해발 430m, 현존 천수 중 가장 높은 곳에 선 산성. 가을 아침에는 운해에 뜬 모습을 전망대에서 노릴 수 있다.", bestSeason: "9〜4월", stayTime: "약 2시간", access: "빗추타카하시역에서 합승 택시와 도보로 약 30분" },
    "okunoshima": { name: "오쿠노시마(토끼섬)", description: "약 500마리의 야생 토끼가 사는 '토끼섬'. 페리로 15분, 자전거 일주는 약 1시간.", bestSeason: "연중", stayTime: "반나절", access: "다다노우미항에서 페리로 약 15분" },
    "saijo-sakagura": { name: "히가시히로시마 사이조 사카구라 거리", description: "붉은 벽돌 굴뚝과 흰 벽 술도가가 늘어선 일본 3대 술 산지. 일곱 양조장을 돌며 시음할 수 있다.", bestSeason: "10월", stayTime: "약 2시간", access: "사이조역에서 도보 약 5분" },
    "akiyoshido": { name: "아키요시도·아키요시다이", description: "일본 최대급 카르스트 대지와 그 지하에 펼쳐진 대종유동. 햐쿠마이자라와 황금기둥은 필견.", bestSeason: "연중", stayTime: "반나절", access: "신야마구치역에서 버스로 약 40분" },
    "hagi": { name: "하기 조카마치", description: "요시다 쇼인과 유신 지사들을 낳은 조카마치. 여름밀감 토담과 무가 저택을 자전거로 돈다.", bestSeason: "연중", stayTime: "반나절", access: "히가시하기역에서 자전거로 약 10분" },
    "iya-kazurabashi": { name: "이야의 가즈라바시", description: "깊은 계곡에 걸린 덩굴 다리. 발밑 틈새로 내려다보이는 계곡은 스릴 만점.", bestSeason: "4〜11월", stayTime: "약 1시간", access: "오보케역에서 차로 약 20분" },
    "naruto-whirlpools": { name: "나루토 소용돌이", description: "세계 최대급 소용돌이가 이는 나루토 해협. 관조선으로 다가가거나, '소용돌이의 길' 유리 바닥에서 바로 위에서 내려다보거나.", bestSeason: "봄·가을 사리 때", stayTime: "약 2시간", access: "나루토역에서 버스로 약 20분" },
    "kotohiragu": { name: "고토히라구", description: "'곤피라상'으로 친숙한 785계단 위의 본궁. 참배길의 사누키 우동도 빼놓을 수 없다.", bestSeason: "연중", stayTime: "약 3시간", access: "고토히라역에서 도보+돌계단 785단" },
    "chichibugahama": { name: "지치부가하마", description: "썰물 해질녘 물웅덩이가 거울이 되는 '일본의 우유니 소금호수'. 인생샷을 부르는 석양 명소.", bestSeason: "연중", stayTime: "약 1시간 30분", access: "다쿠마역에서 차로 약 10분" },
    "dogo-onsen": { name: "도고 온천", description: "일본에서 가장 오래된 급의 온천. 중요문화재인 도고온천 본관 입욕과 유카타 차림 상점가 산책이 정석.", bestSeason: "연중", stayTime: "반나절 또는 1박", access: "도고온센역에서 바로" },
    "shimanami-kaido": { name: "시마나미 해도", description: "세토우치 섬들을 다리로 잇는 라이더의 성지. 기로산 전망공원에서 보는 다도해와 다리의 파노라마는 압권.", bestSeason: "3〜11월", stayTime: "반나절〜1일", access: "이마바리역·오노미치역에서 렌터사이클" },
    "shimanto-river": { name: "시만토강", description: "'일본 최후의 청류'. 난간 없는 침하교와 놀잇배 뱃놀이로 느긋한 시간을 보낼 수 있다.", bestSeason: "5〜10월", stayTime: "반나절", access: "나카무라역에서 차로 약 15분(사다 침하교)" },
    "katsurahama": { name: "가쓰라하마", description: "사카모토 료마 동상이 태평양을 바라보는 활 모양 해변. 달맞이 명소로 유명하며, 히로메 시장의 가다랑어 다타키와 세트로.", bestSeason: "연중", stayTime: "약 1시간 30분", access: "고치역에서 버스로 약 40분" },
    "oboke-koboke": { name: "오보케·고보케", description: "요시노강 급류가 2억 년에 걸쳐 깎아낸 계곡. 유람선과 래프팅으로 에메랄드 물살과 기암을 가까이서.", bestSeason: "4〜11월", stayTime: "약 2시간", access: "오보케역에서 도보 약 20분" },
    "awaodori-kaikan": { name: "아와오도리 회관", description: "400년 이어진 아와오도리를 일 년 내내 체험할 수 있다. 전속 무용단의 공연에서 함께 추면 당신도 '춤추는 바보'.", bestSeason: "연중", stayTime: "약 1시간 30분", access: "도쿠시마역에서 도보 약 10분" },
    "ritsurin": { name: "리쓰린 공원", description: "'한 걸음마다 새 풍경'이라 불리는 다이묘 정원의 정점. 히라이호에서 내려다보는 엔게쓰교와 축산의 경치는 훌륭하다는 말뿐.", bestSeason: "연중", stayTime: "약 2시간", access: "리쓰린코엔키타구치역에서 도보 약 3분" },
    "naoshima": { name: "나오시마", description: "쿠사마 야요이의 호박과 안도 다다오 건축이 점재하는 현대 예술의 섬. 항구에서 자전거로 아트 순례.", bestSeason: "3〜11월", stayTime: "1일", access: "다카마쓰항에서 페리로 약 50분" },
    "matsuyama-castle": { name: "마쓰야마성", description: "현존 12천수 중 하나. 리프트로 오르는 혼마루 광장에서 마쓰야마 시가와 세토내해를 한눈에.", bestSeason: "연중", stayTime: "약 2시간", access: "오카이도 정류장에서 도보와 리프트로 약 15분" },
    "uchiko": { name: "우치코 옛거리", description: "목랍으로 번영한 상가의 흰 벽이 이어지는 요카이치 고코쿠 지구. 현역 극장 '우치코자'도 견학할 수 있다.", bestSeason: "연중", stayTime: "약 2시간", access: "우치코역에서 도보 약 10분" },
    "hirome-ichiba": { name: "고치 히로메 시장", description: "짚불에 구운 가다랑어 다타키를 낮부터 한잔과 함께. 60여 개 점포가 북적이는 고치의 사랑방.", bestSeason: "연중", stayTime: "약 2시간", access: "고치조마에 정류장에서 도보 약 2분" },
    "nikobuchi": { name: "니코부치", description: "'니요도 블루'의 대명사가 된 신비의 폭포 웅덩이. 맑은 날 정오 전후 수면이 가장 파랗게 빛난다.", bestSeason: "연중", stayTime: "약 1시간", access: "이노역에서 차로 약 40분" },
    "nakasu-yatai": { name: "후쿠오카 나카스 포장마차 거리", description: "강가에 포장마차가 이어지는 하카타 밤의 명물. 돈코쓰 라멘·야키라멘·교자를 순례하고 싶다.", bestSeason: "연중", stayTime: "약 2시간", access: "나카스카와바타역에서 도보 약 5분" },
    "dazaifu-tenmangu": { name: "다자이후 텐만구", description: "학문의 신 스가와라노 미치자네를 모시는 전국 텐만구의 총본궁. 참배길의 갓 구운 우메가에모치는 놓칠 수 없다.", bestSeason: "연중", stayTime: "약 2시간", access: "다자이후역에서 도보 약 5분" },
    "mifuneyama-rakuen": { name: "미후네야마 라쿠엔", description: "절벽을 차경으로 삼은 다케오의 대정원. 봄에는 20만 그루 철쭉, 여름에는 팀랩 빛의 아트로 환상적으로 물든다.", bestSeason: "4〜5월·7〜10월", stayTime: "약 2시간", access: "다케오온센역에서 차로 약 5분" },
    "yutoku-inari": { name: "유토쿠 이나리 신사", description: "'진제이 닛코'라 불리는 일본 3대 이나리 중 하나. 절벽에 걸쳐 지은 주홍 본전은 가케즈쿠리 건축의 걸작.", bestSeason: "연중", stayTime: "약 1시간 30분", access: "히젠카시마역에서 버스로 약 10분" },
    "inasayama": { name: "이나사야마 야경", description: "사발 모양 시가지에 불빛이 반짝이는 '세계 신 3대 야경'. 로프웨이로 5분, 정상 전망대에서 천만 불짜리 야경을.", bestSeason: "연중", stayTime: "약 2시간", access: "나가사키역에서 차+로프웨이로 약 20분" },
    "gunkanjima": { name: "군칸지마(하시마)", description: "바다에 떠 있는 폐허 탄광섬. 한때 세계 최고 인구밀도를 자랑한 세계유산에 상륙 투어로 건너갈 수 있다.", bestSeason: "4〜10월", stayTime: "반나절(투어)", access: "나가사키항에서 투어선으로 약 40분" },
    "aso-daikanbo": { name: "아소 다이칸보", description: "세계 유수의 칼데라와 초원이 펼쳐지는 웅대한 풍경. 다이칸보의 전망과 아소 아카우시 덮밥이 명물.", bestSeason: "4〜11월", stayTime: "약 1시간", access: "아소역에서 차로 약 30분" },
    "kurokawa-onsen": { name: "구로카와 온천", description: "산골짜기에 와풍 여관이 모여 있는 온천향. 석 장짜리 '입욕 패스'로 마음에 드는 숙소의 노천탕을 돌 수 있다.", bestSeason: "연중", stayTime: "반나절 또는 1박", access: "아소역에서 버스로 약 50분" },
    "yufuin-onsen": { name: "유후인 온천", description: "유후다케를 바라보는 인기 온천지. 유노쓰보 거리 먹거리 탐방과 아침 안개에 싸인 긴린호가 볼거리.", bestSeason: "연중", stayTime: "반나절 또는 1박", access: "유후인역에서 도보 약 15분(긴린호)" },
    "beppu-jigoku": { name: "벳푸 지옥 순례", description: "코발트블루의 바다 지옥과 새빨간 피의 연못 지옥 등 7개 원천을 도는 벳푸 명물. 용출량 일본 제일.", bestSeason: "연중", stayTime: "약 3시간", access: "벳푸역에서 버스로 약 15분" },
    "takachiho-gorge": { name: "다카치호 협곡", description: "주상절리 절벽에 마나이 폭포가 쏟아지는 신비로운 협곡. 보트로 폭포 바로 옆까지 갈 수 있다.", bestSeason: "연중", stayTime: "약 2시간", access: "노베오카역에서 차로 약 1시간" },
    "aoshima": { name: "아오시마", description: "'도깨비 빨래판'이라 불리는 물결 모양 바위에 둘러싸인 아열대 섬. 야자수와 아오시마 신사가 남국 무드 만점.", bestSeason: "연중", stayTime: "약 1시간 30분", access: "아오시마역에서 도보 약 10분" },
    "yakushima": { name: "야쿠시마", description: "수령 수천 년의 조몬스기와 이끼 낀 숲의 세계자연유산. 시라타니운스이쿄 트레킹이 인기.", bestSeason: "3〜11월", stayTime: "1일 이상", access: "가고시마항에서 고속선으로 약 2〜3시간" },
    "sakurajima": { name: "사쿠라지마", description: "지금도 연기를 뿜는 가고시마의 상징. 페리로 겨우 15분, 용암 해변 공원 족욕탕에서 박력 있는 산세를 올려다본다.", bestSeason: "연중", stayTime: "약 3시간", access: "가고시마항에서 페리로 약 15분" },
    "churaumi": { name: "오키나와 추라우미 수족관", description: "거대 수조 '구로시오의 바다'를 유유히 헤엄치는 고래상어는 압권. 주변 해양박공원과 에메랄드 비치도.", bestSeason: "연중", stayTime: "약 3시간", access: "나하공항에서 차로 약 2시간" },
    "kouri-island": { name: "고우리섬", description: "'사랑의 섬'으로 불리는 섬까지, 맑은 바다 위 고우리 대교로 일직선. 하트 록과 절경 카페가 인기.", bestSeason: "4〜10월", stayTime: "약 2시간", access: "나하공항에서 차로 약 1시간 30분" },
    "taketomi-island": { name: "다케토미섬", description: "붉은 기와 마을과 흰 모랫길이 남아 있는 야에야마의 섬. 물소 수레로 마을을 돌고 곤도이 비치의 얕은 바다로.", bestSeason: "연중", stayTime: "반나절", access: "이시가키항에서 페리로 약 15분" },
    "yanagawa": { name: "야나가와 뱃놀이", description: "돈코배로 조카마치의 수로를 유유히 내려간다. 명물 장어 세이로무시로 마무리하는 것이 야나가와 스타일.", bestSeason: "연중", stayTime: "반나절", access: "니시테쓰야나가와역에서 도보 약 8분" },
    "itoshima": { name: "이토시마 사쿠라이 후타미가우라", description: "하얀 도리이와 부부바위로 지는 석양이 명물. 해변 카페와 겨울 굴 오두막, 후쿠오카 시내에서의 당일 드라이브 정석.", bestSeason: "4〜10월", stayTime: "반나절", access: "지쿠젠마에바루역에서 차로 약 20분" },
    "yobuko": { name: "요부코 아침시장", description: "일본 3대 아침시장 중 하나. 명물 오징어 활어회는 투명한 몸통에, 다리는 나중에 튀김으로 즐길 수 있다.", bestSeason: "연중", stayTime: "약 2시간", access: "가라쓰역에서 버스로 약 30분" },
    "unzen-jigoku": { name: "운젠 지옥", description: "유황 증기가 피어오르는 지옥 순례와 일본 최초 국립공원으로 지정된 운젠 온천. 명물은 온천 달걀.", bestSeason: "연중", stayTime: "반나절", access: "이사하야역에서 버스로 약 1시간 20분" },
    "kujukushima": { name: "구주쿠시마", description: "사세보 앞바다에 208개 섬이 떠 있는 리아스 해안. 유람선 크루즈와 덴카이호에서 바라보는 석양이 유명.", bestSeason: "연중", stayTime: "반나절", access: "사세보역에서 버스로 약 25분" },
    "kumamoto-castle": { name: "구마모토성", description: "'무사 가에시' 석벽으로 이름난 천하의 명성. 지진 복구가 진행 중이며, 특별 견학 통로에서 옛 모습을 되찾는 과정을 볼 수 있다.", bestSeason: "연중", stayTime: "약 2시간", access: "구마모토역에서 노면전차로 약 15분" },
    "amakusa-sakitsu": { name: "아마쿠사 사키쓰 마을", description: "어촌 집들 사이로 성당 첨탑이 솟은 세계유산 잠복 크리스천 마을. 바다로 열린 기도의 마을을 천천히 걷는다.", bestSeason: "연중", stayTime: "약 2시간", access: "혼도 버스센터에서 차로 약 30분" },
    "kokonoe-yume-bridge": { name: "고코노에 '유메' 대현수교", description: "높이 173m, 보행자 전용으로는 일본 제일의 현수교. 발아래 신도 폭포와 규스이케이의 대수해가 펼쳐진다.", bestSeason: "10〜11월", stayTime: "약 1시간", access: "분고나카무라역에서 버스로 약 20분" },
    "usa-jingu": { name: "우사 신궁", description: "전국 4만 하치만 신사의 총본궁. 국보인 주홍 본전과 신대의 숲의 맑은 공기에 감싸인다.", bestSeason: "연중", stayTime: "약 2시간", access: "우사역에서 버스로 약 10분" },
    "udo-jingu": { name: "우도 신궁", description: "태평양을 마주한 절벽 동굴에 본전이 자리한다. '운다마'를 거북바위 홈에 던져 넣어 인연을 기원.", bestSeason: "연중", stayTime: "약 1시간 30분", access: "미야자키역에서 버스로 약 1시간 30분" },
    "ebino-kogen": { name: "에비노 고원", description: "기리시마 연산에 안긴 해발 1,200m의 고원. 가라쿠니다케 등산과 연못 순례 코스, 가을엔 억새 들판이 황금빛으로.", bestSeason: "5〜11월", stayTime: "반나절", access: "고바야시역에서 차로 약 30분" },
    "kirishima-jingu": { name: "기리시마 신궁", description: "천손강림의 땅에 세워진 주홍 신사. 수령 800년의 신목과 이끼 낀 참배길이 신화의 세계로 이끈다.", bestSeason: "연중", stayTime: "약 1시간 30분", access: "기리시마진구역에서 버스로 약 10분" },
    "ibusuki-onsen": { name: "이부스키 온천", description: "물가에서 즐기는 세계적으로도 드문 천연 모래찜질 온천. 유카타 차림으로 모래에 묻히면 10분 만에 땀이 솟는다.", bestSeason: "연중", stayTime: "반나절", access: "이부스키역에서 도보 약 20분" },
    "amami-oshima": { name: "아마미오시마", description: "긴사쿠바루의 아열대 원시림과 투명도 발군의 도모리 해안. 아마미검은토끼가 사는 세계자연유산의 섬.", bestSeason: "4〜10월", stayTime: "1일 이상", access: "아마미공항에서 차로 각지로" },
    "shurijo": { name: "슈리성", description: "류큐 왕국의 영화를 전하는 왕성. 2019년 화재 이후 정전 복원이 진행 중이며 '보여주는 복원' 현장을 견학할 수 있다.", bestSeason: "연중", stayTime: "약 2시간", access: "모노레일 슈리역에서 도보 약 15분" },
    "kokusai-dori": { name: "고쿠사이도리", description: "나하의 메인 스트리트 약 1.6km. 스테이크에 블루씰 아이스크림, 골목 시장 안쪽에는 마키시 공설시장.", bestSeason: "연중", stayTime: "약 3시간", access: "모노레일 겐초마에역에서 도보 약 3분" },
    "manzamo": { name: "만자모", description: "'만 명이 앉을 수 있는 초원'이라 칭송받은 코끼리 코 모양의 절벽. 동중국해로 지는 석양의 명소.", bestSeason: "연중", stayTime: "약 1시간", access: "나하공항에서 차로 약 1시간" },
    "kabira-bay": { name: "이시가키섬 가비라만", description: "흰 모래에 에메랄드 그라데이션이 펼쳐지는 미슐랭 3스타의 만. 글라스보트로 산호초를 들여다본다.", bestSeason: "연중", stayTime: "약 2시간", access: "이시가키항에서 차로 약 30분" },
  },
  courses: {
    "kanazawa-hida-2n3d": {
      title: "가나자와·시라카와고·히다 다카야마 2박 3일",
      summary: "호쿠리쿠 신칸센으로 가나자와에 들어가 세계유산 합장촌을 거쳐 히다의 조카마치로. 가가 백만석 문화와 산골 원풍경을 한 번에 맛보는 정석 루트.",
      notes: [
        ["오전엔 겐로쿠엔과 히가시차야 거리, 점심은 오미초 시장에서 해산물", "저녁엔 렌터카로 해변 드라이브, 가나자와 숙박"],
        ["오전 중에 전망대로. 마을을 천천히 산책", "돌아가는 길에 들르기. 고요한 합장촌을 독차지, 다카야마 숙박"],
        ["미야가와 아침시장에서 옛거리로. 히다규 초밥으로 마무리"],
      ],
    },
    "kyoto-nara-2n3d": {
      title: "교토·나라 정석 순례 2박 3일",
      summary: "센본도리이에 금각, 아라시야마 대나무숲, 그리고 나라의 대불과 사슴. 첫 간사이 여행이라면 우선 이 코스. 어느 계절에도 실패가 없다.",
      notes: [
        ["아침 일찍 센본도리이로(혼잡 회피)"],
        ["개문 직후의 고요한 금각을", "오후엔 도게쓰교와 대나무숲, 강가 카페에서 한숨 돌리기"],
        ["긴테쓰로 나라로. 대불전과 사슴 센베이 체험"],
      ],
    },
    "hokkaido-2n3d": {
      title: "삿포로·오타루·노보리베쓰 2박 3일",
      summary: "해산물과 레트로 항구 도시, 그리고 지옥계곡의 명탕. 첫 홋카이도를 응축한 정석 코스. 겨울엔 설경, 여름엔 상쾌한 기후가 기다린다.",
      notes: [
        ["도착하면 우선 해산물덮밥. 오후엔 오도리 공원 산책, 삿포로 숙박"],
        ["JR로 오타루로. 유리 공방과 스시, 해질녘 운하까지"],
        ["지옥계곡을 산책한 뒤 명탕으로 마무리"],
      ],
    },
    "setouchi-2n3d": {
      title: "히로시마·시마나미·도고 2박 3일",
      summary: "미야지마 대도리이에서 오노미치 언덕길, 섬들을 건너는 사이클링, 그리고 일본 최고(最古)급의 탕으로. 세토우치의 빛과 다도해를 만끽하는 3일.",
      notes: [
        ["평화기념공원에서 기도를", "오후엔 미야지마로 건너가 썰물·밀물 두 모습의 대도리이를. 히로시마 숙박"],
        ["센코지에서의 전망과 오노미치 라멘", "렌터사이클로 섬으로. 기로산 석양은 필견, 이마바리 숙박"],
        ["마쓰야마로 이동해 본관 온천과 상점가 산책"],
      ],
    },
    "kyushu-onsen-2n3d": {
      title: "규슈 온천과 대자연 2박 3일",
      summary: "벳푸의 지옥, 유후인의 아침 안개, 구로카와의 노천탕, 아소의 대초원, 다카치호의 신화 협곡. 규슈 '탕과 불의 나라'를 종단하는 농밀한 루트.",
      notes: [
        ["바다 지옥과 피의 연못 지옥을 중심으로", "저녁엔 유노쓰보 거리와 긴린호, 유후인 숙박"],
        ["입욕 패스로 노천탕 순례", "칼데라를 한눈에 담고 아카우시 덮밥, 아소 숙박"],
        ["보트로 마나이 폭포로"],
      ],
    },
    "tohoku-2n3d": {
      title: "미치노쿠 정취 2박 3일",
      summary: "일본 3경 마쓰시마, 야마데라의 돌계단, 다이쇼 로망의 긴잔 온천, 무가 저택의 가쿠노다테. 신칸센으로 도는 차분하고 아름다운 도호쿠 여행.",
      notes: [
        ["유람선과 굴 런치, 센다이 숙박"],
        ["오전 중에 1,015계단에 도전", "해질녘 가스등 온천 거리로, 긴잔 온천 숙박"],
        ["신칸센으로 가쿠노다테로. 무가 저택 거리를 기모노 산책"],
      ],
    },
    "fuji-hakone-1n2d": {
      title: "후지산 한 바퀴 1박 2일",
      summary: "가와구치호의 거꾸로 후지, 오시노의 용천수, 아시노코의 해적선, 아타미의 탕. 주말에 훌쩍 떠나 후지산을 사방에서 감상하는 소여행.",
      notes: [
        ["오이시 공원에서 후지와 호수의 파노라마", "용천수 마을 산책, 가와구치코 온천 숙박"],
        ["해적선과 하코네 신사의 호수 위 도리이", "마무리는 아타미에서 온천과 먹거리 탐방"],
      ],
    },
    "okinawa-3n4d": {
      title: "오키나와 본섬과 야에야마 3박 4일",
      summary: "고래상어를 만나고, 고우리 블루의 바다를 건너, 비행기로 야에야마로. 붉은 기와 마을과 얕은 바다에서 아무것도 하지 않는 사치를 맛보는 섬 여행.",
      notes: [
        ["오후 먹이 주는 시간을 노려서, 모토부 숙박"],
        ["고우리 대교를 건너 절경 카페로. 저녁 비행기로 이시가키로"],
        ["물소 수레와 곤도이 비치의 섬 시간, 이시가키 숙박"],
        ["아침의 고요한 마을을 한 번 더 산책하고 귀로에"],
      ],
    },
    "sanin-2n3d": {
      title: "산인 이즈모·마쓰에·돗토리 2박 3일",
      summary: "인연의 이즈모 대사에서 국보 마쓰에성, 미인탕 다마쓰쿠리와 라돈의 미사사 온천을 순례하고 마지막은 돗토리 사구로. 신화와 명탕의 산인 길.",
      notes: [
        ["두 번 절, 네 번 박수, 한 번 절로 인연 기원. 문전에서 소바를", "미인탕과 강변 족욕 순례, 다마쓰쿠리 숙박"],
        ["국보 천수와 해자 유람선", "액자 같은 일본 정원을 천천히 감상", "레트로 온천 거리로 이동해 미사사 숙박"],
        ["아침 사구의 바람 무늬가 가장 아름답다"],
      ],
    },
    "hokuriku-2n3d": {
      title: "호쿠리쿠 한 바퀴 가나자와·노토·후쿠이 2박 3일",
      summary: "오미초 시장 해산물과 히가시차야 거리, 모래사장을 달리는 지리하마, 바다의 온천 와쿠라. 마무리는 에이헤이지의 고요와 도진보의 절벽. 호쿠리쿠 명소를 한붓그리기로 돈다.",
      notes: [
        ["점심은 시장에서 해산물덮밥", "오후엔 찻집 거리를 기모노 산책, 가나자와 숙박"],
        ["렌터카로 파도 옆을 드라이브", "나나오만을 바라보는 바다의 온천에서 와쿠라 숙박"],
        ["삼나무숲 속 칠당가람에서 좌선 체험도", "석양의 절벽에서 여행을 마무리"],
      ],
    },
    "shikoku-3n4d": {
      title: "시코쿠 한 바퀴 일주 3박 4일",
      summary: "곤피라 참배에 나루토 소용돌이, 이야의 비경, 도고의 탕. 우동도 가다랑어도 아와오도리도, 시코쿠의 알짜만 골라 한 바퀴.",
      notes: [
        ["다카마쓰에 도착해 우선 명원 산책. 점심은 사누키 우동", "785계단을 올라 곤피라 참배, 고토히라 숙박"],
        ["물때표로 사리 시간을 확인하고 소용돌이의 길로", "밤 공연에서 함께 춤추기, 도쿠시마 숙박"],
        ["유람선으로 계곡미를 만끽", "스릴 만점 가즈라바시를 건너 이야 숙박"],
        ["마쓰야마로 이동해 리프트로 혼마루로", "여행의 마무리는 3,000년의 명탕"],
      ],
    },
    "furano-biei-1n2d": {
      title: "아사히카와·비에이·후라노 1박 2일",
      summary: "행동 전시의 아사히야마 동물원에서 푸른 연못과 라벤더밭으로. 여름 홋카이도의 하이라이트를 응축한 주말 여행. 렌터카 추천.",
      notes: [
        ["오전 중에 인기 먹이 시간을", "오후의 빛에 연못이 더욱 파랗다, 비에이 숙박"],
        ["아침 일찍 라벤더밭, 마지막은 멜론으로"],
      ],
    },
    "minami-kyushu-2n3d": {
      title: "미나미규슈 사쿠라지마·이부스키·기리시마·니치난 2박 3일",
      summary: "연기를 뿜는 사쿠라지마, 모래에 파묻히는 이부스키, 신화의 기리시마 신궁에서 니치난 해안의 우도 신궁으로. 화산과 신화와 온천, 규슈 남단을 도는 여행.",
      notes: [
        ["페리로 건너 유노히라 전망소로", "저녁 모래찜질로 땀을 빼고 이부스키 숙박"],
        ["주홍 사전과 삼나무길 산림욕", "연못 순례 산책로를 걷고 기리시마 숙박"],
        ["동굴 본전과 운다마 던지기", "도깨비 빨래판을 보며 니치난 해안 드라이브"],
      ],
    },
  },
};
