// 简体中文の翻訳辞書。キーが無い項目は日本語(原本)にフォールバックする。
const LANG_ZH = {
  ui: {
    docTitle: "Tabisome — 日本国内旅行推荐景点",
    eyebrow: "重新发现日本。",
    heroLead: "从全部47个都道府县精选的{spots}个景点,以及{courses}条示范行程。看到心动的地方就点 ⭐ 加入心愿清单,去过之后盖上纪念印章吧。",
    unitSpots: "{n}",
    unitCourses: "{n}",
    tabSpots: "探索景点",
    tabCourses: "示范行程",
    searchPlaceholder: "按名称或关键词搜索",
    prefAll: "都道府县:全部",
    allLabel: "全部",
    wishlistToggle: "⭐ 心愿清单({n})",
    sortAdded: "按添加顺序",
    sortRegion: "按地区",
    exportBtn: "导出",
    importBtn: "导入",
    resultCount: "{n}个 / 共{total}个",
    emptyMsg: "没有符合条件的景点",
    clearFilters: "清除条件,显示全部",
    seasonalHeading: "当季推荐",
    months: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
    bestSeasonLabel: "最佳季节",
    stayTimeLabel: "游览时长",
    accessLabel: "交通方式",
    mapLink: "查看地图 →",
    hotelSearch: "🏨 查找附近酒店",
    shareLabel: "分享:",
    copyUrl: "复制链接",
    copied: "✓ 已复制",
    visitedOnlyBtn: "仅看已到访",
    stampbookTitle: "朱印帐 — 已到访 {n} 处・{m}/47 个都道府县",
    feeLabel: "门票(参考)",
    feeFree: "免费",
    feeAbout: "约 ¥{n}",
    feeRange: "¥{a}〜{b}",
    feeDisclaimer: "※ 价格仅供参考,可能会有变动。",
    budgetLabel: "💴 当地费用参考(每人): {range}",
    budgetNote: "含住宿、餐饮和门票,不含交通费。",
    starAdd: "☆ 加入心愿清单",
    starAdded: "⭐ 已在心愿清单",
    visitedYes: "✓ 已去过",
    visitedNo: "○ 还没去过",
    memoLabel: "我的笔记",
    memoPlaceholder: "想确认的事、想吃的美食、想住的旅馆……",
    nearbyHeading: "顺路一起玩",
    inCoursesHeading: "包含此景点的行程",
    daysUnit: "{n}天",
    dayLabel: "第{n}天",
    backToCourses: "← 返回行程列表",
    confirmRemove: "笔记也会一并删除。确定从心愿清单移除吗?",
    importError: "无法读取文件。请选择从本站导出的JSON文件。",
    importNone: "未找到有效的景点。",
    importDone: "已导入{n}个景点。",
    exportFilename: "Tabisome-心愿清单.json",
    photoCredit: "照片: {a} ({l}) / {s}",
    feedbackLink: "📝 意见反馈",
    footerText: "从全部47个都道府县精选{n}个景点与示范行程的旅行指南。照片来自 Wikimedia Commons,每张照片均标注了出处。本站使用 Google Analytics 统计访问情况。",
    ariaClose: "关闭",
    ariaStar: "将{name}加入或移出心愿清单",
    ariaCardOpen: "查看{name}的详情",
    ariaDotShow: "显示{name}的照片",
    ariaCaption: "打开当前照片对应的景点",
  },
  regions: {
    "北海道": "北海道", "東北": "东北", "関東": "关东", "中部": "中部",
    "近畿": "近畿", "中国": "中国地区", "四国": "四国", "九州・沖縄": "九州·冲绳",
  },
  prefectures: {
    "北海道": "北海道", "青森県": "青森县", "岩手県": "岩手县", "宮城県": "宫城县", "秋田県": "秋田县",
    "山形県": "山形县", "福島県": "福岛县", "茨城県": "茨城县", "栃木県": "枥木县", "群馬県": "群马县",
    "埼玉県": "埼玉县", "千葉県": "千叶县", "東京都": "东京都", "神奈川県": "神奈川县", "新潟県": "新潟县",
    "富山県": "富山县", "石川県": "石川县", "福井県": "福井县", "山梨県": "山梨县", "長野県": "长野县",
    "岐阜県": "岐阜县", "静岡県": "静冈县", "愛知県": "爱知县", "三重県": "三重县", "滋賀県": "滋贺县",
    "京都府": "京都府", "大阪府": "大阪府", "兵庫県": "兵库县", "奈良県": "奈良县", "和歌山県": "和歌山县",
    "鳥取県": "鸟取县", "島根県": "岛根县", "岡山県": "冈山县", "広島県": "广岛县", "山口県": "山口县",
    "徳島県": "德岛县", "香川県": "香川县", "愛媛県": "爱媛县", "高知県": "高知县", "福岡県": "福冈县",
    "佐賀県": "佐贺县", "長崎県": "长崎县", "熊本県": "熊本县", "大分県": "大分县", "宮崎県": "宫崎县",
    "鹿児島県": "鹿儿岛县", "沖縄県": "冲绳县",
  },
  categories: {
    "絶景": "绝景", "温泉": "温泉", "グルメ": "美食", "歴史": "历史", "自然": "自然", "街歩き": "漫步街区",
  },
  spots: {
    "biei-blue-pond": { name: "美瑛·青池", description: "拼布般的丘陵风光中,一泓神秘的钴蓝色池水。夏天还能欣赏薰衣草。", bestSeason: "6〜8月", stayTime: "约1小时", access: "从旭川机场驾车约40分钟" },
    "hakodateyama": { name: "函馆山", description: "被誉为“世界三大夜景”之一的扇形夜景。缆车约3分钟直达山顶,山脚的元町街区也值得漫步。", bestSeason: "全年", stayTime: "约2小时", access: "从函馆站乘市电+缆车约30分钟" },
    "otaru-canal": { name: "小樽运河", description: "石造仓库林立的复古运河街区,煤气灯点亮的黄昏尤为动人。寿司和海鲜盖饭名店众多。", bestSeason: "全年", stayTime: "约3小时", access: "从札幌站乘JR约35分钟" },
    "shiretoko": { name: "知床", description: "世界自然遗产。漫步知床五湖,或乘观光船观赏棕熊与鲸鱼,尽享原始自然。", bestSeason: "6〜9月", stayTime: "半天〜1天", access: "从女满别机场驾车约2小时" },
    "noboribetsu-onsen": { name: "登别温泉", description: "涌泉量居北海道之首的温泉胜地。源泉喷涌的“地狱谷”景观粗犷而震撼。", bestSeason: "全年", stayTime: "半天或住一晚", access: "从新千岁机场驾车约1小时" },
    "sapporo-nijo-market": { name: "札幌·二条市场", description: "自明治时代延续至今的札幌厨房,清晨就能吃到新鲜海鲜盖饭。步行可至大通公园和薄野。", bestSeason: "全年", stayTime: "约1小时", access: "从札幌站步行约15分钟" },
    "asahiyama-zoo": { name: "旭山动物园", description: "以企鹅散步、海豹圆柱水槽等“行为展示”闻名的动物园。雪中的动物们也是冬季一大看点。", bestSeason: "全年", stayTime: "半天", access: "从旭川站乘巴士约40分钟" },
    "furano-farm-tomita": { name: "富良野·富田农场", description: "把山丘染成紫色的薰衣草田代名词。7月盛花期还有蜜瓜和花田甜点。", bestSeason: "6〜8月", stayTime: "约2小时", access: "从旭川机场驾车约45分钟" },
    "toyako": { name: "洞爷湖", description: "湖畔温泉街环绕的破火山口湖。4月下旬至10月每晚举行长期花火大会。", bestSeason: "4〜10月", stayTime: "半天", access: "从札幌驾车约2小时" },
    "akanko": { name: "阿寒湖", description: "特别天然纪念物“毬藻”栖息之湖。湖畔有阿伊努村落和温泉街,冬季还能看到湖面霜花。", bestSeason: "全年", stayTime: "半天", access: "从钏路机场驾车约1小时10分钟" },
    "hakodate-asaichi": { name: "函馆早市", description: "站前约250家店铺鳞次栉比的早市。钓鱿鱼体验和海鲜盖饭开启函馆的早晨。", bestSeason: "全年", stayTime: "约1.5小时", access: "从函馆站步行1分钟" },
    "cape-kamui": { name: "神威岬", description: "从积丹半岛尖端眺望“积丹蓝”大海的海岬。通往尖端的步道“恰伦卡小径”令人心旷神怡。", bestSeason: "6〜8月", stayTime: "约1.5小时", access: "从小樽驾车约1.5小时" },
    "oirase-gorge": { name: "奥入濑溪流", description: "从十和田湖流出的约14公里溪流,步道沿途瀑布与青苔岩石相连,是新绿和红叶名所。", bestSeason: "5〜6月·10月", stayTime: "约3小时", access: "从青森站驾车约1.5小时" },
    "hirosaki-castle": { name: "弘前城·弘前公园", description: "现存12座天守之一。春天约2600株樱花铺满护城河的弘前樱花祭,是日本屈指可数的樱花胜景。", bestSeason: "4月下旬〜5月上旬", stayTime: "约2小时", access: "从弘前站乘巴士约15分钟" },
    "chusonji": { name: "中尊寺金色堂", description: "平泉世界遗产。奥州藤原氏建造的金箔佛堂令人叹为观止。", bestSeason: "全年", stayTime: "约2小时", access: "从平泉站步行约20分钟" },
    "jodogahama": { name: "净土滨", description: "白色流纹岩、青松与清澈海水交织的三陆代表性胜景。巡游蓝色洞窟的小船也很受欢迎。", bestSeason: "6〜9月", stayTime: "约2小时", access: "从宫古站驾车约10分钟" },
    "matsushima": { name: "松岛", description: "日本三景之一。可乘游览船巡游漂浮着260余座小岛的海湾。牡蛎和竹叶鱼板也是名产。", bestSeason: "全年", stayTime: "约3小时", access: "从仙台站乘JR约40分钟" },
    "zao-okama": { name: "藏王·御釜", description: "翡翠绿的火口湖,湖面随天气变换颜色。驾车驶过藏王回音线前往这一神秘景观。", bestSeason: "5〜10月", stayTime: "约1小时", access: "从仙台驾车约1.5小时" },
    "kakunodate": { name: "角馆", description: "被称为“陆奥小京都”的武家宅邸街区。春天垂枝樱花隧道美不胜收。", bestSeason: "4月下旬〜5月上旬", stayTime: "约2小时", access: "从角馆站步行约15分钟" },
    "nyuto-onsen": { name: "乳头温泉乡", description: "七家汤宿散落在山毛榉林中的秘汤之乡。乳白色露天温泉和凭“巡汤帖”泡遍各家是一大特色。", bestSeason: "全年", stayTime: "半天或住一晚", access: "从田泽湖站乘巴士约50分钟" },
    "ginzan-onsen": { name: "银山温泉", description: "大正浪漫风格的木造旅馆沿河而立的温泉街。煤气灯与雪景的组合是冬日风物诗。", bestSeason: "12〜2月", stayTime: "半天或住一晚", access: "从大石田站乘巴士约40分钟" },
    "yamadera": { name: "山寺(立石寺)", description: "堂宇依断崖而建的天台宗古刹。登上1015级石阶,五大堂的眺望让人忘却疲惫。", bestSeason: "5〜11月", stayTime: "约2小时", access: "从山形站乘JR约20分钟后步行" },
    "ouchi-juku": { name: "大内宿", description: "江户时代驿站小镇的茅草屋顶保存至今。用大葱代替筷子吃的“大葱荞麦面”是名物。", bestSeason: "全年", stayTime: "约2小时", access: "从汤野上温泉站驾车约10分钟" },
    "goshiki-numa": { name: "五色沼", description: "磐梯山喷发形成的大小湖沼群。沿探胜路巡游闪耀着钴蓝与翡翠绿的沼泽。", bestSeason: "5〜11月", stayTime: "约2小时", access: "从猪苗代站乘巴士约30分钟" },
    "towadako": { name: "十和田湖", description: "十和田八幡平国立公园核心的破火山口湖,也是奥入濑溪流的源头。游览船和湖畔“少女之像”是经典。", bestSeason: "5〜10月", stayTime: "约2小时", access: "从八户站乘巴士约2小时15分钟" },
    "hachinohe-yokocho": { name: "八户·弥勒横丁", description: "26家小摊连成的横丁。与店主和当地人并肩而坐,品尝仙贝汤和八户鲭鱼等南部风味。", bestSeason: "全年", stayTime: "约2小时", access: "从本八户站步行约10分钟" },
    "ryusendo": { name: "龙泉洞", description: "日本三大钟乳洞之一。被称为“龙蓝”的地底湖透明度世界屈指可数,神秘莫测。", bestSeason: "全年", stayTime: "约1小时", access: "从盛冈站乘巴士约2小时10分钟" },
    "genbikei": { name: "严美溪", description: "发源于栗驹山的磐井川侵蚀出的溪谷美景。从对岸沿绳索飞来的“飞天团子”是名物。", bestSeason: "4〜11月", stayTime: "约1小时", access: "从一之关站乘巴士约20分钟" },
    "akiu-onsen": { name: "秋保温泉", description: "被称为“仙台后花园”的古汤。附近还有落差55米的秋保大瀑布和奇岩连绵的磊磊峡步道。", bestSeason: "全年", stayTime: "半天", access: "从仙台站乘巴士约50分钟" },
    "naruko-onsen": { name: "鸣子温泉乡", description: "木芥子人偶与木屐声相伴的汤治之乡。约370处源泉,据说囊括了日本约七成的泉质。", bestSeason: "10〜11月", stayTime: "半天", access: "鸣子温泉站步行即到" },
    "tazawako": { name: "田泽湖", description: "日本最深(423米)的琉璃色湖泊。湖畔金色的辰子像是绝佳拍照点。", bestSeason: "5〜10月", stayTime: "约2小时", access: "从田泽湖站乘巴士约12分钟" },
    "oga-nyudozaki": { name: "男鹿半岛·入道崎", description: "绿色大地、蔚蓝大海与黑白条纹灯塔相映成趣的海岬。也以“生剥鬼”之乡闻名。", bestSeason: "6〜9月", stayTime: "约1.5小时", access: "从男鹿站驾车约30分钟" },
    "zao-onsen": { name: "藏王温泉", description: "相传开汤1900年的强酸性温泉。冬季从缆车俯瞰世界罕见的树冰森林。", bestSeason: "12〜2月", stayTime: "半天", access: "从山形站乘巴士约40分钟" },
    "sankyo-soko": { name: "酒田·山居仓库", description: "建于1893年的12栋米仓,是这座港町的象征。榉树林荫道与黑墙景观曾作为电影外景地。", bestSeason: "全年", stayTime: "约1小时", access: "从酒田站驾车约5分钟" },
    "tsuruga-castle": { name: "会津若松·鹤城", description: "在戊辰战争中经受了一个月笼城战的名城。日本唯一的红瓦天守映衬着天空。", bestSeason: "4〜11月", stayTime: "约1.5小时", access: "从会津若松站乘巴士约15分钟" },
    "kitakata": { name: "喜多方", description: "保留着4000多栋仓房的“藏之城”。也是清晨吃拉面的“早拉”文化圣地。", bestSeason: "全年", stayTime: "约2小时", access: "从喜多方站步行约15分钟" },
    "hitachi-seaside-park": { name: "国营日立海滨公园", description: "春天粉蝶花把山丘染成一片蔚蓝,秋天扫帚草红成一片。四季花田令人震撼。", bestSeason: "4〜5月·10月", stayTime: "约3小时", access: "从胜田站乘巴士约20分钟" },
    "fukuroda-falls": { name: "袋田瀑布", description: "分四段落下的日本三名瀑之一。冬季整条瀑布结冰成“冰瀑”,秋季与红叶交相辉映。", bestSeason: "11月·1〜2月", stayTime: "约1小时", access: "从袋田站驾车约10分钟" },
    "nikko-toshogu": { name: "日光东照宫", description: "祭祀德川家康的华丽世界遗产。阳明门、沉睡猫等看点众多,建议与华严瀑布、中禅寺湖一同游览。", bestSeason: "全年", stayTime: "约2小时", access: "从东武日光站乘巴士约10分钟" },
    "ashikaga-flower-park": { name: "足利花卉公园", description: "树龄逾160年的大紫藤架梦幻迷人。冬季的关东三大灯饰之一也值得一看。", bestSeason: "4月中旬〜5月中旬", stayTime: "约2小时", access: "足利花卉公园站即到" },
    "kusatsu-onsen": { name: "草津温泉", description: "自然涌出量日本第一。以汤畑为中心的温泉街风情浓郁,还能观赏名物“汤揉”表演。", bestSeason: "全年", stayTime: "半天或住一晚", access: "从长野原草津口站乘巴士约25分钟" },
    "ikaho-onsen": { name: "伊香保温泉", description: "365级石阶两旁旅馆与射击游戏店林立的怀旧温泉街。茶褐色的“黄金之汤”是名物。", bestSeason: "全年", stayTime: "半天或住一晚", access: "从涩川站乘巴士约25分钟" },
    "kawagoe": { name: "川越", description: "被称为“小江户”的土藏造老街。钟楼“时之钟”和点心横丁等,边走边吃乐趣无穷。", bestSeason: "全年", stayTime: "约3小时", access: "从川越站步行约20分钟" },
    "nagatoro": { name: "长瀞", description: "乘和舟穿行岩畳之间的溪流泛舟是名物。刨冰名店和宝登山的眺望也很有趣。", bestSeason: "4〜11月", stayTime: "约3小时", access: "从长瀞站步行约5分钟" },
    "naritasan": { name: "成田山新胜寺", description: "拥有千余年历史的不动尊信仰中心。参道上的老字号鳗鱼店边逛边吃也是乐趣。", bestSeason: "全年", stayTime: "约2小时", access: "从成田站步行约10分钟" },
    "yoro-valley": { name: "养老溪谷", description: "房总第一的溪谷美。漫步粟又瀑布步道,泡黑汤温泉,是离东京不远的疗愈之乡。", bestSeason: "11月下旬〜12月上旬", stayTime: "约3小时", access: "从养老溪谷站驾车约10分钟" },
    "asakusa-sensoji": { name: "浅草·浅草寺", description: "以雷门和仲见世街闻名的东京最古老寺院。下町美食边走边吃和人力车都很受欢迎。", bestSeason: "全年", stayTime: "约2小时", access: "浅草站即到" },
    "meiji-jingu": { name: "明治神宫", description: "被深邃森林环抱的神域,难以想象身处市中心。穿过原宿站旁的大鸟居,静谧参道绵延。", bestSeason: "全年", stayTime: "约1.5小时", access: "原宿站即到" },
    "tsukiji-market": { name: "筑地场外市场", description: "约400家店铺云集的美食乐园。海鲜盖饭和玉子烧要趁早上去吃才对。", bestSeason: "全年", stayTime: "约2小时", access: "筑地站即到" },
    "kamakura": { name: "镰仓", description: "鹤冈八幡宫、大佛、小町通的边走边吃,再乘江之电沿海而行,可以玩上一整天的古都。", bestSeason: "全年", stayTime: "半天〜1天", access: "从镰仓站步行约10分钟" },
    "hakone-ashinoko": { name: "箱根·芦之湖", description: "隔着海盗船点缀的湖面遥望富士山的经典度假地。大涌谷黑鸡蛋和名汤巡游也不可错过。", bestSeason: "全年", stayTime: "半天或住一晚", access: "从箱根汤本站乘巴士约35分钟" },
    "kairakuen": { name: "偕乐园", description: "日本三名园之一。2〜3月梅花祭期间,约100种3000株梅花竞相绽放。", bestSeason: "2〜3月", stayTime: "约1.5小时", access: "从水户站乘巴士约20分钟" },
    "kegon-falls": { name: "华严瀑布", description: "中禅寺湖水一泻97米的日本三名瀑之一。乘电梯可下到瀑潭附近的观瀑台。", bestSeason: "10〜11月", stayTime: "约1小时", access: "从东武日光站乘巴士约45分钟" },
    "utsunomiya-gyoza": { name: "宇都宫饺子街", description: "专门店超过200家的“饺子之城”。煎饺、炸饺、水饺,一家家吃过去比较才有趣。", bestSeason: "全年", stayTime: "约2小时", access: "宇都宫站步行范围内" },
    "tomioka-silk-mill": { name: "富冈制丝厂", description: "1872年开业的官营制丝厂,世界遗产。缫丝所和蚕茧仓库几乎完整保存。", bestSeason: "全年", stayTime: "约1.5小时", access: "从上州富冈站步行约15分钟" },
    "shima-onsen": { name: "四万温泉", description: "相传能治愈“四万种疾病”的名汤。清澈碧蓝的四万川与奥四万湖的“四万蓝”也是看点。", bestSeason: "全年", stayTime: "半天", access: "从中之条站乘巴士约40分钟" },
    "chichibu-hitsujiyama": { name: "秩父·羊山公园", description: "以武甲山为背景,约40万株芝樱铺满山丘。4月中旬至5月上旬盛花期还有热闹的露天摊位。", bestSeason: "4〜5月", stayTime: "约1.5小时", access: "从西武秩父站步行约20分钟" },
    "nokogiriyama": { name: "锯山·日本寺", description: "探出断崖的“地狱窥视”和日本最大的摩崖大佛。乘索道登顶。", bestSeason: "全年", stayTime: "半天", access: "从滨金谷站步行+索道约20分钟" },
    "shibuya-crossing": { name: "涩谷十字路口", description: "一次绿灯最多3000人穿行的世界级景点。从观景设施俯瞰的夜间路口也很受欢迎。", bestSeason: "全年", stayTime: "约1小时", access: "涩谷站步行即到" },
    "ameyoko": { name: "上野·阿美横丁", description: "高架桥下约400家店铺鳞次栉比的商店街。边走边吃和此起彼伏的吆喝声,是充满活力的下町厨房。", bestSeason: "全年", stayTime: "约2小时", access: "上野站步行即到" },
    "takaosan": { name: "高尾山", description: "距市中心电车约1小时的米其林三星之山。缆车、名物天狗烧,晴天还能从山顶望见富士山。", bestSeason: "11月", stayTime: "半天", access: "高尾山口站步行即到" },
    "yokohama-chukagai": { name: "横滨中华街", description: "约600家店铺云集的日本最大中华街。从街头小吃到老字号名店,胃有几个都不够用。", bestSeason: "全年", stayTime: "约3小时", access: "元町·中华街站步行即到" },
    "enoshima": { name: "江之岛", description: "参道美食和海烛台展望塔上的相模湾景色。晴天还能望见富士山,是湘南的象征。", bestSeason: "全年", stayTime: "半天", access: "从片濑江之岛站步行约15分钟" },
    "kiyotsu-gorge": { name: "清津峡", description: "日本三大峡谷之一。隧道尽头的“全景站”水镜倒映峡谷,是必看的艺术空间。", bestSeason: "4〜11月", stayTime: "约1.5小时", access: "从越后汤泽站驾车约25分钟" },
    "sado-island": { name: "佐渡岛", description: "以盆舟和世界遗产金山闻名的日本海最大岛屿。尖阁湾等未经雕琢的海岸美景绵延不绝。", bestSeason: "5〜10月", stayTime: "1天以上", access: "从新潟港乘渡轮约2.5小时" },
    "tateyama-kurobe": { name: "立山黑部阿尔卑斯路线", description: "乘交通工具翻越3000米级群山的山岳观光路线。春天的“雪之大谷”和黑部水坝泄洪闻名遐迩。", bestSeason: "4〜11月", stayTime: "1天", access: "从立山站或扇泽换乘缆车等" },
    "ainokura": { name: "五箇山·相仓合掌造聚落", description: "与白川乡一同登录世界遗产的山间合掌聚落。未被过度开发的宁静是其魅力。", bestSeason: "全年", stayTime: "约1.5小时", access: "从城端站驾车约25分钟" },
    "kenrokuen": { name: "金泽·兼六园", description: "日本三名园之一。建议与东茶屋街漫步和近江町市场的海鲜一同享受。", bestSeason: "全年", stayTime: "约2小时", access: "从金泽站乘巴士约15分钟" },
    "chirihama": { name: "千里滨渚车道", description: "日本唯一可以开车驰骋浪边的约8公里沙滩。夕阳时分的兜风宛如电影场景。", bestSeason: "4〜11月", stayTime: "约1小时", access: "从金泽站驾车约45分钟" },
    "tojinbo": { name: "东寻坊", description: "日本海怒涛雕琢出的柱状节理断崖绝壁。从游览船仰望岩壁和夕阳的景色气势磅礴。", bestSeason: "全年", stayTime: "约1.5小时", access: "从芦原温泉站乘巴士约40分钟" },
    "eiheiji": { name: "永平寺", description: "道元禅师开创的曹洞宗大本山。沿回廊巡游老杉环抱的七堂伽蓝,心境归于平静。", bestSeason: "全年", stayTime: "约2小时", access: "从福井站乘巴士约30分钟" },
    "kawaguchiko": { name: "河口湖", description: "富士山绝景观赏地的代名词。从湖畔温泉旅馆眺望的“逆富士”别有一番风味。", bestSeason: "全年", stayTime: "半天", access: "从河口湖站乘周游巴士" },
    "oshino-hakkai": { name: "忍野八海", description: "富士山伏流水涌出的八处清池。茅草屋村落风景与清澈见底的碧水相映成画。", bestSeason: "全年", stayTime: "约1.5小时", access: "从富士山站乘巴士约20分钟" },
    "kamikochi": { name: "上高地", description: "梓川倒映穗高连峰,河童桥横跨其上。海拔1500米的山岳度假地,盛夏依然凉爽宜人。", bestSeason: "5〜10月", stayTime: "半天", access: "从松本站乘巴士等约1.5小时(私家车管制)" },
    "matsumoto-castle": { name: "松本城", description: "以北阿尔卑斯为背景的漆黑现存天守。护城河中的“倒影松本城”和城下町的手工艺店巡游也很有趣。", bestSeason: "全年", stayTime: "约2小时", access: "从松本站步行约15分钟" },
    "shirakawago": { name: "白川乡", description: "合掌造聚落的世界遗产。从展望台俯瞰的村落风景四季各有画意。", bestSeason: "全年", stayTime: "约3小时", access: "从高山乘巴士约50分钟" },
    "takayama": { name: "飞驒高山·老街", description: "出格子商家连绵的城下町。飞驒牛握寿司、早市小吃、酒藏巡游,尽享“飞驒小京都”。", bestSeason: "全年", stayTime: "约3小时", access: "从高山站步行约10分钟" },
    "atami-onsen": { name: "热海温泉", description: "从东京交通便利的海滨温泉街。商店街边走边吃和海上花火大会人气很高。", bestSeason: "全年", stayTime: "半天或住一晚", access: "热海站步行即到" },
    "miho-no-matsubara": { name: "三保松原", description: "隔着羽衣传说的松原遥望富士山的世界文化遗产。白砂青松与骏河湾的全景宛如浮世绘。", bestSeason: "11〜2月(富士山清晰可见)", stayTime: "约1.5小时", access: "从清水站乘巴士约25分钟" },
    "nagoya-castle": { name: "名古屋城", description: "金鯱闪耀的尾张德川家居城。本丸御殿复原的华丽障壁画必看,金鯱横丁还能享受美食。", bestSeason: "全年", stayTime: "约2小时", access: "地铁名古屋城站即到" },
    "inuyama-castle": { name: "犬山城与城下町", description: "俯瞰木曾川的国宝天守,山下是小吃热闹的城下町。天守顶层的眺望让人有城主气分。", bestSeason: "全年", stayTime: "约3小时", access: "从犬山站步行约20分钟" },
    "yahiko-shrine": { name: "弥彦神社", description: "拥有2400年历史的越后一宫。乘弥彦山缆车登顶,越后平原与日本海的大全景尽收眼底。", bestSeason: "10〜11月", stayTime: "约2小时", access: "从弥彦站步行约15分钟" },
    "echigo-yuzawa": { name: "越后汤泽温泉", description: "川端康成《雪国》的舞台。站内的“ponshu馆”可以品鉴新潟几乎所有酒藏的日本酒。", bestSeason: "12〜3月", stayTime: "半天", access: "越后汤泽站步行即到" },
    "kurobe-gorge": { name: "黑部峡谷小火车", description: "乘无窗小火车穿行日本最深的V字峡谷。脚下的黑部川与漫山红叶气势撼人。", bestSeason: "10〜11月", stayTime: "半天", access: "从宇奈月温泉站旁的宇奈月站乘车" },
    "amaharashi": { name: "雨晴海岸", description: "隔着富山湾遥望3000米级立山连峰的奇迹景色。冬日清晨海面升起雾气时如梦似幻。", bestSeason: "11〜2月", stayTime: "约1小时", access: "从雨晴站步行约5分钟" },
    "higashi-chaya": { name: "金泽·东茶屋街", description: "出格子茶屋建筑连绵的金泽第一风情街。金箔冰淇淋和町家咖啡馆的边走边吃也很有趣。", bestSeason: "全年", stayTime: "约2小时", access: "从金泽站乘巴士约10分钟" },
    "omicho-market": { name: "近江町市场", description: "约170家店铺的“金泽市民厨房”。螃蟹、甜虾、喉黑鱼,海鲜盖饭名店清晨就排起长队。", bestSeason: "11〜2月", stayTime: "约1.5小时", access: "从金泽站步行约15分钟" },
    "wakura-onsen": { name: "和仓温泉", description: "面朝七尾湾的“海之温泉”。开汤1200年,以巡汤和能登海味自豪。", bestSeason: "全年", stayTime: "半天", access: "从和仓温泉站驾车约5分钟" },
    "mikatagoko": { name: "三方五湖彩虹线", description: "五个湖泊各呈现不同蓝色的绝景兜风公路。山顶公园的足汤和露台可将美景一览无余。", bestSeason: "4〜11月", stayTime: "约2小时", access: "从三方站驾车约15分钟" },
    "echizen-ono-castle": { name: "越前大野城", description: "秋冬拂晓漂浮在云海上的“天空之城”。城下町是名水之乡,还有延续400年的早市。", bestSeason: "10〜4月", stayTime: "约2小时", access: "从越前大野站步行约30分钟" },
    "arakurayama-sengen": { name: "新仓山浅间公园", description: "五重塔与樱花映衬富士山,海外最负盛名的日本风景之一。登上398级台阶,绝景在等你。", bestSeason: "4月", stayTime: "约1.5小时", access: "从下吉田站步行约20分钟" },
    "hottarakashi-onsen": { name: "放置温泉", description: "从海拔700米俯瞰甲府盆地和富士山的绝景露天温泉。日出前1小时开放的晨汤是名物。", bestSeason: "全年", stayTime: "约2小时", access: "从山梨市站驾车约10分钟" },
    "zenkoji": { name: "善光寺", description: "“一生至少参拜一次善光寺”的无宗派古刹。在漆黑回廊中摸索前行的“戒坛巡游”必须体验。", bestSeason: "全年", stayTime: "约2小时", access: "从长野站乘巴士约10分钟" },
    "jigokudani-yaen": { name: "地狱谷野猿公苑", description: "世界唯一能近距离观察泡温泉的日本猕猴“雪猴”的地方。", bestSeason: "12〜3月", stayTime: "约2小时", access: "从汤田中站乘巴士+步行约1小时" },
    "narai-juku": { name: "奈良井宿", description: "中山道驿站小镇,日本最长的约1公里老街。手持五平饼,漫步漆器铺与木曾路风情。", bestSeason: "4〜11月", stayTime: "约2小时", access: "奈良井站步行即到" },
    "gero-onsen": { name: "下吕温泉", description: "位列日本三名泉的“美人汤”。温泉街上免费足汤散布,凭“巡汤手形”可以泡遍名汤。", bestSeason: "全年", stayTime: "半天", access: "下吕站步行即到" },
    "gujo-hachiman": { name: "郡上八幡", description: "水渠遍布全城的“水之城”。夏天的郡上舞持续32夜,盂兰盆的通宵舞将气氛推向高潮。", bestSeason: "7〜8月", stayTime: "约2小时", access: "从郡上八幡站步行约20分钟" },
    "shuzenji-onsen": { name: "修善寺温泉", description: "伊豆最古老的温泉场。竹林小径、朱红桂桥和河中涌出的“独钴之汤”撩动旅情。", bestSeason: "11月", stayTime: "半天", access: "从修善寺站乘巴士约10分钟" },
    "jogasaki": { name: "城崎海岸", description: "熔岩造就的断崖绝壁海岸线。高23米的海上吊桥“门胁吊桥”惊险刺激。", bestSeason: "全年", stayTime: "约2小时", access: "从伊豆高原站步行约35分钟" },
    "atsuta-jingu": { name: "热田神宫", description: "供奉三种神器之一草薙神剑的高格神社。门前的鳗鱼饭三吃名店与参拜是绝配。", bestSeason: "全年", stayTime: "约1.5小时", access: "从神宫前站步行约3分钟" },
    "osu": { name: "大须商店街", description: "大须观音门前约1200家店铺。电器街、古着、小吃混杂交融,是名古屋的混沌厨房。", bestSeason: "全年", stayTime: "约2小时", access: "大须观音站步行即到" },
    "ise-jingu": { name: "伊势神宫", description: "被亲切称为“伊势大人”的日本总氏神。参拜后去御荫横丁吃伊势乌冬和赤福吧。", bestSeason: "全年", stayTime: "约3小时", access: "从五十铃川站乘巴士约6分钟" },
    "meoto-iwa": { name: "二见兴玉神社·夫妇岩", description: "被大注连绳系在一起的大小两块岩石浮于海上,是结缘圣地。5〜7月可以看到朝阳从岩间升起。", bestSeason: "5〜7月", stayTime: "约1小时", access: "从二见浦站步行约15分钟" },
    "hikone-castle": { name: "彦根城", description: "俯瞰琵琶湖的国宝现存天守。玄宫园的借景庭园,还能见到吉祥物鼻祖“彦根猫”。", bestSeason: "全年", stayTime: "约2小时", access: "从彦根站步行约15分钟" },
    "shirahige-shrine": { name: "白须神社", description: "朱红大鸟居立于琵琶湖中的“近江严岛”。朝霞或月夜中浮现的鸟居美得令人屏息。", bestSeason: "全年", stayTime: "约30分钟", access: "从近江高岛站驾车约5分钟" },
    "fushimi-inari": { name: "伏见稻荷大社", description: "延伸至山顶的千本鸟居是这里独有的景观。推荐清晨参拜。", bestSeason: "全年", stayTime: "约2小时", access: "JR稻荷站即到" },
    "arashiyama": { name: "岚山", description: "以渡月桥和竹林小径闻名的京都第一胜景。还能体验观光小火车和保津川漂流。", bestSeason: "11月", stayTime: "半天", access: "岚山站即到" },
    "kinkakuji": { name: "金阁寺", description: "金色楼阁倒映镜湖池,是京都的代名词。雪妆晨景的金阁是一生难忘的景色。", bestSeason: "全年", stayTime: "约1小时", access: "从京都站乘巴士约40分钟" },
    "nara-park": { name: "奈良公园·东大寺", description: "大佛殿与园内自由漫步的约1200头鹿。春日大社和兴福寺也在步行范围内。", bestSeason: "全年", stayTime: "约3小时", access: "从近铁奈良站步行约5分钟" },
    "yoshinoyama": { name: "吉野山", description: "被誉为“一目千本”的日本第一赏樱名所。约3万株山樱从下千本向奥千本次第开放。", bestSeason: "4月", stayTime: "半天", access: "从吉野站乘索道" },
    "dotonbori": { name: "道顿堀", description: "格力高招牌和霓虹闪烁的大阪南部中心。章鱼烧、串炸,“吃到破产”之街。", bestSeason: "全年", stayTime: "约3小时", access: "从难波站步行约5分钟" },
    "osaka-castle": { name: "大阪城", description: "丰臣秀吉筑造的天下名城。巨石石垣和广阔公园是都市绿洲,春天则是赏樱名所。", bestSeason: "全年", stayTime: "约2小时", access: "从大阪城公园站步行约15分钟" },
    "himeji-castle": { name: "姬路城", description: "别名白鹭城,日本第一批世界文化遗产。现存天守的白墙之美独一无二。", bestSeason: "全年", stayTime: "约2.5小时", access: "从姬路站步行约20分钟" },
    "kinosaki-onsen": { name: "城崎温泉", description: "穿浴衣踏木屐沿柳树河畔巡游七大外汤的温泉街。冬季更是松叶蟹的著名产地。", bestSeason: "11〜3月", stayTime: "住一晚", access: "城崎温泉站步行即到" },
    "shirahama": { name: "南纪白滨·白良滨", description: "白沙碧海绵延的关西屈指可数的度假地。日本三古汤之一的白滨温泉和圆月岛夕阳也是看点。", bestSeason: "6〜9月", stayTime: "半天或住一晚", access: "从白滨站乘巴士约15分钟" },
    "nachi-falls": { name: "那智瀑布·熊野那智大社", description: "落差133米的日本第一名瀑与朱红三重塔并立的熊野信仰圣地。推荐从大门坂石板路徒步参拜。", bestSeason: "全年", stayTime: "约3小时", access: "从纪伊胜浦站乘巴士约30分钟" },
    "okage-yokocho": { name: "御荫横丁", description: "伊势神宫内宫前,再现江户至明治伊势风情的街区。赤福本店、伊势乌冬,边走边吃的天堂。", bestSeason: "全年", stayTime: "约2小时", access: "从伊势市站乘巴士约15分钟" },
    "enryakuji": { name: "比叡山延历寺", description: "最澄开创、“不灭法灯”燃烧1200年的天台宗总本山。世界遗产的整座山都是修行道场。", bestSeason: "10〜11月", stayTime: "半天", access: "从京都站乘电车和缆车约1小时" },
    "kiyomizudera": { name: "清水寺", description: "从“清水舞台”一览京都市街的世界遗产。二年坂、三年坂的参道漫步也是旅行的精髓。", bestSeason: "4月·11月", stayTime: "约2小时", access: "从京都站乘巴士+步行约25分钟" },
    "gion": { name: "祇园·花见小路", description: "茶屋连绵的石板花街。黄昏时分,或许能邂逅舞妓。", bestSeason: "全年", stayTime: "约1.5小时", access: "从祇园四条站步行约5分钟" },
    "nishiki-market": { name: "锦市场", description: "拥有400年历史的“京都厨房”。约130家店铺,京都酱菜、汤叶、豆乳甜甜圈边走边吃。", bestSeason: "全年", stayTime: "约1.5小时", access: "从乌丸站步行约3分钟" },
    "amanohashidate": { name: "天桥立", description: "日本三景之一,全长3.6公里的沙洲。从观景台“胯下窥视”,宛如天上架桥。", bestSeason: "全年", stayTime: "半天", access: "天桥立站步行即到" },
    "ine-funaya": { name: "伊根舟屋", description: "约230栋舟屋立于海上的渔村。从海上出租车望去,宛如水上都市。", bestSeason: "全年", stayTime: "约2小时", access: "从天桥立站乘巴士约1小时" },
    "horyuji": { name: "法隆寺", description: "现存世界最古老的木造建筑群。五重塔与百济观音,漫步教科书里的飞鸟世界。", bestSeason: "全年", stayTime: "约2小时", access: "从法隆寺站步行约20分钟" },
    "hasedera": { name: "长谷寺", description: "沿399级登廊而上的“花之御寺”。牡丹、绣球、红叶,四季鲜花将山寺淹没。", bestSeason: "4〜6月", stayTime: "约2小时", access: "从长谷寺站步行约15分钟" },
    "asuka": { name: "明日香村", description: "石舞台古坟和高松塚古坟散布田园的日本原风景。租辆自行车巡游飞鸟时代。", bestSeason: "3〜5月·9〜11月", stayTime: "半天", access: "从飞鸟站骑自行车前往各处" },
    "shinsekai": { name: "新世界·通天阁", description: "串炸、炖牛筋、夸张招牌。以通天阁为中心,昭和复古风满载的大阪深度地带。", bestSeason: "全年", stayTime: "约2小时", access: "从惠美须町站步行约3分钟" },
    "minoo-falls": { name: "箕面大瀑布", description: "从大阪市内乘电车30分钟可达的落差33米名瀑。瀑布道的红叶和名物“炸枫叶”是秋日风物诗。", bestSeason: "11月", stayTime: "约2小时", access: "从箕面站步行约40分钟" },
    "arima-onsen": { name: "有马温泉", description: "太阁秀吉钟爱的日本三古汤。铁分浑赤的“金泉”与无色透明的“银泉”双汤巡游。", bestSeason: "全年", stayTime: "半天", access: "从神户电铁有马温泉站步行约5分钟" },
    "takeda-castle": { name: "竹田城迹", description: "秋日拂晓漂浮在云海上的“天空之城”。从对面立云峡眺望的石垣剪影令人屏息。", bestSeason: "9〜11月", stayTime: "约2小时", access: "从竹田站乘天空巴士约20分钟" },
    "koyasan": { name: "高野山", description: "空海开创的海拔800米宗教都市。奥之院的杉木林、宿坊的精进料理和晨间勤行让心灵沉静。", bestSeason: "5〜11月", stayTime: "1天", access: "从极乐桥站乘缆车约5分钟" },
    "kumano-kodo": { name: "熊野古道·大门坂", description: "树龄800年的杉木林荫下,青苔石板路绵延的熊野朝圣之路。从大门坂到那智瀑布,走完约2.5公里圣路。", bestSeason: "3〜5月·10〜11月", stayTime: "约2小时", access: "从纪伊胜浦站乘巴士约20分钟" },
    "tottori-sakyu": { name: "鸟取沙丘", description: "日本最大级的沙丘。可以体验骑骆驼和滑沙,毗邻的沙之美术馆也值得一看。", bestSeason: "全年", stayTime: "约2小时", access: "从鸟取站乘巴士约20分钟" },
    "mizuki-shigeru-road": { name: "水木茂之路", description: "177座妖怪铜像林立的境港商店街。夜晚路面浮现妖怪影绘,展现与白天不同的一面。", bestSeason: "全年", stayTime: "约2小时", access: "境港站即到" },
    "izumo-taisha": { name: "出云大社", description: "以结缘之神闻名的古社。巨大注连绳气势十足,门前町的出云荞麦面也是名物。", bestSeason: "全年", stayTime: "约2小时", access: "从出云市站乘巴士约25分钟" },
    "adachi-museum": { name: "足立美术馆", description: "被誉为“活的日本画”的庭园,在美国杂志的日本庭园排名中连年第一。横山大观收藏也必看。", bestSeason: "全年", stayTime: "约2小时", access: "从安来站乘免费班车约20分钟" },
    "kurashiki": { name: "仓敷美观地区", description: "白墙仓房与柳树相伴的运河小镇。乘川舟游览,或漫步牛仔布街,乐趣多多。", bestSeason: "全年", stayTime: "约3小时", access: "从仓敷站步行约15分钟" },
    "korakuen": { name: "冈山后乐园", description: "借景冈山城的日本三名园之一。开阔的草坪与曲水营造出其他名园没有的开放感。", bestSeason: "全年", stayTime: "约1.5小时", access: "从冈山站乘巴士约15分钟" },
    "itsukushima": { name: "严岛神社", description: "以浮于海上的大鸟居闻名的世界遗产。退潮时可以走到鸟居脚下。宫岛名物星鳗饭和红叶馒头也别错过。", bestSeason: "全年", stayTime: "约3小时", access: "从宫岛口乘渡轮约10分钟" },
    "genbaku-dome": { name: "原爆圆顶·和平纪念公园", description: "向今天传递核武器惨祸的世界遗产。与资料馆一起参观,静静献上对和平的祈愿。", bestSeason: "全年", stayTime: "约2小时", access: "从广岛站乘路面电车约15分钟" },
    "onomichi": { name: "尾道", description: "坡道、猫与寺庙之城。千光寺眺望尾道水道、小巷漫步、尾道拉面,乐趣满载。", bestSeason: "全年", stayTime: "半天", access: "尾道站步行即到" },
    "tsunoshima-bridge": { name: "角岛大桥", description: "笔直延伸于翡翠绿海面的约1780米大桥。兜风绝景的经典之地。", bestSeason: "5〜9月", stayTime: "约1小时", access: "从新下关站驾车约1小时" },
    "kintaikyo": { name: "锦带桥", description: "五连木造拱桥横跨锦川,日本三名桥之一。樱花和鸬鹚捕鱼的季节格外入画。", bestSeason: "4月·6〜8月", stayTime: "约1.5小时", access: "从岩国站乘巴士约20分钟" },
    "motonosumi-shrine": { name: "元乃隅神社", description: "123座朱红鸟居向大海绵延的绝景神社。也来挑战日本最难投的赛钱箱(位于鸟居顶上)吧。", bestSeason: "全年", stayTime: "约1小时", access: "从长门市站驾车约20分钟" },
    "misasa-onsen": { name: "三朝温泉", description: "世界屈指可数的氡温泉。伴着三德川的潺潺水声泡河原风吕,再漫步复古的温泉本通。", bestSeason: "全年", stayTime: "半天", access: "从仓吉站乘巴士约25分钟" },
    "matsue-castle": { name: "松江城", description: "全国仅存12座现存天守之一,国宝。乘小舟环游护城河眺望城下町,风情满溢。", bestSeason: "全年", stayTime: "约2小时", access: "从松江站乘巴士约10分钟" },
    "tamatsukuri-onsen": { name: "玉造温泉", description: "《出云国风土记》中就有记载的美肌之汤。玉汤川沿岸勾玉桥与足汤相连,夜晚灯火温柔。", bestSeason: "全年", stayTime: "半天", access: "从玉造温泉站驾车约5分钟" },
    "bitchu-matsuyama-castle": { name: "备中松山城", description: "海拔430米,现存天守中位置最高的山城。秋日清晨可从展望台捕捉其漂浮云海的身影。", bestSeason: "9〜4月", stayTime: "约2小时", access: "从备中高梁站乘共乘出租车+步行约30分钟" },
    "okunoshima": { name: "大久野岛", description: "约500只野生兔子栖息的“兔子岛”。渡轮15分钟,骑自行车环岛约1小时。", bestSeason: "全年", stayTime: "半天", access: "从忠海港乘渡轮约15分钟" },
    "saijo-sakagura": { name: "东广岛·西条酒藏通", description: "红砖烟囱与白墙酒藏并立的日本三大酒乡之一。巡游七家酒藏还能试饮。", bestSeason: "10月", stayTime: "约2小时", access: "从西条站步行约5分钟" },
    "akiyoshido": { name: "秋芳洞·秋吉台", description: "日本最大级的喀斯特台地及其地下的大钟乳洞。百枚皿和黄金柱必看。", bestSeason: "全年", stayTime: "半天", access: "从新山口站乘巴士约40分钟" },
    "hagi": { name: "萩城下町", description: "孕育了吉田松阴和维新志士的城下町。骑自行车穿行夏蜜柑土墙与武家宅邸。", bestSeason: "全年", stayTime: "半天", access: "从东萩站骑自行车约10分钟" },
    "iya-kazurabashi": { name: "祖谷藤蔓桥", description: "以山藤蔓编成、横跨深谷的吊桥。从脚下缝隙窥见的溪谷惊险满点。", bestSeason: "4〜11月", stayTime: "约1小时", access: "从大步危站驾车约20分钟" },
    "naruto-whirlpools": { name: "鸣门漩涡", description: "世界最大级的漩涡翻卷的鸣门海峡。乘观潮船近距离逼近,或从“涡之道”玻璃地板正上方俯瞰。", bestSeason: "春秋大潮", stayTime: "约2小时", access: "从鸣门站乘巴士约20分钟" },
    "kotohiragu": { name: "金刀比罗宫", description: "以“金毗罗大人”之名为人熟知,本宫位于785级石阶之上。参道的赞岐乌冬也不可错过。", bestSeason: "全年", stayTime: "约3小时", access: "从琴平站步行+785级石阶" },
    "chichibugahama": { name: "父母滨", description: "退潮的黄昏,潮池化作明镜——“日本的乌尤尼盐湖”。上镜度极高的夕阳名所。", bestSeason: "全年", stayTime: "约1.5小时", access: "从诧间站驾车约10分钟" },
    "dogo-onsen": { name: "道后温泉", description: "日本最古老级的温泉。在重要文化财的道后温泉本馆入浴,再穿浴衣漫步商店街是经典玩法。", bestSeason: "全年", stayTime: "半天或住一晚", access: "道后温泉站即到" },
    "shimanami-kaido": { name: "岛波海道", description: "用桥梁串联濑户内群岛的骑行者圣地。从龟老山展望公园眺望的多岛美与大桥全景震撼人心。", bestSeason: "3〜11月", stayTime: "半天〜1天", access: "从今治站·尾道站租自行车" },
    "shimanto-river": { name: "四万十川", description: "“日本最后的清流”。无栏杆的沉下桥与屋形船川游,享受悠然时光。", bestSeason: "5〜10月", stayTime: "半天", access: "从中村站驾车约15分钟(佐田沉下桥)" },
    "katsurahama": { name: "桂滨", description: "坂本龙马像凝望太平洋的弓形海滨。作为赏月名所著称,配上弘人市场的鲣鱼半敲烧最佳。", bestSeason: "全年", stayTime: "约1.5小时", access: "从高知站乘巴士约40分钟" },
    "oboke-koboke": { name: "大步危·小步危", description: "吉野川激流历经2亿年雕刻的溪谷。乘游览船或漂流,近距离感受翡翠水流与奇岩。", bestSeason: "4〜11月", stayTime: "约2小时", access: "从大步危站步行约20分钟" },
    "awaodori-kaikan": { name: "阿波舞会馆", description: "一年四季都能体验400年历史的阿波舞。跟着专属舞连的表演一起跳,你也是“跳舞的傻瓜”。", bestSeason: "全年", stayTime: "约1.5小时", access: "从德岛站步行约10分钟" },
    "ritsurin": { name: "栗林公园", description: "被誉为“一步一景”的大名庭园巅峰。从飞来峰俯瞰偃月桥与假山之景,只能说绝妙。", bestSeason: "全年", stayTime: "约2小时", access: "从栗林公园北口站步行约3分钟" },
    "naoshima": { name: "直岛", description: "草间弥生的南瓜和安藤忠雄建筑散布的现代艺术之岛。从港口骑自行车巡游艺术。", bestSeason: "3〜11月", stayTime: "1天", access: "从高松港乘渡轮约50分钟" },
    "matsuyama-castle": { name: "松山城", description: "现存12天守之一。乘缆椅登上本丸广场,松山市街与濑户内海一览无余。", bestSeason: "全年", stayTime: "约2小时", access: "从大街道电车站步行+缆椅约15分钟" },
    "uchiko": { name: "内子老街", description: "因木蜡而繁荣的商家白墙延续的八日市护国地区。现役剧场“内子座”也可参观。", bestSeason: "全年", stayTime: "约2小时", access: "从内子站步行约10分钟" },
    "hirome-ichiba": { name: "高知·弘人市场", description: "从中午就着酒享用稻草炙烤鲣鱼。60多家店铺云集,是高知的社交场。", bestSeason: "全年", stayTime: "约2小时", access: "从高知城前电车站步行约2分钟" },
    "nikobuchi": { name: "仁淀渊", description: "成为“仁淀蓝”代名词的神秘水潭。晴天正午前后,水面闪耀最深邃的蓝。", bestSeason: "全年", stayTime: "约1小时", access: "从伊野站驾车约40分钟" },
    "nakasu-yatai": { name: "福冈·中洲屋台街", description: "沿河排开的屋台是博多夜晚的名物。豚骨拉面、炒拉面、饺子,一摊接一摊。", bestSeason: "全年", stayTime: "约2小时", access: "从中洲川端站步行约5分钟" },
    "dazaifu-tenmangu": { name: "太宰府天满宫", description: "祭祀学问之神菅原道真的全国天满宫总本宫。参道现烤的梅枝饼不容错过。", bestSeason: "全年", stayTime: "约2小时", access: "从太宰府站步行约5分钟" },
    "mifuneyama-rakuen": { name: "御船山乐园", description: "借景断崖的武雄大庭园。春天20万株杜鹃,夏天teamLab光影艺术,梦幻迷人。", bestSeason: "4〜5月·7〜10月", stayTime: "约2小时", access: "从武雄温泉站驾车约5分钟" },
    "yutoku-inari": { name: "祐德稻荷神社", description: "被誉为“镇西日光”的日本三大稻荷之一。悬空而建的朱红本殿是悬造建筑的杰作。", bestSeason: "全年", stayTime: "约1.5小时", access: "从肥前鹿岛站乘巴士约10分钟" },
    "inasayama": { name: "稻佐山夜景", description: "灯火在钵状街区闪烁的“世界新三大夜景”。缆车5分钟,山顶展望台上是千万美元夜景。", bestSeason: "全年", stayTime: "约2小时", access: "从长崎站乘车+缆车约20分钟" },
    "gunkanjima": { name: "军舰岛(端岛)", description: "浮于海上的废墟煤矿岛。曾拥有世界第一人口密度的世界遗产,可乘登岛游轮前往。", bestSeason: "4〜10月", stayTime: "半天(跟团)", access: "从长崎港乘游轮约40分钟" },
    "aso-daikanbo": { name: "阿苏·大观峰", description: "世界屈指可数的破火山口与草原铺展的雄大风景。大观峰的眺望和阿苏赤牛盖饭是名物。", bestSeason: "4〜11月", stayTime: "约1小时", access: "从阿苏站驾车约30分钟" },
    "kurokawa-onsen": { name: "黑川温泉", description: "和风旅馆依偎山间的“入汤手形”温泉乡。凭三联手形可以随意巡泡心仪旅馆的露天温泉。", bestSeason: "全年", stayTime: "半天或住一晚", access: "从阿苏站乘巴士约50分钟" },
    "yufuin-onsen": { name: "由布院温泉", description: "遥望由布岳的人气温泉地。汤之坪街道边走边吃,再看晨雾笼罩的金鳞湖。", bestSeason: "全年", stayTime: "半天或住一晚", access: "从由布院站步行约15分钟(金鳞湖)" },
    "beppu-jigoku": { name: "别府·地狱巡游", description: "钴蓝的海地狱、鲜红的血池地狱,巡游七大源泉的别府名物。涌出量日本第一。", bestSeason: "全年", stayTime: "约3小时", access: "从别府站乘巴士约15分钟" },
    "takachiho-gorge": { name: "高千穗峡", description: "真名井瀑布泻落柱状节理断崖的神秘峡谷。划小船可以到瀑布近旁。", bestSeason: "全年", stayTime: "约2小时", access: "从延冈站驾车约1小时" },
    "aoshima": { name: "青岛", description: "被称为“鬼之洗衣板”的波状岩环绕的亚热带小岛。棕榈树与青岛神社充满南国风情。", bestSeason: "全年", stayTime: "约1.5小时", access: "从青岛站步行约10分钟" },
    "yakushima": { name: "屋久岛", description: "数千年绳文杉与青苔森林的世界自然遗产。白谷云水峡徒步很受欢迎。", bestSeason: "3〜11月", stayTime: "1天以上", access: "从鹿儿岛港乘高速船约2〜3小时" },
    "sakurajima": { name: "樱岛", description: "至今仍喷烟的鹿儿岛象征。渡轮仅15分钟,在熔岩渚公园足汤中仰望雄伟山容。", bestSeason: "全年", stayTime: "约3小时", access: "从鹿儿岛港乘渡轮约15分钟" },
    "churaumi": { name: "冲绳美丽海水族馆", description: "鲸鲨悠游巨大水槽“黑潮之海”,震撼人心。周边的海洋博公园和翡翠海滩也值得一去。", bestSeason: "全年", stayTime: "约3小时", access: "从那霸机场驾车约2小时" },
    "kouri-island": { name: "古宇利岛", description: "经古宇利大桥笔直跨越清澈海面,驶向“恋之岛”。心形岩和绝景咖啡馆人气很高。", bestSeason: "4〜10月", stayTime: "约2小时", access: "从那霸机场驾车约1.5小时" },
    "taketomi-island": { name: "竹富岛", description: "保留红瓦聚落与白沙道的八重山离岛。乘水牛车巡游聚落,再到孔多伊海滩踏浪。", bestSeason: "全年", stayTime: "半天", access: "从石垣港乘渡轮约15分钟" },
    "yanagawa": { name: "柳川游船", description: "乘小舟悠然漂过城下町的护城河。最后以名物鳗鱼蒸笼饭收尾才是柳川做派。", bestSeason: "全年", stayTime: "半天", access: "从西铁柳川站步行约8分钟" },
    "itoshima": { name: "糸岛·樱井二见浦", description: "白色鸟居与夫妇岩映衬落日。海边咖啡馆和冬季牡蛎小屋,是福冈市民一日兜风的经典。", bestSeason: "4〜10月", stayTime: "半天", access: "从筑前前原站驾车约20分钟" },
    "yobuko": { name: "呼子早市", description: "日本三大早市之一。名物活鱿鱼刺身晶莹剔透,鱿鱼须最后还会做成天妇罗。", bestSeason: "全年", stayTime: "约2小时", access: "从唐津站乘巴士约30分钟" },
    "unzen-jigoku": { name: "云仙地狱", description: "硫磺蒸汽升腾的地狱巡游,与日本第一座国立公园的云仙温泉。名物是温泉蛋。", bestSeason: "全年", stayTime: "半天", access: "从谏早站乘巴士约1小时20分钟" },
    "kujukushima": { name: "九十九岛", description: "佐世保近海208座岛屿散布的里亚斯海岸。游览船巡航和展海峰的夕照最为著名。", bestSeason: "全年", stayTime: "半天", access: "从佐世保站乘巴士约25分钟" },
    "kumamoto-castle": { name: "熊本城", description: "以“武者返”石垣闻名的天下名城。震后修复不断推进,可从特别参观通道见证名城重生。", bestSeason: "全年", stayTime: "约2小时", access: "从熊本站乘市电约15分钟" },
    "amakusa-sakitsu": { name: "天草·崎津聚落", description: "教堂尖塔耸立于渔村屋舍间的世界遗产潜伏基督徒聚落。在面海的祈祷之乡慢慢走走。", bestSeason: "全年", stayTime: "约2小时", access: "从本渡巴士中心驾车约30分钟" },
    "kokonoe-yume-bridge": { name: "九重“梦”大吊桥", description: "高173米,日本第一高的步行专用吊桥。脚下震动瀑布与九醉溪的莽莽林海铺展开来。", bestSeason: "10〜11月", stayTime: "约1小时", access: "从丰后中村站乘巴士约20分钟" },
    "usa-jingu": { name: "宇佐神宫", description: "全国4万座八幡神社的总本宫。国宝朱红本殿,包裹在神代森林的清澈空气中。", bestSeason: "全年", stayTime: "约2小时", access: "从宇佐站乘巴士约10分钟" },
    "udo-jingu": { name: "鹈户神宫", description: "本殿镇座于面朝太平洋的断崖洞窟中。把“运玉”投入龟石凹槽,祈求良缘。", bestSeason: "全年", stayTime: "约1.5小时", access: "从宫崎站乘巴士约1.5小时" },
    "ebino-kogen": { name: "虾野高原", description: "雾岛连山环抱的海拔1200米高原。韩国岳登山和巡池步道,秋天芒草原染成金色。", bestSeason: "5〜11月", stayTime: "半天", access: "从小林站驾车约30分钟" },
    "kirishima-jingu": { name: "雾岛神宫", description: "建于天孙降临之地的朱红神社。树龄800年的神木和青苔参道,引人步入神话世界。", bestSeason: "全年", stayTime: "约1.5小时", access: "从雾岛神宫站乘巴士约10分钟" },
    "ibusuki-onsen": { name: "指宿温泉", description: "在浪花边享受世界罕见的天然砂蒸温泉。穿浴衣埋进沙里,10分钟就大汗淋漓。", bestSeason: "全年", stayTime: "半天", access: "从指宿站步行约20分钟" },
    "amami-oshima": { name: "奄美大岛", description: "金作原的亚热带原生林与透明度超群的土盛海岸。奄美黑兔栖息的世界自然遗产之岛。", bestSeason: "4〜10月", stayTime: "1天以上", access: "从奄美机场驾车前往各处" },
    "shurijo": { name: "首里城", description: "传承琉球王国荣华的王城。2019年火灾后正殿修复推进中,可参观“可视化重建”现场。", bestSeason: "全年", stayTime: "约2小时", access: "从单轨电车首里站步行约15分钟" },
    "kokusai-dori": { name: "国际通", description: "那霸约1.6公里的主街。牛排、Blue Seal冰淇淋,侧巷市场本通深处还有牧志公设市场。", bestSeason: "全年", stayTime: "约3小时", access: "从单轨电车县厅前站步行约3分钟" },
    "manzamo": { name: "万座毛", description: "被赞为“可坐万人的草原”的象鼻状断崖。是眺望东海落日的名所。", bestSeason: "全年", stayTime: "约1小时", access: "从那霸机场驾车约1小时" },
    "kabira-bay": { name: "石垣岛·川平湾", description: "白沙与翡翠渐变铺展的米其林三星海湾。乘玻璃底船窥探珊瑚礁。", bestSeason: "全年", stayTime: "约2小时", access: "从石垣港驾车约30分钟" },
  },
  courses: {
    "kanazawa-hida-2n3d": {
      title: "金泽·白川乡·飞驒高山 3天2晚",
      summary: "乘北陆新干线抵达金泽,经世界遗产合掌村前往飞驒城下町。加贺百万石文化与山乡原风景一次尽享的王道路线。",
      notes: [
        ["上午游兼六园和东茶屋街,中午在近江町市场吃海鲜", "傍晚租车沙滩兜风,宿金泽"],
        ["上午前往展望台,悠闲漫步聚落", "归途顺路造访,独享宁静合掌村,宿高山"],
        ["从宫川早市走到老街,以飞驒牛握寿司收尾"],
      ],
    },
    "kyoto-nara-2n3d": {
      title: "京都·奈良经典巡游 3天2晚",
      summary: "千本鸟居、金阁、岚山竹林,再加上奈良大佛与小鹿。初次关西之旅首选路线,四季皆宜。",
      notes: [
        ["一早前往千本鸟居(避开人流)"],
        ["开门时分的静谧金阁", "下午渡月桥与竹林,河畔咖啡小憩"],
        ["乘近铁去奈良,大佛殿和喂鹿仙贝体验"],
      ],
    },
    "hokkaido-2n3d": {
      title: "札幌·小樽·登别 3天2晚",
      summary: "海鲜、复古港町、地狱谷名汤,浓缩初次北海道的经典路线。冬有雪景,夏有清爽气候。",
      notes: [
        ["抵达先来碗海鲜盖饭,下午漫步大通公园,宿札幌"],
        ["乘JR去小樽,玻璃工房、寿司,直到黄昏的运河"],
        ["漫步地狱谷,再以名汤收尾"],
      ],
    },
    "setouchi-2n3d": {
      title: "广岛·岛波·道后 3天2晚",
      summary: "从宫岛大鸟居到尾道坡道,骑行跨越群岛,最后泡进日本最古老级的名汤。沐浴濑户内之光与多岛美的3天。",
      notes: [
        ["在和平纪念公园献上祈祷", "下午渡往宫岛,把退潮与涨潮的大鸟居都看遍,宿广岛"],
        ["千光寺的眺望和尾道拉面", "租自行车跨岛骑行,龟老山夕景必看,宿今治"],
        ["移动到松山,本馆泡汤与商店街漫步"],
      ],
    },
    "kyushu-onsen-2n3d": {
      title: "九州 温泉与大自然 3天2晚",
      summary: "别府地狱、由布院晨雾、黑川露天、阿苏大草原、高千穗神话峡谷。纵贯九州“汤与火之国”的浓缩路线。",
      notes: [
        ["以海地狱和血池地狱为中心", "傍晚逛汤之坪街道和金鳞湖,宿由布院"],
        ["凭入汤手形巡游露天温泉", "一览破火山口后来碗赤牛盖饭,宿阿苏"],
        ["划船前往真名井瀑布"],
      ],
    },
    "tohoku-2n3d": {
      title: "陆奥风情 3天2晚",
      summary: "日本三景松岛、山寺石阶、大正浪漫的银山温泉、武家宅邸的角馆。乘新干线巡游沉静优美的东北。",
      notes: [
        ["游览船与牡蛎午餐,宿仙台"],
        ["上午挑战1015级石阶", "黄昏走进煤气灯温泉街,宿银山温泉"],
        ["乘新干线去角馆,和服漫步武家屋敷通"],
      ],
    },
    "fuji-hakone-1n2d": {
      title: "环游富士山 2天1晚",
      summary: "河口湖的逆富士、忍野的涌泉、芦之湖的海盗船、热海的温泉。周末说走就走,从各个角度欣赏富士山的小旅行。",
      notes: [
        ["从大石公园看富士与湖的全景", "漫步涌泉之乡,宿河口湖温泉"],
        ["海盗船与箱根神社湖上鸟居", "最后在热海泡汤+边走边吃"],
      ],
    },
    "okinawa-3n4d": {
      title: "冲绳 本岛与八重山 4天3晚",
      summary: "会一会鲸鲨,跨越古宇利蓝的大海,再飞往八重山。在红瓦聚落与浅滩海水中,享受什么都不做的奢侈。",
      notes: [
        ["瞄准下午的喂食时间,宿本部"],
        ["跨过古宇利大桥去绝景咖啡馆,傍晚航班飞石垣"],
        ["水牛车与孔多伊海滩的岛屿时光,宿石垣"],
        ["清晨再逛一次安静的聚落,然后踏上归途"],
      ],
    },
    "sanin-2n3d": {
      title: "山阴 出云·松江·鸟取 3天2晚",
      summary: "从结缘的出云大社到国宝松江城,连泡美肌玉造温泉与氡泉三朝温泉,最后抵达鸟取沙丘。神话与名汤的山阴之路。",
      notes: [
        ["二礼四拍手一礼祈求良缘,门前吃荞麦面", "美肌之汤与河畔足汤巡游,宿玉造"],
        ["国宝天守与护城河游船", "细细欣赏画框般的日本庭园", "移步复古温泉街,宿三朝"],
        ["清晨的沙丘风纹最美"],
      ],
    },
    "hokuriku-2n3d": {
      title: "北陆环游 金泽·能登·福井 3天2晚",
      summary: "近江町市场海鲜与东茶屋街,驰骋千里滨沙滩,泡和仓海之温泉。最后以永平寺的静谧与东寻坊断崖收笔,一笔画游北陆名胜。",
      notes: [
        ["中午在市场吃海鲜盖饭", "下午和服漫步茶屋街,宿金泽"],
        ["租车沿浪边兜风", "眺望七尾湾的海之温泉,宿和仓"],
        ["杉木林中的七堂伽蓝,还可体验坐禅", "在黄昏的断崖为旅程收尾"],
      ],
    },
    "shikoku-3n4d": {
      title: "四国环游 4天3晚",
      summary: "金毗罗参拜、鸣门漩涡、祖谷秘境、道后之汤。乌冬、鲣鱼、阿波舞,一网打尽四国精华绕上一圈。",
      notes: [
        ["抵达高松先逛名园,中午吃赞岐乌冬", "登上785级石阶参拜金毗罗,宿琴平"],
        ["查好大潮时间,走上涡之道", "夜场公演一起共舞,宿德岛"],
        ["乘游览船饱览溪谷之美", "走过惊险刺激的藤蔓桥,宿祖谷"],
        ["移动到松山,乘缆椅登本丸", "旅程最后是3000年名汤"],
      ],
    },
    "furano-biei-1n2d": {
      title: "旭川·美瑛·富良野 2天1晚",
      summary: "从行为展示的旭山动物园,到青池与薰衣草田。浓缩北海道夏日精华的周末之旅。推荐租车。",
      notes: [
        ["上午看人气的喂食时间", "午后光线让池水更蓝,宿美瑛"],
        ["一早直奔薰衣草田,最后以蜜瓜收尾"],
      ],
    },
    "minami-kyushu-2n3d": {
      title: "南九州 樱岛·指宿·雾岛·日南 3天2晚",
      summary: "喷烟的樱岛、埋进砂里的指宿、神话的雾岛神宫,再到日南海岸的鹈户神宫。火山、神话与温泉,巡游九州最南端。",
      notes: [
        ["乘渡轮过海,登上汤之平展望所", "傍晚砂蒸温泉出一身汗,宿指宿"],
        ["朱红社殿与杉木道森林浴", "漫步巡池步道,宿雾岛"],
        ["洞窟本殿与投运玉", "看着鬼之洗衣板,兜风日南海岸"],
      ],
    },
  },
};
