// 英語の翻訳辞書。UI文言と全スポット・全コースの訳文を持つ。
// キーが無い項目は日本語(原本)にフォールバックする。
const LANG_EN = {
  ui: {
    docTitle: "Nihon no Tabi — Japan Travel Guide",
    eyebrow: "Rediscover Japan.",
    heroLead: "{spots} hand-picked spots across all 47 prefectures, plus {courses} model itineraries. Tap ⭐ to save places to your wishlist, and stamp them once you've been.",
    unitSpots: "{n}",
    unitCourses: "{n}",
    tabSpots: "Explore spots",
    tabCourses: "Itineraries",
    searchPlaceholder: "Search by name or keyword",
    prefAll: "Prefecture: all",
    allLabel: "All",
    wishlistToggle: "⭐ Wishlist ({n})",
    sortAdded: "By date added",
    sortRegion: "By region",
    exportBtn: "Export",
    importBtn: "Import",
    resultCount: "{n} of {total} spots",
    emptyMsg: "No spots match your filters",
    clearFilters: "Clear filters and show all",
    seasonalHeading: "In season now",
    months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    bestSeasonLabel: "Best season",
    stayTimeLabel: "Time needed",
    accessLabel: "Getting there",
    mapLink: "View map →",
    starAdd: "☆ Add to wishlist",
    starAdded: "⭐ On your wishlist",
    visitedYes: "✓ Visited",
    visitedNo: "○ Not yet visited",
    memoLabel: "My notes",
    memoPlaceholder: "Things to check, foods to try, places to stay…",
    nearbyHeading: "Nearby spots",
    inCoursesHeading: "Itineraries featuring this spot",
    daysUnit: "{n} days",
    dayLabel: "Day {n}",
    backToCourses: "← Back to itineraries",
    confirmRemove: "This will also delete your notes and visited status. Remove from wishlist?",
    importError: "Could not read the file. Please choose a JSON file exported from this site.",
    importNone: "No valid spots found.",
    importDone: "Imported {n} spots.",
    exportFilename: "japan-travel-wishlist.json",
    photoCredit: "Photo: {a} ({l}) / Wikimedia Commons",
    footerText: "A guide to {n} hand-picked spots and model itineraries across all 47 prefectures of Japan. Photos are from Wikimedia Commons, credited on each image.",
    ariaClose: "Close",
    ariaStar: "Add or remove {name} from wishlist",
    ariaCardOpen: "View details of {name}",
    ariaDotShow: "Show photo of {name}",
    ariaCaption: "Open the spot shown in this photo",
  },
  regions: {
    "北海道": "Hokkaido", "東北": "Tohoku", "関東": "Kanto", "中部": "Chubu",
    "近畿": "Kansai", "中国": "Chugoku", "四国": "Shikoku", "九州・沖縄": "Kyushu & Okinawa",
  },
  prefectures: {
    "北海道": "Hokkaido", "青森県": "Aomori", "岩手県": "Iwate", "宮城県": "Miyagi", "秋田県": "Akita",
    "山形県": "Yamagata", "福島県": "Fukushima", "茨城県": "Ibaraki", "栃木県": "Tochigi", "群馬県": "Gunma",
    "埼玉県": "Saitama", "千葉県": "Chiba", "東京都": "Tokyo", "神奈川県": "Kanagawa", "新潟県": "Niigata",
    "富山県": "Toyama", "石川県": "Ishikawa", "福井県": "Fukui", "山梨県": "Yamanashi", "長野県": "Nagano",
    "岐阜県": "Gifu", "静岡県": "Shizuoka", "愛知県": "Aichi", "三重県": "Mie", "滋賀県": "Shiga",
    "京都府": "Kyoto", "大阪府": "Osaka", "兵庫県": "Hyogo", "奈良県": "Nara", "和歌山県": "Wakayama",
    "鳥取県": "Tottori", "島根県": "Shimane", "岡山県": "Okayama", "広島県": "Hiroshima", "山口県": "Yamaguchi",
    "徳島県": "Tokushima", "香川県": "Kagawa", "愛媛県": "Ehime", "高知県": "Kochi", "福岡県": "Fukuoka",
    "佐賀県": "Saga", "長崎県": "Nagasaki", "熊本県": "Kumamoto", "大分県": "Oita", "宮崎県": "Miyazaki",
    "鹿児島県": "Kagoshima", "沖縄県": "Okinawa",
  },
  categories: {
    "絶景": "Scenic views", "温泉": "Hot springs", "グルメ": "Food", "歴史": "History", "自然": "Nature", "街歩き": "Town walks",
  },
  spots: {
    "biei-blue-pond": { name: "Biei Blue Pond", description: "A mysterious cobalt-blue pond amid patchwork hills. Lavender fields bloom nearby in summer.", bestSeason: "Jun–Aug", stayTime: "About 1 hour", access: "About 40 min by car from Asahikawa Airport" },
    "hakodateyama": { name: "Mt. Hakodate", description: "A fan-shaped night view often called one of the world's three finest. The ropeway reaches the summit in about 3 minutes; the Motomachi district below is great for strolling.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 30 min from Hakodate Station by tram and ropeway" },
    "otaru-canal": { name: "Otaru Canal", description: "A retro canal district lined with stone warehouses, beautiful at dusk when the gas lamps come on. Known for excellent sushi and seafood bowls.", bestSeason: "Year-round", stayTime: "About 3 hours", access: "About 35 min by JR from Sapporo Station" },
    "shiretoko": { name: "Shiretoko", description: "A World Natural Heritage site. Walk the Shiretoko Five Lakes or watch brown bears and whales from a sightseeing boat in pristine wilderness.", bestSeason: "Jun–Sep", stayTime: "Half to full day", access: "About 2 hours by car from Memanbetsu Airport" },
    "noboribetsu-onsen": { name: "Noboribetsu Onsen", description: "Hokkaido's premier hot-spring town with abundant waters. The rugged landscape of Jigokudani (Hell Valley), where the springs rise, is spectacular.", bestSeason: "Year-round", stayTime: "Half day or overnight", access: "About 1 hour by car from New Chitose Airport" },
    "sapporo-nijo-market": { name: "Sapporo Nijo Market", description: "Sapporo's kitchen since the Meiji era, serving fresh seafood bowls from early morning. Odori Park and Susukino are within walking distance.", bestSeason: "Year-round", stayTime: "About 1 hour", access: "About 15 min on foot from Sapporo Station" },
    "asahiyama-zoo": { name: "Asahiyama Zoo", description: "Famous for 'behavioral exhibits' like the penguin walk and cylindrical seal tank. The animals in the snow are a winter highlight.", bestSeason: "Year-round", stayTime: "Half a day", access: "About 40 min by bus from Asahikawa Station" },
    "furano-farm-tomita": { name: "Farm Tomita, Furano", description: "The iconic lavender farm that paints the hills purple. At peak bloom in July, enjoy melon and flower-field sweets too.", bestSeason: "Jun–Aug", stayTime: "About 2 hours", access: "About 45 min by car from Asahikawa Airport" },
    "toyako": { name: "Lake Toya", description: "A caldera lake with a hot-spring town on its shore. Fireworks light up the lake every night from late April to October.", bestSeason: "Apr–Oct", stayTime: "Half a day", access: "About 2 hours by car from Sapporo" },
    "akanko": { name: "Lake Akan", description: "Home of the protected marimo moss balls. An Ainu kotan village and hot springs line the shore, with frost flowers on the ice in winter.", bestSeason: "Year-round", stayTime: "Half a day", access: "About 1 hr 10 min by car from Kushiro Airport" },
    "hakodate-asaichi": { name: "Hakodate Morning Market", description: "Some 250 stalls packed next to the station. Start your Hakodate morning with squid fishing and a seafood bowl.", bestSeason: "Year-round", stayTime: "About 1.5 hours", access: "1 min on foot from Hakodate Station" },
    "cape-kamui": { name: "Cape Kamui", description: "A cape at the tip of the Shakotan Peninsula overlooking the famed 'Shakotan blue' sea. The Charenka Trail to the point is exhilarating.", bestSeason: "Jun–Aug", stayTime: "About 1.5 hours", access: "About 1.5 hours by car from Otaru" },
    "oirase-gorge": { name: "Oirase Gorge", description: "A 14 km stream flowing from Lake Towada, with waterfalls and mossy rocks along the walking trail. Famous for fresh greenery and autumn leaves.", bestSeason: "May–Jun & Oct", stayTime: "About 3 hours", access: "About 1.5 hours by car from Aomori Station" },
    "hirosaki-castle": { name: "Hirosaki Castle & Park", description: "One of Japan's twelve original castle keeps. The spring festival, when 2,600 cherry trees fill the moats with petals, is among Japan's finest blossom scenes.", bestSeason: "Late Apr–early May", stayTime: "About 2 hours", access: "About 15 min by bus from Hirosaki Station" },
    "chusonji": { name: "Chusonji Konjikido", description: "Part of the Hiraizumi World Heritage site. The gold-leaf-covered hall built by the Oshu Fujiwara clan is simply breathtaking.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 20 min on foot from Hiraizumi Station" },
    "jodogahama": { name: "Jodogahama Beach", description: "White rhyolite rocks, green pines and crystal-clear water — the signature landscape of the Sanriku coast. Small-boat cruises to the Blue Cave are popular.", bestSeason: "Jun–Sep", stayTime: "About 2 hours", access: "About 10 min by car from Miyako Station" },
    "matsushima": { name: "Matsushima", description: "One of Japan's three most scenic views: a bay dotted with 260 islands, best seen by cruise boat. Oysters and sasa-kamaboko are local specialties.", bestSeason: "Year-round", stayTime: "About 3 hours", access: "About 40 min by JR from Sendai Station" },
    "zao-okama": { name: "Zao Okama Crater", description: "An emerald crater lake whose color shifts with the weather. Drive the Zao Echo Line to reach this mysterious sight.", bestSeason: "May–Oct", stayTime: "About 1 hour", access: "About 1.5 hours by car from Sendai" },
    "kakunodate": { name: "Kakunodate", description: "A samurai district known as the 'Little Kyoto of Tohoku.' In spring, weeping cherry trees form magnificent tunnels of blossom.", bestSeason: "Late Apr–early May", stayTime: "About 2 hours", access: "About 15 min on foot from Kakunodate Station" },
    "nyuto-onsen": { name: "Nyuto Onsen", description: "Seven secluded inns scattered through a beech forest. Famous for milky-white open-air baths and inn-hopping with a bathing pass.", bestSeason: "Year-round", stayTime: "Half day or overnight", access: "About 50 min by bus from Tazawako Station" },
    "ginzan-onsen": { name: "Ginzan Onsen", description: "Taisho-era wooden inns line the river in this hot-spring town. Gas lamps and snow make an iconic winter scene.", bestSeason: "Dec–Feb", stayTime: "Half day or overnight", access: "About 40 min by bus from Oishida Station" },
    "yamadera": { name: "Yamadera (Risshakuji)", description: "An ancient temple whose halls cling to a cliff. The view from Godaido Hall after climbing 1,015 stone steps makes you forget the effort.", bestSeason: "May–Nov", stayTime: "About 2 hours", access: "About 20 min by JR from Yamagata Station, then a walk" },
    "ouchi-juku": { name: "Ouchi-juku", description: "A preserved Edo-period post town with thatched roofs. Try the famous negi-soba, eaten with a green onion instead of chopsticks.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 10 min by car from Yunokami Onsen Station" },
    "goshiki-numa": { name: "Goshiki-numa Ponds", description: "A cluster of ponds created by the eruption of Mt. Bandai. Follow the trail past waters glowing cobalt blue and emerald green.", bestSeason: "May–Nov", stayTime: "About 2 hours", access: "About 30 min by bus from Inawashiro Station" },
    "towadako": { name: "Lake Towada", description: "The caldera lake at the heart of Towada-Hachimantai National Park, source of the Oirase Gorge. Cruise boats and the lakeside 'Maidens' statue are classics.", bestSeason: "May–Oct", stayTime: "About 2 hours", access: "About 2 hr 15 min by bus from Hachinohe Station" },
    "hachinohe-yokocho": { name: "Miroku Yokocho, Hachinohe", description: "An alley of 26 tiny stalls. Rub shoulders with locals over senbei-jiru soup and Hachinohe mackerel.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 10 min on foot from Hon-Hachinohe Station" },
    "ryusendo": { name: "Ryusendo Cave", description: "One of Japan's three great limestone caves, with an underground lake of world-class clarity known as 'Dragon Blue.'", bestSeason: "Year-round", stayTime: "About 1 hour", access: "About 2 hr 10 min by bus from Morioka Station" },
    "genbikei": { name: "Genbikei Gorge", description: "A gorge carved by the Iwai River. Don't miss the 'flying dango' — dumplings delivered by rope across the ravine.", bestSeason: "Apr–Nov", stayTime: "About 1 hour", access: "About 20 min by bus from Ichinoseki Station" },
    "akiu-onsen": { name: "Akiu Onsen", description: "An old spa known as 'Sendai's back parlor.' Nearby are the 55 m Akiu Great Falls and the rocky Rairaikyo Gorge trail.", bestSeason: "Year-round", stayTime: "Half a day", access: "About 50 min by bus from Sendai Station" },
    "naruko-onsen": { name: "Naruko Onsen", description: "A therapeutic-bath village of kokeshi dolls and clacking geta. With about 370 sources, it's said to cover 70% of Japan's spring-water types.", bestSeason: "Oct–Nov", stayTime: "Half a day", access: "Right by Naruko-Onsen Station" },
    "tazawako": { name: "Lake Tazawa", description: "Japan's deepest lake (423 m) with lapis-blue water. The golden statue of Tatsuko on the shore is a favorite photo spot.", bestSeason: "May–Oct", stayTime: "About 2 hours", access: "About 12 min by bus from Tazawako Station" },
    "oga-nyudozaki": { name: "Nyudozaki, Oga Peninsula", description: "A cape of green fields, blue sea and a striped lighthouse. Also known as the home of the Namahage folk demons.", bestSeason: "Jun–Sep", stayTime: "About 1.5 hours", access: "About 30 min by car from Oga Station" },
    "zao-onsen": { name: "Zao Onsen", description: "Strongly acidic waters said to date back 1,900 years. In winter, ride the ropeway over the world-famous 'snow monster' frost-covered trees.", bestSeason: "Dec–Feb", stayTime: "Half a day", access: "About 40 min by bus from Yamagata Station" },
    "sankyo-soko": { name: "Sankyo Warehouses, Sakata", description: "Twelve rice warehouses built in 1893, symbol of this port town. The zelkova-lined lane and black walls have starred in films.", bestSeason: "Year-round", stayTime: "About 1 hour", access: "About 5 min by car from Sakata Station" },
    "tsuruga-castle": { name: "Tsuruga Castle, Aizu-Wakamatsu", description: "The famed castle that withstood a month-long siege in the Boshin War. Its keep, Japan's only one with red roof tiles, stands out against the sky.", bestSeason: "Apr–Nov", stayTime: "About 1.5 hours", access: "About 15 min by bus from Aizu-Wakamatsu Station" },
    "kitakata": { name: "Kitakata", description: "A 'town of kura storehouses' with over 4,000 remaining. Also the holy land of 'morning ramen' culture.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 15 min on foot from Kitakata Station" },
    "hitachi-seaside-park": { name: "Hitachi Seaside Park", description: "Famous for hills of blue nemophila in spring and crimson kochia in autumn. The seasonal flower fields are overwhelming.", bestSeason: "Apr–May & Oct", stayTime: "About 3 hours", access: "About 20 min by bus from Katsuta Station" },
    "fukuroda-falls": { name: "Fukuroda Falls", description: "One of Japan's three great waterfalls, dropping in four tiers. It freezes solid in winter and pairs beautifully with autumn leaves.", bestSeason: "Nov & Jan–Feb", stayTime: "About 1 hour", access: "About 10 min by car from Fukuroda Station" },
    "nikko-toshogu": { name: "Nikko Toshogu Shrine", description: "The lavish World Heritage shrine of Tokugawa Ieyasu, with the Yomeimon Gate, Sleeping Cat and more. Combine with Kegon Falls and Lake Chuzenji.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 10 min by bus from Tobu-Nikko Station" },
    "ashikaga-flower-park": { name: "Ashikaga Flower Park", description: "Home to a magical 160-year-old great wisteria. The winter illumination, one of Kanto's three finest, is also spectacular.", bestSeason: "Mid Apr–mid May", stayTime: "About 2 hours", access: "Right by Ashikaga Flower Park Station" },
    "kusatsu-onsen": { name: "Kusatsu Onsen", description: "Japan's largest natural flow of spring water. The town spreads around the Yubatake field, where you can watch the traditional yumomi water-stirring.", bestSeason: "Year-round", stayTime: "Half day or overnight", access: "About 25 min by bus from Naganohara-Kusatsuguchi Station" },
    "ikaho-onsen": { name: "Ikaho Onsen", description: "A nostalgic spa town along a 365-step stone stairway lined with inns and shooting galleries. Known for its russet 'golden' waters.", bestSeason: "Year-round", stayTime: "Half day or overnight", access: "About 25 min by bus from Shibukawa Station" },
    "kawagoe": { name: "Kawagoe", description: "'Little Edo,' a townscape of clay-walled warehouses. Enjoy snacking your way past the Bell of Time and Candy Alley.", bestSeason: "Year-round", stayTime: "About 3 hours", access: "About 20 min on foot from Kawagoe Station" },
    "nagatoro": { name: "Nagatoro", description: "A gorge famed for boat rides between rock terraces. Renowned shaved-ice shops and the view from Mt. Hodo add to the fun.", bestSeason: "Apr–Nov", stayTime: "About 3 hours", access: "About 5 min on foot from Nagatoro Station" },
    "naritasan": { name: "Naritasan Shinshoji Temple", description: "A center of Fudo worship with over 1,000 years of history. Grilled eel at the old shops along the approach is a must.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 10 min on foot from Narita Station" },
    "yoro-valley": { name: "Yoro Valley", description: "Boso's finest gorge scenery. Stroll to Awamata Falls and soak in dark 'kuroyu' springs, an easy escape from Tokyo.", bestSeason: "Late Nov–early Dec", stayTime: "About 3 hours", access: "About 10 min by car from Yoro-Keikoku Station" },
    "asakusa-sensoji": { name: "Asakusa Sensoji Temple", description: "Tokyo's oldest temple, known for the Kaminarimon gate and Nakamise shopping street. Street food and rickshaw rides are popular.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "Right by Asakusa Station" },
    "meiji-jingu": { name: "Meiji Jingu Shrine", description: "A sacred forest that feels worlds away from the city. Pass the great torii near Harajuku Station into a hushed approach.", bestSeason: "Year-round", stayTime: "About 1.5 hours", access: "Right by Harajuku Station" },
    "tsukiji-market": { name: "Tsukiji Outer Market", description: "A food wonderland of some 400 shops. Go in the morning for seafood bowls and grilled tamagoyaki.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "Right by Tsukiji Station" },
    "kamakura": { name: "Kamakura", description: "An ancient capital with Tsurugaoka Hachimangu, the Great Buddha, Komachi Street snacks and a seaside ride on the Enoden line.", bestSeason: "Year-round", stayTime: "Half to full day", access: "About 10 min on foot from Kamakura Station" },
    "hakone-ashinoko": { name: "Hakone & Lake Ashi", description: "A classic resort with Mt. Fuji views across the lake and its pirate ships. Don't miss Owakudani's black eggs and the famous baths.", bestSeason: "Year-round", stayTime: "Half day or overnight", access: "About 35 min by bus from Hakone-Yumoto Station" },
    "kairakuen": { name: "Kairakuen Garden", description: "One of Japan's three great gardens. The plum festival in Feb–Mar, when 3,000 trees of 100 varieties bloom, is the highlight.", bestSeason: "Feb–Mar", stayTime: "About 1.5 hours", access: "About 20 min by bus from Mito Station" },
    "kegon-falls": { name: "Kegon Falls", description: "One of Japan's three great waterfalls, plunging 97 m from Lake Chuzenji. An elevator descends to a viewing deck near the basin.", bestSeason: "Oct–Nov", stayTime: "About 1 hour", access: "About 45 min by bus from Tobu-Nikko Station" },
    "utsunomiya-gyoza": { name: "Utsunomiya, City of Gyoza", description: "Over 200 dumpling specialists. Hop between shops comparing grilled, fried and boiled gyoza.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "Walking distance from Utsunomiya Station" },
    "tomioka-silk-mill": { name: "Tomioka Silk Mill", description: "A government silk mill opened in 1872, now a World Heritage site. The reeling plant and cocoon warehouses survive nearly intact.", bestSeason: "Year-round", stayTime: "About 1.5 hours", access: "About 15 min on foot from Joshu-Tomioka Station" },
    "shima-onsen": { name: "Shima Onsen", description: "A famed spring said to cure 'forty thousand ailments.' The clear-blue Shima River and the 'Shima Blue' of Lake Okushima are also worth seeing.", bestSeason: "Year-round", stayTime: "Half a day", access: "About 40 min by bus from Nakanojo Station" },
    "chichibu-hitsujiyama": { name: "Hitsujiyama Park, Chichibu", description: "Some 400,000 shibazakura moss phlox carpet the hill against Mt. Buko. Food stalls line the park at peak bloom from mid-April to early May.", bestSeason: "Apr–May", stayTime: "About 1.5 hours", access: "About 20 min on foot from Seibu-Chichibu Station" },
    "nokogiriyama": { name: "Mt. Nokogiri & Nihonji", description: "The cliff-edge 'View of Hell' lookout and Japan's largest carved stone Buddha. Take the ropeway to the summit.", bestSeason: "Year-round", stayTime: "Half a day", access: "About 20 min from Hamakanaya Station on foot and by ropeway" },
    "shibuya-crossing": { name: "Shibuya Scramble Crossing", description: "A world-famous crossing where up to 3,000 people cross on a single green light. The night view from the observation decks is popular too.", bestSeason: "Year-round", stayTime: "About 1 hour", access: "Right by Shibuya Station" },
    "ameyoko": { name: "Ameyoko, Ueno", description: "About 400 shops packed under the rail tracks. A downtown kitchen full of street food and spirited sales calls.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "Right by Ueno Station" },
    "takaosan": { name: "Mt. Takao", description: "A Michelin three-star mountain an hour from central Tokyo. Ride the cable car, try the tengu-yaki, and catch Mt. Fuji from the summit on clear days.", bestSeason: "November", stayTime: "Half a day", access: "Right by Takaosanguchi Station" },
    "yokohama-chukagai": { name: "Yokohama Chinatown", description: "Japan's largest Chinatown with some 600 establishments, from street snacks to venerable restaurants — one stomach is never enough.", bestSeason: "Year-round", stayTime: "About 3 hours", access: "Right by Motomachi-Chukagai Station" },
    "enoshima": { name: "Enoshima", description: "Street food on the approach and Sagami Bay views from the Sea Candle tower. On clear days, Mt. Fuji completes this Shonan icon.", bestSeason: "Year-round", stayTime: "Half a day", access: "About 15 min on foot from Katase-Enoshima Station" },
    "kiyotsu-gorge": { name: "Kiyotsu Gorge", description: "One of Japan's three great gorges. The mirror-water 'Panorama Station' at the tunnel's end is an unmissable art space.", bestSeason: "Apr–Nov", stayTime: "About 1.5 hours", access: "About 25 min by car from Echigo-Yuzawa Station" },
    "sado-island": { name: "Sado Island", description: "The largest island in the Sea of Japan, known for tub boats and the World Heritage gold mines. Wild coastal beauty like Senkaku Bay abounds.", bestSeason: "May–Oct", stayTime: "1 day or more", access: "About 2.5 hours by ferry from Niigata Port" },
    "tateyama-kurobe": { name: "Tateyama Kurobe Alpine Route", description: "A mountain sightseeing route crossing 3,000 m peaks by cable car and bus. Famous for the spring 'Snow Corridor' and Kurobe Dam's discharge.", bestSeason: "Apr–Nov", stayTime: "Full day", access: "By cable car and connections from Tateyama Station or Ogizawa" },
    "ainokura": { name: "Ainokura Village, Gokayama", description: "A World Heritage gassho-style village in the mountains, quieter and less touristy than Shirakawa-go.", bestSeason: "Year-round", stayTime: "About 1.5 hours", access: "About 25 min by car from Johana Station" },
    "kenrokuen": { name: "Kenrokuen Garden, Kanazawa", description: "One of Japan's three great gardens. Pair it with the Higashi Chaya district and seafood at Omicho Market.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 15 min by bus from Kanazawa Station" },
    "chirihama": { name: "Chirihama Nagisa Driveway", description: "Japan's only beach you can drive on — 8 km along the surf. At sunset it feels like a scene from a film.", bestSeason: "Apr–Nov", stayTime: "About 1 hour", access: "About 45 min by car from Kanazawa Station" },
    "tojinbo": { name: "Tojinbo Cliffs", description: "Columnar basalt cliffs carved by the rough Sea of Japan. The view of the rock walls and sunset from a sightseeing boat is superb.", bestSeason: "Year-round", stayTime: "About 1.5 hours", access: "About 40 min by bus from Awara-Onsen Station" },
    "eiheiji": { name: "Eiheiji Temple", description: "Head temple of Soto Zen founded by Dogen. Walking the corridors linking seven halls among ancient cedars calms the mind.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 30 min by bus from Fukui Station" },
    "kawaguchiko": { name: "Lake Kawaguchi", description: "A renowned viewpoint for Mt. Fuji. The upside-down Fuji reflected from lakeside hot-spring inns is exceptional.", bestSeason: "Year-round", stayTime: "Half a day", access: "Sightseeing bus from Kawaguchiko Station" },
    "oshino-hakkai": { name: "Oshino Hakkai", description: "Eight clear ponds fed by Mt. Fuji's underground springs, set in a thatched-roof village with water visible to the bottom.", bestSeason: "Year-round", stayTime: "About 1.5 hours", access: "About 20 min by bus from Fujisan Station" },
    "kamikochi": { name: "Kamikochi", description: "The Azusa River mirrors the Hotaka peaks by Kappa Bridge. A 1,500 m alpine resort, cool for walking even in summer.", bestSeason: "May–Oct", stayTime: "Half a day", access: "About 1.5 hours by bus from Matsumoto Station (private cars restricted)" },
    "matsumoto-castle": { name: "Matsumoto Castle", description: "A jet-black original keep against the Northern Alps. Enjoy the 'upside-down castle' in the moat and craft shops in town.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 15 min on foot from Matsumoto Station" },
    "shirakawago": { name: "Shirakawa-go", description: "The World Heritage gassho-style village. The view over the village from the observatory is picture-perfect in every season.", bestSeason: "Year-round", stayTime: "About 3 hours", access: "About 50 min by bus from Takayama" },
    "takayama": { name: "Hida Takayama Old Town", description: "A castle town of latticed merchant houses. Savor Hida beef sushi, morning markets and sake breweries in the 'Little Kyoto of Hida.'", bestSeason: "Year-round", stayTime: "About 3 hours", access: "About 10 min on foot from Takayama Station" },
    "atami-onsen": { name: "Atami Onsen", description: "A seaside spa town an easy trip from Tokyo. Popular for shopping-street snacks and fireworks over the sea.", bestSeason: "Year-round", stayTime: "Half day or overnight", access: "Right by Atami Station" },
    "miho-no-matsubara": { name: "Miho no Matsubara", description: "A World Heritage pine grove with Mt. Fuji beyond, straight out of an ukiyo-e print with white sand and Suruga Bay panoramas.", bestSeason: "Nov–Feb (clearest Fuji views)", stayTime: "About 1.5 hours", access: "About 25 min by bus from Shimizu Station" },
    "nagoya-castle": { name: "Nagoya Castle", description: "The Owari Tokugawa castle crowned with golden shachihoko. The restored Honmaru Palace's painted screens are a must-see; Kinshachi Yokocho serves local food.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "Right by Nagoyajo subway station" },
    "inuyama-castle": { name: "Inuyama Castle & Town", description: "A National Treasure keep overlooking the Kiso River, with a bustling castle town of street food below. The top floor offers a lord's-eye view.", bestSeason: "Year-round", stayTime: "About 3 hours", access: "About 20 min on foot from Inuyama Station" },
    "yahiko-shrine": { name: "Yahiko Shrine", description: "Echigo's foremost shrine with 2,400 years of history. The ropeway up Mt. Yahiko reveals a panorama of the plains and the Sea of Japan.", bestSeason: "Oct–Nov", stayTime: "About 2 hours", access: "About 15 min on foot from Yahiko Station" },
    "echigo-yuzawa": { name: "Echigo-Yuzawa Onsen", description: "The hot-spring town of Kawabata's novel 'Snow Country.' At the station's Ponshukan, sample sake from almost every brewery in Niigata.", bestSeason: "Dec–Mar", stayTime: "Half a day", access: "Right by Echigo-Yuzawa Station" },
    "kurobe-gorge": { name: "Kurobe Gorge Railway", description: "Ride an open-sided trolley train through Japan's deepest V-shaped gorge. The river below and blazing autumn colors are magnificent.", bestSeason: "Oct–Nov", stayTime: "Half a day", access: "Board at Unazuki Station, next to Unazuki-Onsen Station" },
    "amaharashi": { name: "Amaharashi Coast", description: "A miraculous view of the 3,000 m Tateyama range across Toyama Bay. On winter mornings, sea mist makes it otherworldly.", bestSeason: "Nov–Feb", stayTime: "About 1 hour", access: "About 5 min on foot from Amaharashi Station" },
    "higashi-chaya": { name: "Higashi Chaya District, Kanazawa", description: "Kanazawa's most atmospheric quarter of latticed teahouses. Gold-leaf ice cream and townhouse cafés make for great snacking.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 10 min by bus from Kanazawa Station" },
    "omicho-market": { name: "Omicho Market", description: "Kanazawa's kitchen with about 170 shops. Queues form early for crab, sweet shrimp, nodoguro and seafood bowls.", bestSeason: "Nov–Feb", stayTime: "About 1.5 hours", access: "About 15 min on foot from Kanazawa Station" },
    "wakura-onsen": { name: "Wakura Onsen", description: "A 1,200-year-old 'onsen of the sea' facing Nanao Bay, proud of its bath-hopping and Noto seafood.", bestSeason: "Year-round", stayTime: "Half a day", access: "About 5 min by car from Wakura-Onsen Station" },
    "mikatagoko": { name: "Mikata Five Lakes Rainbow Line", description: "A scenic drive where five lakes each show a different shade of blue. Take in the view from the summit park's footbath and terraces.", bestSeason: "Apr–Nov", stayTime: "About 2 hours", access: "About 15 min by car from Mikata Station" },
    "echizen-ono-castle": { name: "Echizen Ono Castle", description: "A 'castle in the sky' floating on a sea of clouds on autumn–winter mornings. The town below is famed for spring water and a 400-year-old market.", bestSeason: "Oct–Apr", stayTime: "About 2 hours", access: "About 30 min on foot from Echizen-Ono Station" },
    "arakurayama-sengen": { name: "Arakurayama Sengen Park", description: "The five-story pagoda, cherry blossoms and Mt. Fuji in one frame — one of Japan's most famous views abroad, 398 steps up.", bestSeason: "April", stayTime: "About 1.5 hours", access: "About 20 min on foot from Shimoyoshida Station" },
    "hottarakashi-onsen": { name: "Hottarakashi Onsen", description: "Open-air baths at 700 m overlooking the Kofu basin and Mt. Fuji. The morning bath opens an hour before sunrise.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 10 min by car from Yamanashishi Station" },
    "zenkoji": { name: "Zenkoji Temple", description: "A beloved non-sectarian temple — 'visit Zenkoji once in your life.' Braving the pitch-dark underground passage is a must.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 10 min by bus from Nagano Station" },
    "jigokudani-yaen": { name: "Jigokudani Monkey Park", description: "The only place in the world to watch wild 'snow monkeys' soaking in hot springs up close.", bestSeason: "Dec–Mar", stayTime: "About 2 hours", access: "About 1 hour by bus and on foot from Yudanaka Station" },
    "narai-juku": { name: "Narai-juku", description: "Japan's longest preserved post town on the Nakasendo, about 1 km. Stroll past lacquerware shops with gohei-mochi in hand.", bestSeason: "Apr–Nov", stayTime: "About 2 hours", access: "Right by Narai Station" },
    "gero-onsen": { name: "Gero Onsen", description: "One of Japan's three finest springs, the 'waters of beauty.' Free footbaths dot the town, and a spa pass lets you hop between baths.", bestSeason: "Year-round", stayTime: "Half a day", access: "Right by Gero Station" },
    "gujo-hachiman": { name: "Gujo Hachiman", description: "A 'water town' laced with canals. The Gujo Odori dance runs 32 nights each summer, peaking with all-night dancing at Obon.", bestSeason: "Jul–Aug", stayTime: "About 2 hours", access: "About 20 min on foot from Gujo-Hachiman Station" },
    "shuzenji-onsen": { name: "Shuzenji Onsen", description: "Izu's oldest spa. The bamboo path, vermilion Katsura Bridge and riverside Tokko-no-yu spring exude old-Japan charm.", bestSeason: "November", stayTime: "Half a day", access: "About 10 min by bus from Shuzenji Station" },
    "jogasaki": { name: "Jogasaki Coast", description: "A lava-formed coastline of sheer cliffs. The 23 m high Kadowaki suspension bridge is a thrill.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 35 min on foot from Izu-Kogen Station" },
    "atsuta-jingu": { name: "Atsuta Jingu Shrine", description: "A great shrine housing the sacred sword Kusanagi. The famed hitsumabushi eel restaurants by the gate pair well with a visit.", bestSeason: "Year-round", stayTime: "About 1.5 hours", access: "About 3 min on foot from Jingu-mae Station" },
    "osu": { name: "Osu Shopping District", description: "Some 1,200 shops before Osu Kannon temple — electronics, vintage clothes and street food in Nagoya's chaotic kitchen.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "Right by Osu-Kannon Station" },
    "ise-jingu": { name: "Ise Jingu Shrine", description: "Japan's most venerated shrine, affectionately called 'O-Ise-san.' After praying, head to Okage Yokocho for Ise udon and akafuku sweets.", bestSeason: "Year-round", stayTime: "About 3 hours", access: "About 6 min by bus from Isuzugawa Station" },
    "meoto-iwa": { name: "Meoto Iwa (Wedded Rocks)", description: "Two rocks bound by a great sacred rope, a site of matchmaking. From May to July the sun rises between them.", bestSeason: "May–Jul", stayTime: "About 1 hour", access: "About 15 min on foot from Futaminoura Station" },
    "hikone-castle": { name: "Hikone Castle", description: "A National Treasure keep overlooking Lake Biwa. Enjoy Genkyuen Garden's borrowed scenery and meet Hikonyan, the original castle mascot.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 15 min on foot from Hikone Station" },
    "shirahige-shrine": { name: "Shirahige Shrine", description: "A vermilion torii rising from Lake Biwa, the 'Itsukushima of Omi.' At dawn or under the moon it is breathtaking.", bestSeason: "Year-round", stayTime: "About 30 min", access: "About 5 min by car from Omi-Takashima Station" },
    "fushimi-inari": { name: "Fushimi Inari Taisha", description: "Thousands of vermilion torii winding to the summit — a sight found nowhere else. Aim for an early-morning visit.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "Right by JR Inari Station" },
    "arashiyama": { name: "Arashiyama", description: "Kyoto's famed scenic district of Togetsukyo Bridge and the bamboo grove. Enjoy the scenic railway and Hozugawa river boats too.", bestSeason: "November", stayTime: "Half a day", access: "Right by Arashiyama Station" },
    "kinkakuji": { name: "Kinkakuji (Golden Pavilion)", description: "The golden pavilion mirrored in Kyokochi Pond, a symbol of Kyoto. Snow-dusted mornings are a once-in-a-lifetime sight.", bestSeason: "Year-round", stayTime: "About 1 hour", access: "About 40 min by bus from Kyoto Station" },
    "nara-park": { name: "Nara Park & Todaiji", description: "The Great Buddha Hall and some 1,200 free-roaming deer. Kasuga Taisha and Kofukuji are within walking distance.", bestSeason: "Year-round", stayTime: "About 3 hours", access: "About 5 min on foot from Kintetsu-Nara Station" },
    "yoshinoyama": { name: "Mt. Yoshino", description: "Japan's finest cherry-blossom mountain, praised as 'a thousand trees at a glance' — 30,000 wild cherries bloom from base to summit.", bestSeason: "April", stayTime: "Half a day", access: "Ropeway from Yoshino Station" },
    "dotonbori": { name: "Dotonbori", description: "The neon heart of Minami under the Glico sign. Takoyaki, kushikatsu — the street of 'eat till you drop.'", bestSeason: "Year-round", stayTime: "About 3 hours", access: "About 5 min on foot from Namba Station" },
    "osaka-castle": { name: "Osaka Castle", description: "Hideyoshi's legendary castle with massive stone walls in a vast park — an urban oasis and famed cherry-blossom spot.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 15 min on foot from Osakajokoen Station" },
    "himeji-castle": { name: "Himeji Castle", description: "The White Heron Castle, Japan's first World Cultural Heritage site. The beauty of its original white-walled keep is in a class of its own.", bestSeason: "Year-round", stayTime: "About 2.5 hours", access: "About 20 min on foot from Himeji Station" },
    "kinosaki-onsen": { name: "Kinosaki Onsen", description: "Stroll the willow-lined canal in yukata and geta, hopping between seven public baths. In winter it's a mecca for snow crab.", bestSeason: "Nov–Mar", stayTime: "Overnight", access: "Right by Kinosaki-Onsen Station" },
    "shirahama": { name: "Nanki-Shirahama & Shirara Beach", description: "Kansai's favorite resort of white sand and blue sea, plus the ancient Shirahama springs and sunset at Engetsu Island.", bestSeason: "Jun–Sep", stayTime: "Half day or overnight", access: "About 15 min by bus from Shirahama Station" },
    "nachi-falls": { name: "Nachi Falls & Kumano Nachi Taisha", description: "Japan's tallest waterfall (133 m) beside a vermilion pagoda — a sacred site of Kumano worship. Approach on foot up the Daimonzaka stone path.", bestSeason: "Year-round", stayTime: "About 3 hours", access: "About 30 min by bus from Kii-Katsuura Station" },
    "okage-yokocho": { name: "Okage Yokocho", description: "A recreated Edo–Meiji townscape at the gates of Ise Jingu. Akafuku's main shop, Ise udon — a street-food paradise.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 15 min by bus from Iseshi Station" },
    "enryakuji": { name: "Enryakuji, Mt. Hiei", description: "Head temple of Tendai Buddhism founded by Saicho, where the 'Eternal Dharma Light' has burned for 1,200 years across a World Heritage mountain.", bestSeason: "Oct–Nov", stayTime: "Half a day", access: "About 1 hour from Kyoto Station by train and cable car" },
    "kiyomizudera": { name: "Kiyomizudera Temple", description: "The World Heritage 'stage of Kiyomizu' overlooking Kyoto. Walking the Ninenzaka and Sannenzaka lanes is half the pleasure.", bestSeason: "Apr & Nov", stayTime: "About 2 hours", access: "About 25 min from Kyoto Station by bus and on foot" },
    "gion": { name: "Gion & Hanamikoji", description: "A stone-paved geisha quarter of teahouses. At dusk you may glimpse a maiko on her way.", bestSeason: "Year-round", stayTime: "About 1.5 hours", access: "About 5 min on foot from Gion-Shijo Station" },
    "nishiki-market": { name: "Nishiki Market", description: "'Kyoto's kitchen' with 400 years of history — about 130 shops of pickles, yuba and soy-milk doughnuts to graze through.", bestSeason: "Year-round", stayTime: "About 1.5 hours", access: "About 3 min on foot from Karasuma Station" },
    "amanohashidate": { name: "Amanohashidate", description: "One of Japan's three most scenic views, a 3.6 km sandbar. Viewed upside-down from the lookout, it becomes a bridge to heaven.", bestSeason: "Year-round", stayTime: "Half a day", access: "Right by Amanohashidate Station" },
    "ine-funaya": { name: "Ine Boathouses", description: "A fishing village of some 230 funaya boathouses standing over the water — from a sea taxi it looks like a floating town.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 1 hour by bus from Amanohashidate Station" },
    "horyuji": { name: "Horyuji Temple", description: "The world's oldest surviving wooden buildings. The five-story pagoda and Kudara Kannon bring textbook Asuka history to life.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 20 min on foot from Horyuji Station" },
    "hasedera": { name: "Hasedera Temple", description: "The 'temple of flowers,' reached by a 399-step covered stairway. Peonies, hydrangeas and autumn leaves bury the mountainside in bloom.", bestSeason: "Apr–Jun", stayTime: "About 2 hours", access: "About 15 min on foot from Hasedera Station" },
    "asuka": { name: "Asuka Village", description: "Ishibutai and Takamatsuzuka burial mounds dot the countryside in this primal Japanese landscape. Tour the Asuka era by rental bicycle.", bestSeason: "Mar–May & Sep–Nov", stayTime: "Half a day", access: "By bicycle from Asuka Station" },
    "shinsekai": { name: "Shinsekai & Tsutenkaku", description: "Kushikatsu, doteyaki and gaudy signboards around Tsutenkaku Tower — Osaka's deep retro zone in full Showa flavor.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 3 min on foot from Ebisucho Station" },
    "minoo-falls": { name: "Minoo Falls", description: "A 33 m waterfall just 30 minutes by train from central Osaka. Autumn brings blazing foliage and the famous fried maple leaves.", bestSeason: "November", stayTime: "About 2 hours", access: "About 40 min on foot from Minoo Station" },
    "arima-onsen": { name: "Arima Onsen", description: "One of Japan's three oldest springs, beloved by Hideyoshi. Bathe in the iron-red 'golden' and clear 'silver' waters.", bestSeason: "Year-round", stayTime: "Half a day", access: "About 5 min on foot from Arima-Onsen Station" },
    "takeda-castle": { name: "Takeda Castle Ruins", description: "The 'castle in the sky' floating above a sea of clouds on autumn mornings. The silhouette of its walls from Ritsuunkyo across the valley is stunning.", bestSeason: "Sep–Nov", stayTime: "About 2 hours", access: "About 20 min by Tenku Bus from Takeda Station" },
    "koyasan": { name: "Koyasan (Mt. Koya)", description: "Kukai's monastic city at 800 m. Cedar groves of Okunoin, temple-lodging cuisine and morning prayers restore the spirit.", bestSeason: "May–Nov", stayTime: "Full day", access: "About 5 min by cable car from Gokurakubashi Station" },
    "kumano-kodo": { name: "Kumano Kodo Daimonzaka", description: "A mossy stone path beneath 800-year-old cedars on the pilgrimage route. Walk the sacred 2.5 km from Daimonzaka to Nachi Falls.", bestSeason: "Mar–May & Oct–Nov", stayTime: "About 2 hours", access: "About 20 min by bus from Kii-Katsuura Station" },
    "tottori-sakyu": { name: "Tottori Sand Dunes", description: "Japan's largest dunes. Try camel rides and sandboarding, and don't miss the adjacent Sand Museum.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 20 min by bus from Tottori Station" },
    "mizuki-shigeru-road": { name: "Mizuki Shigeru Road", description: "A shopping street in Sakaiminato lined with 177 bronze yokai statues. At night, spirit silhouettes glow on the pavement.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "Right by Sakaiminato Station" },
    "izumo-taisha": { name: "Izumo Taisha", description: "The ancient shrine of matchmaking, famed for its colossal sacred straw rope. Izumo soba in the temple town is a specialty.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 25 min by bus from Izumoshi Station" },
    "adachi-museum": { name: "Adachi Museum of Art", description: "Its 'living Japanese painting' garden has repeatedly ranked first in Japan; the Yokoyama Taikan collection is a must-see.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 20 min by free shuttle from Yasugi Station" },
    "kurashiki": { name: "Kurashiki Bikan Quarter", description: "White-walled storehouses and willows along a canal. Enjoy boat rides and a stroll down Denim Street.", bestSeason: "Year-round", stayTime: "About 3 hours", access: "About 15 min on foot from Kurashiki Station" },
    "korakuen": { name: "Korakuen Garden, Okayama", description: "One of Japan's three great gardens, borrowing Okayama Castle as scenery. Its open lawns and winding streams feel unlike any other.", bestSeason: "Year-round", stayTime: "About 1.5 hours", access: "About 15 min by bus from Okayama Station" },
    "itsukushima": { name: "Itsukushima Shrine", description: "The World Heritage shrine with its great torii in the sea; at low tide you can walk right up to it. Try Miyajima's anago rice and momiji manju.", bestSeason: "Year-round", stayTime: "About 3 hours", access: "About 10 min by ferry from Miyajimaguchi" },
    "genbaku-dome": { name: "Atomic Bomb Dome & Peace Park", description: "A World Heritage site conveying the horror of nuclear war. Visit with the museum and offer a quiet prayer for peace.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 15 min by tram from Hiroshima Station" },
    "onomichi": { name: "Onomichi", description: "A town of slopes, cats and temples. Views over the strait from Senkoji, alley wandering and Onomichi ramen fill a day.", bestSeason: "Year-round", stayTime: "Half a day", access: "Right by Onomichi Station" },
    "tsunoshima-bridge": { name: "Tsunoshima Bridge", description: "A 1,780 m bridge running straight over emerald water — a classic scenic drive.", bestSeason: "May–Sep", stayTime: "About 1 hour", access: "About 1 hour by car from Shin-Shimonoseki Station" },
    "kintaikyo": { name: "Kintaikyo Bridge", description: "A five-arch wooden bridge over the Nishiki River, one of Japan's three finest. Especially picturesque in cherry-blossom and cormorant-fishing seasons.", bestSeason: "Apr & Jun–Aug", stayTime: "About 1.5 hours", access: "About 20 min by bus from Iwakuni Station" },
    "motonosumi-shrine": { name: "Motonosumi Shrine", description: "123 vermilion torii cascade toward the sea. Try tossing a coin into Japan's hardest offertory box, atop a torii.", bestSeason: "Year-round", stayTime: "About 1 hour", access: "About 20 min by car from Nagatoshi Station" },
    "misasa-onsen": { name: "Misasa Onsen", description: "One of the world's finest radon springs. Bathe in the riverside rotenburo to the murmur of the Mitoku River, then stroll the retro main street.", bestSeason: "Year-round", stayTime: "Half a day", access: "About 25 min by bus from Kurayoshi Station" },
    "matsue-castle": { name: "Matsue Castle", description: "One of only twelve original keeps, and a National Treasure. The castle town seen from a moat-cruise boat brims with atmosphere.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 10 min by bus from Matsue Station" },
    "tamatsukuri-onsen": { name: "Tamatsukuri Onsen", description: "Beautifying waters mentioned in the 8th-century Izumo Fudoki. Magatama bridges and footbaths line the Tamayu River, lantern-lit at night.", bestSeason: "Year-round", stayTime: "Half a day", access: "About 5 min by car from Tamatsukuri-Onsen Station" },
    "bitchu-matsuyama-castle": { name: "Bitchu Matsuyama Castle", description: "At 430 m, the highest original castle keep in Japan. On autumn mornings, catch it floating on a sea of clouds from the viewpoint.", bestSeason: "Sep–Apr", stayTime: "About 2 hours", access: "About 30 min from Bitchu-Takahashi Station by shared taxi and on foot" },
    "okunoshima": { name: "Okunoshima (Rabbit Island)", description: "Around 500 wild rabbits roam this small island. Fifteen minutes by ferry; cycling around takes about an hour.", bestSeason: "Year-round", stayTime: "Half a day", access: "About 15 min by ferry from Tadanoumi Port" },
    "saijo-sakagura": { name: "Saijo Sake Breweries, Higashihiroshima", description: "Red-brick chimneys and white-walled breweries in one of Japan's three great sake towns. Tour seven breweries with tastings.", bestSeason: "October", stayTime: "About 2 hours", access: "About 5 min on foot from Saijo Station" },
    "akiyoshido": { name: "Akiyoshido Cave & Akiyoshidai", description: "Japan's largest karst plateau and the vast limestone cave beneath it. The Hyakumaizara terraces and Golden Pillar are must-sees.", bestSeason: "Year-round", stayTime: "Half a day", access: "About 40 min by bus from Shin-Yamaguchi Station" },
    "hagi": { name: "Hagi Castle Town", description: "The castle town that raised Yoshida Shoin and the Meiji Restoration loyalists. Cycle past summer-orange earthen walls and samurai houses.", bestSeason: "Year-round", stayTime: "Half a day", access: "About 10 min by bicycle from Higashi-Hagi Station" },
    "iya-kazurabashi": { name: "Iya Kazurabashi Vine Bridge", description: "A suspension bridge woven from mountain vines over a deep gorge. The view of the ravine through the gaps underfoot is thrilling.", bestSeason: "Apr–Nov", stayTime: "About 1 hour", access: "About 20 min by car from Oboke Station" },
    "naruto-whirlpools": { name: "Naruto Whirlpools", description: "Some of the world's largest whirlpools. Get close by sightseeing boat, or look straight down through the glass floor of the Uzunomichi walkway.", bestSeason: "Spring & autumn spring tides", stayTime: "About 2 hours", access: "About 20 min by bus from Naruto Station" },
    "kotohiragu": { name: "Kotohiragu Shrine", description: "Affectionately 'Konpira-san' — the main shrine sits atop 785 stone steps. Sanuki udon along the approach is essential.", bestSeason: "Year-round", stayTime: "About 3 hours", access: "On foot from Kotohira Station, then 785 steps" },
    "chichibugahama": { name: "Chichibugahama Beach", description: "At low-tide dusk, tide pools become mirrors — 'Japan's Uyuni Salt Flats,' a spectacular sunset photo spot.", bestSeason: "Year-round", stayTime: "About 1.5 hours", access: "About 10 min by car from Takuma Station" },
    "dogo-onsen": { name: "Dogo Onsen", description: "Among Japan's oldest baths. Soak in the Important Cultural Property main hall, then stroll the arcade in yukata.", bestSeason: "Year-round", stayTime: "Half day or overnight", access: "Right by Dogo-Onsen Station" },
    "shimanami-kaido": { name: "Shimanami Kaido", description: "A cyclists' holy land of bridges linking the Seto Inland Sea islands. The panorama from Kirosan Observatory is overwhelming.", bestSeason: "Mar–Nov", stayTime: "Half to full day", access: "Rental cycles from Imabari or Onomichi Station" },
    "shimanto-river": { name: "Shimanto River", description: "'Japan's last clear stream.' Drift past railing-less chinkabashi bridges on a houseboat and let time slow down.", bestSeason: "May–Oct", stayTime: "Half a day", access: "About 15 min by car from Nakamura Station (Sada Bridge)" },
    "katsurahama": { name: "Katsurahama Beach", description: "A bow-shaped beach where Sakamoto Ryoma's statue gazes at the Pacific. Famed for moon-viewing; pair with katsuo tataki at Hirome Market.", bestSeason: "Year-round", stayTime: "About 1.5 hours", access: "About 40 min by bus from Kochi Station" },
    "oboke-koboke": { name: "Oboke & Koboke Gorges", description: "A gorge carved by the Yoshino River over 200 million years. See the emerald rapids and strange rocks up close by cruise boat or raft.", bestSeason: "Apr–Nov", stayTime: "About 2 hours", access: "About 20 min on foot from Oboke Station" },
    "awaodori-kaikan": { name: "Awa Odori Kaikan", description: "Experience the 400-year-old Awa Dance year-round. Join the resident troupe's performance and become one of the 'dancing fools.'", bestSeason: "Year-round", stayTime: "About 1.5 hours", access: "About 10 min on foot from Tokushima Station" },
    "ritsurin": { name: "Ritsurin Garden", description: "The pinnacle of daimyo gardens, 'a new view with every step.' The vista over Engetsukyo Bridge from Hiraiho Hill is superb.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 3 min on foot from Ritsurin-Koen-Kitaguchi Station" },
    "naoshima": { name: "Naoshima", description: "An island of contemporary art dotted with Kusama's pumpkin and Ando Tadao architecture. Tour the art by bicycle from the port.", bestSeason: "Mar–Nov", stayTime: "Full day", access: "About 50 min by ferry from Takamatsu Port" },
    "matsuyama-castle": { name: "Matsuyama Castle", description: "One of the twelve original keeps. From the main bailey, reached by chairlift, the city and the Seto Inland Sea spread below.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 15 min from Okaido tram stop by foot and lift" },
    "uchiko": { name: "Uchiko Old Town", description: "White-walled merchant houses from the wax-trade era line the Yokaichi quarter. The working Uchikoza playhouse welcomes visitors.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 10 min on foot from Uchiko Station" },
    "hirome-ichiba": { name: "Hirome Market, Kochi", description: "Straw-seared katsuo tataki with a drink from midday — some 60 stalls make this Kochi's living room.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 2 min on foot from Kochijo-mae tram stop" },
    "nikobuchi": { name: "Nikobuchi", description: "The plunge pool that made 'Niyodo Blue' famous. Around noon on clear days the water glows its deepest blue.", bestSeason: "Year-round", stayTime: "About 1 hour", access: "About 40 min by car from Ino Station" },
    "nakasu-yatai": { name: "Nakasu Yatai Street, Fukuoka", description: "Riverside food stalls, the icon of Hakata nights. Hop between tonkotsu ramen, yaki-ramen and gyoza.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 5 min on foot from Nakasu-Kawabata Station" },
    "dazaifu-tenmangu": { name: "Dazaifu Tenmangu", description: "Head shrine of Tenmangu shrines, dedicated to the deity of learning. Fresh-grilled umegae-mochi on the approach is unmissable.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 5 min on foot from Dazaifu Station" },
    "mifuneyama-rakuen": { name: "Mifuneyama Rakuen", description: "A grand Takeo garden set against a cliff. 200,000 azaleas in spring, and teamLab's light art in summer, transform it into a dreamscape.", bestSeason: "Apr–May & Jul–Oct", stayTime: "About 2 hours", access: "About 5 min by car from Takeo-Onsen Station" },
    "yutoku-inari": { name: "Yutoku Inari Shrine", description: "One of Japan's three great Inari shrines, called the 'Nikko of the West.' Its vermilion main hall juts from the cliff on wooden stilts.", bestSeason: "Year-round", stayTime: "About 1.5 hours", access: "About 10 min by bus from Hizen-Kashima Station" },
    "inasayama": { name: "Mt. Inasa Night View", description: "Lights shimmer across the bowl-shaped city — one of the world's new three great night views, five minutes up by ropeway.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 20 min from Nagasaki Station by car and ropeway" },
    "gunkanjima": { name: "Gunkanjima (Hashima)", description: "A ruined coal-mining island at sea, once the world's most densely populated place. Landing tours visit the World Heritage site.", bestSeason: "Apr–Oct", stayTime: "Half day (tour)", access: "About 40 min by tour boat from Nagasaki Port" },
    "aso-daikanbo": { name: "Aso Daikanbo", description: "Sweeping views over one of the world's great calderas and its grasslands. Pair the panorama with a local akaushi beef bowl.", bestSeason: "Apr–Nov", stayTime: "About 1 hour", access: "About 30 min by car from Aso Station" },
    "kurokawa-onsen": { name: "Kurokawa Onsen", description: "Ryokan huddle in a mountain hollow. A three-stamp 'bathing pass' lets you hop between open-air baths at inns of your choice.", bestSeason: "Year-round", stayTime: "Half day or overnight", access: "About 50 min by bus from Aso Station" },
    "yufuin-onsen": { name: "Yufuin Onsen", description: "A popular spa town beneath Mt. Yufu. Graze along Yunotsubo Street and catch Lake Kinrin wrapped in morning mist.", bestSeason: "Year-round", stayTime: "Half day or overnight", access: "About 15 min on foot from Yufuin Station (Lake Kinrin)" },
    "beppu-jigoku": { name: "Beppu Hell Tour", description: "Tour seven 'hells' from the cobalt Sea Hell to the crimson Blood Pond Hell. Beppu boasts Japan's greatest hot-spring output.", bestSeason: "Year-round", stayTime: "About 3 hours", access: "About 15 min by bus from Beppu Station" },
    "takachiho-gorge": { name: "Takachiho Gorge", description: "Manai Falls pours between columnar basalt cliffs in this mystical gorge. Rowboats take you right up to the falls.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 1 hour by car from Nobeoka Station" },
    "aoshima": { name: "Aoshima", description: "A subtropical islet ringed by the wave-cut 'Devil's Washboard.' Palm rows and Aoshima Shrine exude southern-island mood.", bestSeason: "Year-round", stayTime: "About 1.5 hours", access: "About 10 min on foot from Aoshima Station" },
    "yakushima": { name: "Yakushima", description: "A World Natural Heritage island of ancient cedars and mossy forests. Trekking Shiratani Unsuikyo ravine is a favorite.", bestSeason: "Mar–Nov", stayTime: "1 day or more", access: "About 2–3 hours by jetfoil from Kagoshima Port" },
    "sakurajima": { name: "Sakurajima", description: "Kagoshima's symbol, still puffing smoke. Just 15 minutes by ferry; soak your feet at the lava-shore footbath beneath the mighty volcano.", bestSeason: "Year-round", stayTime: "About 3 hours", access: "About 15 min by ferry from Kagoshima Port" },
    "churaumi": { name: "Okinawa Churaumi Aquarium", description: "Whale sharks glide through the colossal 'Kuroshio Sea' tank. Explore Ocean Expo Park and Emerald Beach nearby.", bestSeason: "Year-round", stayTime: "About 3 hours", access: "About 2 hours by car from Naha Airport" },
    "kouri-island": { name: "Kouri Island", description: "Cross the Kouri Bridge straight over crystal water to the 'island of love.' Heart Rock and scenic cafés await.", bestSeason: "Apr–Oct", stayTime: "About 2 hours", access: "About 1.5 hours by car from Naha Airport" },
    "taketomi-island": { name: "Taketomi Island", description: "A Yaeyama isle of red-tiled houses and white-sand lanes. Tour the village by water-buffalo cart and wade the shallows of Kondoi Beach.", bestSeason: "Year-round", stayTime: "Half a day", access: "About 15 min by ferry from Ishigaki Port" },
    "yanagawa": { name: "Yanagawa Canal Cruise", description: "Drift down the castle moats on a donko boat. Finish the Yanagawa way, with steamed eel seiro-mushi.", bestSeason: "Year-round", stayTime: "Half a day", access: "About 8 min on foot from Nishitetsu-Yanagawa Station" },
    "itoshima": { name: "Itoshima & Sakurai Futamigaura", description: "A white torii and wedded rocks against the sunset. Seaside cafés and winter oyster huts make it Fukuoka's favorite day drive.", bestSeason: "Apr–Oct", stayTime: "Half a day", access: "About 20 min by car from Chikuzen-Maebaru Station" },
    "yobuko": { name: "Yobuko Morning Market", description: "One of Japan's three great morning markets. The famed live squid sashimi is translucent, with the legs returning as tempura.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 30 min by bus from Karatsu Station" },
    "unzen-jigoku": { name: "Unzen Hells", description: "Sulfurous steam vents on the 'hell walk' at Unzen Onsen, part of Japan's first national park. Try the onsen-steamed eggs.", bestSeason: "Year-round", stayTime: "Half a day", access: "About 1 hr 20 min by bus from Isahaya Station" },
    "kujukushima": { name: "Kujukushima Islands", description: "208 islands scatter across a ria coast off Sasebo. Famous for cruises and the sunset from Tenkaiho lookout.", bestSeason: "Year-round", stayTime: "Half a day", access: "About 25 min by bus from Sasebo Station" },
    "kumamoto-castle": { name: "Kumamoto Castle", description: "A great castle famed for its 'musha-gaeshi' curved walls. Restoration from the earthquake continues, viewable from a special walkway.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 15 min by tram from Kumamoto Station" },
    "amakusa-sakitsu": { name: "Sakitsu Village, Amakusa", description: "A church spire rises over a fishing village in this World Heritage hidden-Christian settlement. Wander the seaside village of prayer.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 30 min by car from Hondo Bus Center" },
    "kokonoe-yume-bridge": { name: "Kokonoe 'Yume' Suspension Bridge", description: "Japan's highest pedestrian suspension bridge at 173 m, overlooking Shindo Falls and the vast forests of Kyusuikei.", bestSeason: "Oct–Nov", stayTime: "About 1 hour", access: "About 20 min by bus from Bungo-Nakamura Station" },
    "usa-jingu": { name: "Usa Jingu", description: "Head shrine of Japan's 40,000 Hachiman shrines. The vermilion main hall is a National Treasure, wrapped in the pure air of an ancient forest.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 10 min by bus from Usa Station" },
    "udo-jingu": { name: "Udo Jingu", description: "A shrine set inside a cliffside cave facing the Pacific. Toss a lucky ball into the hollow of the turtle rock for good fortune.", bestSeason: "Year-round", stayTime: "About 1.5 hours", access: "About 1.5 hours by bus from Miyazaki Station" },
    "ebino-kogen": { name: "Ebino Plateau", description: "A 1,200 m plateau cradled by the Kirishima peaks. Climb Mt. Karakuni or walk the pond loop; autumn turns the pampas fields gold.", bestSeason: "May–Nov", stayTime: "Half a day", access: "About 30 min by car from Kobayashi Station" },
    "kirishima-jingu": { name: "Kirishima Jingu", description: "A vermilion shrine at the mythic site of the gods' descent. An 800-year-old sacred tree and mossy approach evoke the age of legends.", bestSeason: "Year-round", stayTime: "About 1.5 hours", access: "About 10 min by bus from Kirishima-Jingu Station" },
    "ibusuki-onsen": { name: "Ibusuki Onsen", description: "A rare natural sand bath by the shore. Buried in warm sand in a yukata, you'll be sweating within ten minutes.", bestSeason: "Year-round", stayTime: "Half a day", access: "About 20 min on foot from Ibusuki Station" },
    "amami-oshima": { name: "Amami Oshima", description: "Primeval subtropical forest at Kinsakubaru and the crystal waters of Tomori Beach — a World Natural Heritage island, home of the Amami rabbit.", bestSeason: "Apr–Oct", stayTime: "1 day or more", access: "By car from Amami Airport" },
    "shurijo": { name: "Shuri Castle", description: "The royal castle of the Ryukyu Kingdom. Restoration of the main hall after the 2019 fire is open to view as 'visible reconstruction.'", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 15 min on foot from Shuri monorail station" },
    "kokusai-dori": { name: "Kokusai Street", description: "Naha's 1.6 km main street — steak, Blue Seal ice cream, and Makishi Public Market down the side arcades.", bestSeason: "Year-round", stayTime: "About 3 hours", access: "About 3 min on foot from Kencho-mae monorail station" },
    "manzamo": { name: "Cape Manzamo", description: "An elephant-trunk cliff praised as 'a meadow for ten thousand people,' famed for sunsets over the East China Sea.", bestSeason: "Year-round", stayTime: "About 1 hour", access: "About 1 hour by car from Naha Airport" },
    "kabira-bay": { name: "Kabira Bay, Ishigaki", description: "A Michelin three-star bay of white sand and emerald gradients. Peer at coral reefs from a glass-bottom boat.", bestSeason: "Year-round", stayTime: "About 2 hours", access: "About 30 min by car from Ishigaki Port" },
  },
  courses: {
    "kanazawa-hida-2n3d": {
      title: "Kanazawa, Shirakawa-go & Hida Takayama, 3 days",
      summary: "Arrive in Kanazawa by shinkansen, pass the World Heritage thatched villages, and finish in Hida's castle town. Kaga culture and mountain scenery in one classic route.",
      notes: [
        ["Kenrokuen and Higashi Chaya in the morning; seafood lunch at Omicho Market", "Drive the beach at sunset; overnight in Kanazawa"],
        ["Reach the observatory before noon, then wander the village", "Stop by on the way — a quiet gassho village to yourself; overnight in Takayama"],
        ["Miyagawa morning market to the old town; finish with Hida beef sushi"],
      ],
    },
    "kyoto-nara-2n3d": {
      title: "Kyoto & Nara Classics, 3 days",
      summary: "Thousand torii gates, the Golden Pavilion, Arashiyama's bamboo, then Nara's Great Buddha and deer. The fail-safe first Kansai trip, good in any season.",
      notes: [
        ["First thing in the morning to beat the crowds"],
        ["The Golden Pavilion just after opening", "Togetsukyo Bridge and the bamboo grove, with a riverside café break"],
        ["Kintetsu line to Nara — the Great Buddha and deer crackers"],
      ],
    },
    "hokkaido-2n3d": {
      title: "Sapporo, Otaru & Noboribetsu, 3 days",
      summary: "Seafood, a retro port town and the famed baths of Hell Valley — first-time Hokkaido in one compact course. Snowscapes in winter, crisp air in summer.",
      notes: [
        ["Seafood bowl on arrival, then a stroll in Odori Park; overnight in Sapporo"],
        ["JR to Otaru — glass studios, sushi, and the canal at dusk"],
        ["Walk Jigokudani, then a final soak in the famous waters"],
      ],
    },
    "setouchi-2n3d": {
      title: "Hiroshima, Shimanami & Dogo, 3 days",
      summary: "From Miyajima's great torii to Onomichi's slopes, island-hopping by bicycle, then one of Japan's oldest baths. Three days bathed in Seto Inland light.",
      notes: [
        ["A prayer at the Peace Memorial Park", "Ferry to Miyajima — see the torii at both low and high tide; overnight in Hiroshima"],
        ["The view from Senkoji and Onomichi ramen", "Cycle across the islands; Kirosan sunset is a must; overnight in Imabari"],
        ["On to Matsuyama for the main bathhouse and the arcade"],
      ],
    },
    "kyushu-onsen-2n3d": {
      title: "Kyushu Hot Springs & Nature, 3 days",
      summary: "Beppu's hells, Yufuin's morning mist, Kurokawa's rotenburo, Aso's grasslands and Takachiho's mythic gorge — a rich traverse of the land of steam and fire.",
      notes: [
        ["Focus on the Sea Hell and Blood Pond Hell", "Yunotsubo Street and Lake Kinrin at dusk; overnight in Yufuin"],
        ["Open-air bath hopping with the wooden pass", "Overlook the caldera and lunch on akaushi beef; overnight in Aso"],
        ["Rowboat to Manai Falls"],
      ],
    },
    "tohoku-2n3d": {
      title: "Michinoku Charm, 3 days",
      summary: "Matsushima of the Three Views, Yamadera's stone steps, Taisho-era Ginzan Onsen and samurai Kakunodate — a serene northern journey by shinkansen.",
      notes: [
        ["Bay cruise and oyster lunch; overnight in Sendai"],
        ["Take on the 1,015 steps in the morning", "To the gas-lit spa town at dusk; overnight in Ginzan Onsen"],
        ["Shinkansen to Kakunodate — stroll the samurai street in kimono"],
      ],
    },
    "fuji-hakone-1n2d": {
      title: "Around Mt. Fuji, 2 days",
      summary: "Kawaguchiko's mirrored Fuji, Oshino's springs, pirate ships on Lake Ashi and Atami's baths — a weekend loop admiring Fuji from every side.",
      notes: [
        ["The Fuji-and-lake panorama from Oishi Park", "Stroll the spring-water village; overnight at Kawaguchiko Onsen"],
        ["Pirate ship and the lake torii of Hakone Shrine", "Finish with baths and street food in Atami"],
      ],
    },
    "okinawa-3n4d": {
      title: "Okinawa Main Island & Yaeyama, 4 days",
      summary: "Meet the whale sharks, cross the Kouri blue, then fly to Yaeyama for red-tiled lanes and shallow seas — the luxury of doing nothing at all.",
      notes: [
        ["Time your visit for the afternoon feeding; overnight in Motobu"],
        ["Cross Kouri Bridge to a scenic café; evening flight to Ishigaki"],
        ["Water-buffalo cart and Kondoi Beach island time; overnight on Ishigaki"],
        ["One last quiet morning walk in the village before heading home"],
      ],
    },
    "sanin-2n3d": {
      title: "San'in: Izumo, Matsue & Tottori, 3 days",
      summary: "From matchmaking Izumo Taisha to National Treasure Matsue Castle, skin-beautifying Tamatsukuri and radon-rich Misasa, ending at the Tottori dunes. Myth and hot springs along the San'in road.",
      notes: [
        ["Pray with two bows, four claps, one bow; soba by the gate", "Beautifying waters and riverside footbaths; overnight in Tamatsukuri"],
        ["The National Treasure keep and a moat cruise", "Linger over the picture-frame garden", "On to the retro spa town; overnight in Misasa"],
        ["The dunes are most beautiful with morning wind ripples"],
      ],
    },
    "hokuriku-2n3d": {
      title: "Hokuriku Loop: Kanazawa, Noto & Fukui, 3 days",
      summary: "Omicho seafood and the Higashi Chaya quarter, a drive along Chirihama beach, the sea-baths of Wakura, then Eiheiji's silence and the Tojinbo cliffs — Hokuriku in one stroke.",
      notes: [
        ["Seafood bowl lunch at the market", "An afternoon kimono stroll in the teahouse quarter; overnight in Kanazawa"],
        ["Drive along the surf by rental car", "Sea-view hot springs on Nanao Bay; overnight in Wakura"],
        ["Zazen among the cedars and seven halls", "End the trip on the cliffs at sunset"],
      ],
    },
    "shikoku-3n4d": {
      title: "Around Shikoku, 4 days",
      summary: "Konpira pilgrimage, Naruto whirlpools, the hidden Iya Valley and Dogo's waters. Udon, katsuo and Awa Odori — the best of Shikoku in one loop.",
      notes: [
        ["Arrive in Takamatsu and stroll the famed garden; sanuki udon for lunch", "Climb the 785 steps to Konpira-san; overnight in Kotohira"],
        ["Check the tide tables, then onto the Uzunomichi walkway", "Dance along at the evening show; overnight in Tokushima"],
        ["Gorge views from the cruise boat", "Brave the vine bridge; overnight in Iya"],
        ["On to Matsuyama and the chairlift to the keep", "End with a 3,000-year-old bath"],
      ],
    },
    "furano-biei-1n2d": {
      title: "Asahikawa, Biei & Furano, 2 days",
      summary: "From Asahiyama Zoo's famous exhibits to the Blue Pond and lavender fields — a weekend distillation of Hokkaido summer. Rental car recommended.",
      notes: [
        ["Catch the popular feeding time in the morning", "Afternoon light makes the pond bluest; overnight in Biei"],
        ["Lavender fields first thing, then finish with melon"],
      ],
    },
    "minami-kyushu-2n3d": {
      title: "Southern Kyushu: Sakurajima, Ibusuki, Kirishima & Nichinan, 3 days",
      summary: "A smoking volcano, burial in warm sand, the mythic Kirishima Jingu and cliffside Udo Jingu — volcanoes, legends and hot springs at Kyushu's southern tip.",
      notes: [
        ["Ferry across and up to the Yunohira lookout", "Sweat it out in an evening sand bath; overnight in Ibusuki"],
        ["Forest bathing at the vermilion shrine", "Walk the pond loop; overnight in Kirishima"],
        ["The cave shrine and lucky-ball toss", "Drive the Nichinan coast past the Devil's Washboard"],
      ],
    },
  },
};
