// 国内旅行おすすめスポットのデータ(全47都道府県、各2件以上)。
// region は8地方区分: 北海道 / 東北 / 関東 / 中部 / 近畿 / 中国 / 四国 / 九州・沖縄
// categories は固定セット: 絶景 / 温泉 / グルメ / 歴史 / 自然 / 街歩き(複数可)
// nearby には近くの(おおむね車で1時間以内の)スポットの id を入れる。
// photo は Wikimedia Commons のファイル名とクレジット。scripts の収集スクリプトが自動で埋める。
const SPOTS = [
  // ---- 北海道 ----
  {
    id: "biei-blue-pond", name: "美瑛・青い池", region: "北海道", prefecture: "北海道",
    categories: ["絶景", "自然"],
    description: "パッチワークのような丘陵風景と、神秘的なコバルトブルーの池。夏はラベンダーも楽しめる。",
    bestSeason: "6〜8月", stayTime: "約1時間", access: "旭川空港から車で約40分",
    nearby: ["asahiyama-zoo", "furano-farm-tomita"], mapQuery: "美瑛町 青い池",
    photo: { file: "Blue pond in Biei - 青い池（美瑛町） - panoramio.jpg", author: "taku-k", license: "CC BY 3.0" },
  },
  {
    id: "hakodateyama", name: "函館山", region: "北海道", prefecture: "北海道",
    categories: ["絶景", "街歩き"],
    description: "「世界三大夜景」とも称される扇形の夜景。ロープウェイで山頂まで約3分。麓の元町エリアの散策も楽しい。",
    bestSeason: "通年", stayTime: "約2時間", access: "函館駅から市電+ロープウェイで約30分",
    nearby: ["hakodate-asaichi"], mapQuery: "函館山展望台",
    photo: { file: "函館山展望台20231201-IMG 8749.jpg", author: "くろふね", license: "CC BY 4.0" },
  },
  {
    id: "otaru-canal", name: "小樽運河", region: "北海道", prefecture: "北海道",
    categories: ["街歩き", "グルメ"],
    description: "石造倉庫が並ぶレトロな運河沿いの街。ガス灯が灯る夕暮れが美しい。寿司や海鮮丼の名店も多い。",
    bestSeason: "通年", stayTime: "約3時間", access: "札幌駅からJRで約35分",
    nearby: ["sapporo-nijo-market", "cape-kamui"], mapQuery: "小樽運河",
    photo: { file: "Otaru Canal HDR1.jpg", author: "Tan Wei Liang Byorn", license: "CC BY-SA 4.0" },
  },
  {
    id: "shiretoko", name: "知床", region: "北海道", prefecture: "北海道",
    categories: ["自然", "絶景"],
    description: "世界自然遺産。知床五湖の散策や観光船からのヒグマ・クジラウォッチングなど、手つかずの自然を体感できる。",
    bestSeason: "6〜9月", stayTime: "半日〜1日", access: "女満別空港から車で約2時間",
    nearby: [], mapQuery: "知床五湖",
    photo: { file: "140829 Ichiko of Shiretoko Goko Lakes Hokkaido Japan02s5.jpg", author: "663highland", license: "CC BY 2.5" },
  },
  {
    id: "noboribetsu-onsen", name: "登別温泉", region: "北海道", prefecture: "北海道",
    categories: ["温泉", "自然"],
    description: "湯量豊富な北海道随一の温泉地。源泉の湧く「地獄谷」の荒々しい景観は迫力満点。",
    bestSeason: "通年", stayTime: "半日〜1泊", access: "新千歳空港から車で約1時間",
    nearby: ["toyako"], mapQuery: "登別温泉 地獄谷",
    photo: { file: "Noboribetsu hot spring jigokudani 20130503.jpg", author: "メルビル", license: "CC BY-SA 3.0" },
  },
  {
    id: "sapporo-nijo-market", name: "札幌・二条市場", region: "北海道", prefecture: "北海道",
    categories: ["グルメ", "街歩き"],
    description: "明治から続く札幌の台所。朝から新鮮な海鮮丼が味わえる。大通公園やすすきのへも徒歩圏。",
    bestSeason: "通年", stayTime: "約1時間", access: "札幌駅から徒歩約15分",
    nearby: ["otaru-canal"], mapQuery: "札幌 二条市場",
    photo: { file: "Nijo fish Market 2014.jpg", author: "Wing1990hk", license: "CC BY 3.0" },
  },

  {
    id: "asahiyama-zoo", name: "旭山動物園", region: "北海道", prefecture: "北海道",
    categories: ["自然"],
    description: "ペンギンの散歩やアザラシの円柱水槽など「行動展示」で知られる動物園。冬の雪の中の動物たちも人気。",
    bestSeason: "通年", stayTime: "半日", access: "旭川駅からバスで約40分",
    nearby: ["biei-blue-pond"], mapQuery: "旭山動物園",
    photo: { file: "旭山動物園 - panoramio (4).jpg", author: "Mamusi Taka", license: "CC BY-SA 3.0" },
  },
  {
    id: "furano-farm-tomita", name: "富良野・ファーム富田", region: "北海道", prefecture: "北海道",
    categories: ["絶景", "自然"],
    description: "丘一面を紫に染めるラベンダー畑の代名詞。見頃の7月はメロンや花畑スイーツも楽しめる。",
    bestSeason: "6〜8月", stayTime: "約2時間", access: "旭川空港から車で約45分",
    nearby: ["biei-blue-pond"], mapQuery: "ファーム富田",
    photo: { file: "ファーム富田（Farm Tomita） - panoramio (4).jpg", author: "t-konno", license: "CC BY-SA 3.0" },
  },
  {
    id: "toyako", name: "洞爺湖", region: "北海道", prefecture: "北海道",
    categories: ["絶景", "温泉"],
    description: "湖畔に温泉街が広がるカルデラ湖。4月下旬〜10月は毎晩ロングラン花火大会が開催される。",
    bestSeason: "4〜10月", stayTime: "半日", access: "札幌から車で約2時間",
    nearby: ["noboribetsu-onsen"], mapQuery: "洞爺湖温泉",
    photo: { file: "View of Tōyako-onsen town.JPG", author: "Wakimasa", license: "Public domain" },
  },
  {
    id: "akanko", name: "阿寒湖", region: "北海道", prefecture: "北海道",
    categories: ["自然", "温泉"],
    description: "特別天然記念物マリモの湖。湖畔にはアイヌコタンと温泉街があり、冬は湖上のフロストフラワーも見られる。",
    bestSeason: "通年", stayTime: "半日", access: "釧路空港から車で約1時間10分",
    nearby: [], mapQuery: "阿寒湖温泉",
    photo: { file: "Lake-akan and Mt-ahoro.jpg", author: "melvil", license: "CC BY-SA 4.0" },
  },
  {
    id: "hakodate-asaichi", name: "函館朝市", region: "北海道", prefecture: "北海道",
    categories: ["グルメ", "街歩き"],
    description: "駅前に約250店がひしめく朝市。イカ釣り体験と海鮮丼で函館の朝が始まる。",
    bestSeason: "通年", stayTime: "約1時間30分", access: "函館駅から徒歩1分",
    nearby: ["hakodateyama"], mapQuery: "函館朝市",
    photo: { file: "Hakodate Asaichi Hokkaido Japan05bs5.jpg", author: "663highland", license: "CC BY 2.5" },
  },
  {
    id: "cape-kamui", name: "神威岬", region: "北海道", prefecture: "北海道",
    categories: ["絶景", "自然"],
    description: "積丹半島の先端から「積丹ブルー」の海を見渡す岬。先端まで続く遊歩道「チャレンカの小道」は爽快。",
    bestSeason: "6〜8月", stayTime: "約1時間30分", access: "小樽から車で約1時間30分",
    nearby: ["otaru-canal"], mapQuery: "神威岬",
    photo: { file: "130823 Cape Kamui Shakotan Hokkaido Japan06s3.jpg", author: "663highland", license: "CC BY 2.5" },
  },
  // ---- 東北 ----
  {
    id: "oirase-gorge", name: "奥入瀬渓流", region: "東北", prefecture: "青森県",
    categories: ["自然", "絶景"],
    description: "十和田湖から流れ出る約14kmの渓流。遊歩道沿いに滝と苔むした岩が続く。新緑と紅葉の名所。",
    bestSeason: "5〜6月・10月", stayTime: "約3時間", access: "青森駅から車で約1時間30分",
    nearby: ["towadako"], mapQuery: "奥入瀬渓流",
    photo: { file: "奥入瀬渓流 - panoramio (4).jpg", author: "Yoshio Kohara", license: "CC BY 3.0" },
  },
  {
    id: "hirosaki-castle", name: "弘前城・弘前公園", region: "東北", prefecture: "青森県",
    categories: ["歴史", "自然"],
    description: "現存12天守のひとつ。約2600本の桜が濠を埋める春の弘前さくらまつりは日本屈指の桜景色。",
    bestSeason: "4月下旬〜5月上旬", stayTime: "約2時間", access: "弘前駅からバスで約15分",
    nearby: [], mapQuery: "弘前城",
    photo: { file: "弘前城、青森 Hirosaki Castle.jpg", author: "Ari Helminen", license: "CC BY 2.0" },
  },
  {
    id: "chusonji", name: "中尊寺金色堂", region: "東北", prefecture: "岩手県",
    categories: ["歴史"],
    description: "平泉の世界遺産。奥州藤原氏が築いた金箔に覆われた御堂は圧巻の一言。",
    bestSeason: "通年", stayTime: "約2時間", access: "平泉駅から徒歩約20分",
    nearby: ["genbikei"], mapQuery: "中尊寺金色堂",
    photo: { file: "Konjikido Ooido (Chusonji) 20201228.jpg", author: "Suicasmo", license: "CC BY-SA 4.0" },
  },
  {
    id: "jodogahama", name: "浄土ヶ浜", region: "東北", prefecture: "岩手県",
    categories: ["絶景", "自然"],
    description: "白い流紋岩と松の緑、透き通る海が織りなす三陸を代表する景勝地。青の洞窟をめぐるさっぱ船も人気。",
    bestSeason: "6〜9月", stayTime: "約2時間", access: "宮古駅から車で約10分",
    nearby: [], mapQuery: "浄土ヶ浜",
    photo: { file: "浄土ヶ浜の風景20220625-P1390500.jpg", author: "くろふね", license: "CC BY 4.0" },
  },
  {
    id: "matsushima", name: "松島", region: "東北", prefecture: "宮城県",
    categories: ["絶景", "グルメ"],
    description: "日本三景のひとつ。260余りの島々が浮かぶ湾を遊覧船で巡れる。牡蠣や笹かまぼこも名物。",
    bestSeason: "通年", stayTime: "約3時間", access: "仙台駅からJRで約40分",
    nearby: [], mapQuery: "松島 遊覧船",
    photo: { file: "Matsushima (Matsushima Bay).jpg", author: "Cheng-en Cheng", license: "CC BY-SA 2.0" },
  },
  {
    id: "zao-okama", name: "蔵王・御釜", region: "東北", prefecture: "宮城県",
    categories: ["絶景", "自然"],
    description: "エメラルドグリーンの火口湖。天候で色を変える神秘の湖面を蔵王エコーラインのドライブで目指す。",
    bestSeason: "5〜10月", stayTime: "約1時間", access: "仙台から車で約1時間30分",
    nearby: ["yamadera", "zao-onsen"], mapQuery: "蔵王 御釜",
    photo: { file: "Zao L.Okama.JPG", author: "Qwert1234", license: "Public domain" },
  },
  {
    id: "kakunodate", name: "角館", region: "東北", prefecture: "秋田県",
    categories: ["歴史", "街歩き"],
    description: "「みちのくの小京都」と呼ばれる武家屋敷の町並み。春はしだれ桜のトンネルが見事。",
    bestSeason: "4月下旬〜5月上旬", stayTime: "約2時間", access: "角館駅から徒歩約15分",
    nearby: ["nyuto-onsen", "tazawako"], mapQuery: "角館 武家屋敷通り",
    photo: { file: "角館武家屋敷通り20250118-P1063202.jpg", author: "くろふね", license: "CC BY 4.0" },
  },
  {
    id: "nyuto-onsen", name: "乳頭温泉郷", region: "東北", prefecture: "秋田県",
    categories: ["温泉", "自然"],
    description: "ブナの森に7つの湯宿が点在する秘湯の里。乳白色の露天風呂と湯めぐり帳での外湯巡りが名物。",
    bestSeason: "通年", stayTime: "半日〜1泊", access: "田沢湖駅からバスで約50分",
    nearby: ["kakunodate", "tazawako"], mapQuery: "乳頭温泉郷 鶴の湯",
    photo: { file: "乳頭温泉郷-鶴の湯 - panoramio.jpg", author: "SpringField1967", license: "CC BY-SA 3.0" },
  },
  {
    id: "ginzan-onsen", name: "銀山温泉", region: "東北", prefecture: "山形県",
    categories: ["温泉", "街歩き"],
    description: "大正ロマンの木造旅館が川沿いに並ぶ温泉街。ガス灯と雪景色の組み合わせは冬の風物詩。",
    bestSeason: "12〜2月", stayTime: "半日〜1泊", access: "大石田駅からバスで約40分",
    nearby: ["yamadera"], mapQuery: "銀山温泉",
    photo: { file: "Ginzan Onsen Takimi Bridge.jpg", author: "ブルーノ・プラス", license: "CC BY 4.0" },
  },
  {
    id: "yamadera", name: "山寺(立石寺)", region: "東北", prefecture: "山形県",
    categories: ["歴史", "絶景"],
    description: "断崖に堂宇が連なる天台宗の古刹。1015段の石段を登った五大堂からの眺めは疲れを忘れる絶景。",
    bestSeason: "5〜11月", stayTime: "約2時間", access: "山形駅からJRで約20分+徒歩",
    nearby: ["ginzan-onsen", "zao-okama"], mapQuery: "山寺 立石寺",
    photo: { file: "Risshaku-ji konponchudo.jpg", author: "Cp9asngf", license: "CC BY-SA 4.0" },
  },
  {
    id: "ouchi-juku", name: "大内宿", region: "東北", prefecture: "福島県",
    categories: ["歴史", "街歩き", "グルメ"],
    description: "江戸時代の宿場町の茅葺き屋根が今も残る。ねぎを箸代わりに食べる「ねぎそば」が名物。",
    bestSeason: "通年", stayTime: "約2時間", access: "湯野上温泉駅から車で約10分",
    nearby: ["tsuruga-castle"], mapQuery: "大内宿",
    photo: { file: "大内宿 - panoramio (12).jpg", author: "くろふね", license: "CC BY 3.0" },
  },
  {
    id: "goshiki-numa", name: "五色沼", region: "東北", prefecture: "福島県",
    categories: ["自然", "絶景"],
    description: "磐梯山の噴火が生んだ大小の湖沼群。コバルトブルーやエメラルドグリーンに輝く沼を探勝路でめぐる。",
    bestSeason: "5〜11月", stayTime: "約2時間", access: "猪苗代駅からバスで約30分",
    nearby: [], mapQuery: "五色沼自然探勝路",
    photo: { file: "五色沼の毘沙門沼 - panoramio.jpg", author: "Hiroyuki Sato", license: "CC BY-SA 3.0" },
  },

  {
    id: "towadako", name: "十和田湖", region: "東北", prefecture: "青森県",
    categories: ["自然", "絶景"],
    description: "奥入瀬渓流の源にあたる十和田八幡平国立公園の中心のカルデラ湖。遊覧船と湖畔の「乙女の像」が定番。",
    bestSeason: "5〜10月", stayTime: "約2時間", access: "八戸駅からバスで約2時間15分",
    nearby: ["oirase-gorge"], mapQuery: "十和田湖 休屋",
    photo: { file: "Lake Towada from Ohanabe 2008.jpg", author: "Soica2001", license: "Public domain" },
  },
  {
    id: "hachinohe-yokocho", name: "八戸・みろく横丁", region: "東北", prefecture: "青森県",
    categories: ["グルメ", "街歩き"],
    description: "屋台26店が連なる横丁。せんべい汁や八戸前沖さばなど南部の味を、店主や地元客と肩を並べて楽しめる。",
    bestSeason: "通年", stayTime: "約2時間", access: "本八戸駅から徒歩約10分",
    nearby: [], mapQuery: "八戸 みろく横丁",
    photo: { file: "Miroku Yokocho 2024-09-14 2.jpg", author: "七厩拓", license: "CC BY-SA 4.0" },
  },
  {
    id: "ryusendo", name: "龍泉洞", region: "東北", prefecture: "岩手県",
    categories: ["自然"],
    description: "日本三大鍾乳洞のひとつ。「ドラゴンブルー」と呼ばれる世界有数の透明度を誇る地底湖が神秘的。",
    bestSeason: "通年", stayTime: "約1時間", access: "盛岡駅からバスで約2時間10分",
    nearby: [], mapQuery: "龍泉洞",
    photo: { file: "Ryusendo Cave Underground Lake Cap 20201115.jpg", author: "--[[利用者:あおもりくま|あおもりくま]]（会話） 2020年11月21日 (土) 01:16 (UTC)", license: "Public domain" },
  },
  {
    id: "genbikei", name: "厳美渓", region: "東北", prefecture: "岩手県",
    categories: ["絶景", "自然"],
    description: "栗駒山を源とする磐井川が刻んだ渓谷美。対岸からロープを渡って飛んでくる「空飛ぶだんご」が名物。",
    bestSeason: "4〜11月", stayTime: "約1時間", access: "一ノ関駅からバスで約20分",
    nearby: ["chusonji"], mapQuery: "厳美渓",
    photo: { file: "230727 Genbikei Ichinoseki Iwate pref Japan01s3.jpg", author: "663highland", license: "CC BY-SA 4.0" },
  },
  {
    id: "akiu-onsen", name: "秋保温泉", region: "東北", prefecture: "宮城県",
    categories: ["温泉", "自然"],
    description: "「仙台の奥座敷」と呼ばれる古湯。近くには落差55mの秋保大滝や奇岩が続く磊々峡の散策路も。",
    bestSeason: "通年", stayTime: "半日", access: "仙台駅からバスで約50分",
    nearby: [], mapQuery: "秋保温泉",
    photo: { file: "211029 Akiu Onsen Sendai Miyagi pref Japan01s3.jpg", author: "663highland", license: "CC BY-SA 4.0" },
  },
  {
    id: "naruko-onsen", name: "鳴子温泉郷", region: "東北", prefecture: "宮城県",
    categories: ["温泉", "自然"],
    description: "こけしと下駄の音が似合う湯治の里。源泉数約370本、日本にある泉質の約7割が揃うといわれる。",
    bestSeason: "10〜11月", stayTime: "半日", access: "鳴子温泉駅から徒歩すぐ",
    nearby: [], mapQuery: "鳴子温泉",
    photo: { file: "Naruko Spa distant view.jpg", author: "Yauchi", license: "CC BY-SA 4.0" },
  },
  {
    id: "tazawako", name: "田沢湖", region: "東北", prefecture: "秋田県",
    categories: ["絶景", "自然"],
    description: "水深日本一(423m)の瑠璃色の湖。湖畔に立つ金色のたつこ像が絶好の撮影スポット。",
    bestSeason: "5〜10月", stayTime: "約2時間", access: "田沢湖駅からバスで約12分",
    nearby: ["nyuto-onsen", "kakunodate"], mapQuery: "田沢湖 たつこ像",
    photo: { file: "Kansa Shrine built on the shore of the Lake Tazawa 20200823b.jpg", author: "掬茶", license: "CC BY-SA 4.0" },
  },
  {
    id: "oga-nyudozaki", name: "男鹿半島・入道崎", region: "東北", prefecture: "秋田県",
    categories: ["絶景", "自然"],
    description: "緑の大地と青い海、白黒縞の灯台のコントラストが美しい岬。なまはげの里としても知られる。",
    bestSeason: "6〜9月", stayTime: "約1時間30分", access: "男鹿駅から車で約30分",
    nearby: [], mapQuery: "入道崎",
    photo: { file: "Nyudozaki Lighthouse Veroyama.jpg", author: "https://www.flickr.com/photos/veroyama/", license: "CC BY 2.0" },
  },
  {
    id: "zao-onsen", name: "蔵王温泉", region: "東北", prefecture: "山形県",
    categories: ["温泉", "絶景"],
    description: "開湯1900年と伝わる強酸性の湯。冬はロープウェイから世界的にも珍しい樹氷の森を見下ろせる。",
    bestSeason: "12〜2月", stayTime: "半日", access: "山形駅からバスで約40分",
    nearby: ["zao-okama"], mapQuery: "蔵王温泉",
    photo: { file: "Snow Monsters, Zao Onsen Ski Resort.jpg", author: "ZAO Ropeway", license: "CC BY 4.0" },
  },
  {
    id: "sankyo-soko", name: "酒田・山居倉庫", region: "東北", prefecture: "山形県",
    categories: ["歴史", "街歩き"],
    description: "明治26年築の米保管倉庫が12棟並ぶ港町のシンボル。ケヤキ並木と黒壁の景観は映画のロケ地にも。",
    bestSeason: "通年", stayTime: "約1時間", access: "酒田駅から車で約5分",
    nearby: [], mapQuery: "山居倉庫",
    photo: { file: "山居倉庫 - panoramio (8).jpg", author: "くろふね", license: "CC BY 3.0" },
  },
  {
    id: "tsuruga-castle", name: "会津若松・鶴ヶ城", region: "東北", prefecture: "福島県",
    categories: ["歴史"],
    description: "戊辰戦争で1か月の籠城に耐えた名城。国内で唯一の赤瓦の天守が空に映える。",
    bestSeason: "4〜11月", stayTime: "約1時間30分", access: "会津若松駅からバスで約15分",
    nearby: ["ouchi-juku", "kitakata"], mapQuery: "鶴ヶ城",
    photo: { file: "鶴ヶ城.jpg", author: "Kiha 40-2020", license: "CC BY-SA 4.0" },
  },
  {
    id: "kitakata", name: "喜多方", region: "東北", prefecture: "福島県",
    categories: ["グルメ", "街歩き"],
    description: "蔵が4000棟以上残る「蔵のまち」。朝からラーメンを食べる「朝ラー」文化の聖地でもある。",
    bestSeason: "通年", stayTime: "約2時間", access: "喜多方駅から徒歩約15分",
    nearby: ["tsuruga-castle"], mapQuery: "喜多方 蔵のまち",
    photo: { file: "Kitakata ramen by macyu in Yamagata.jpg", author: "macyu from Kitakata, Kitakata", license: "CC BY 2.0" },
  },
  // ---- 関東 ----
  {
    id: "hitachi-seaside-park", name: "国営ひたち海浜公園", region: "関東", prefecture: "茨城県",
    categories: ["絶景", "自然"],
    description: "春は丘一面を青く染めるネモフィラ、秋は真っ赤なコキアが有名。季節の花畑が圧巻。",
    bestSeason: "4〜5月・10月", stayTime: "約3時間", access: "勝田駅からバスで約20分",
    nearby: [], mapQuery: "国営ひたち海浜公園",
    photo: { file: "国営ひたち海浜公園のネモフィラ20220430-IMG 1718.jpg", author: "くろふね", license: "CC BY 4.0" },
  },
  {
    id: "fukuroda-falls", name: "袋田の滝", region: "関東", prefecture: "茨城県",
    categories: ["絶景", "自然"],
    description: "四段に落ちる日本三名瀑のひとつ。冬は滝全体が凍る「氷瀑」、秋は紅葉との共演が見事。",
    bestSeason: "11月・1〜2月", stayTime: "約1時間", access: "袋田駅から車で約10分",
    nearby: [], mapQuery: "袋田の滝",
    photo: { file: "Fukuroda Falls - 袋田の滝(ふくろだのたき).jpg", author: "TANAKA Juuyoh (田中十洋)", license: "CC BY 2.0" },
  },
  {
    id: "nikko-toshogu", name: "日光東照宮", region: "関東", prefecture: "栃木県",
    categories: ["歴史", "自然"],
    description: "徳川家康を祀る豪華絢爛な世界遺産。陽明門や眠り猫など見どころ多数。華厳の滝・中禅寺湖と合わせて回りたい。",
    bestSeason: "通年", stayTime: "約2時間", access: "東武日光駅からバスで約10分",
    nearby: ["kegon-falls", "utsunomiya-gyoza"], mapQuery: "日光東照宮",
    photo: { file: "The Three Wise Monkeys, Nikkō Tōshō-gū; April 2018.jpg", author: "Ray in Manila", license: "CC BY 2.0" },
  },
  {
    id: "ashikaga-flower-park", name: "あしかがフラワーパーク", region: "関東", prefecture: "栃木県",
    categories: ["絶景", "自然"],
    description: "樹齢160年超の大藤棚が幻想的な藤の名所。冬の関東三大イルミネーションも見応えあり。",
    bestSeason: "4月中旬〜5月中旬", stayTime: "約2時間", access: "あしかがフラワーパーク駅からすぐ",
    nearby: [], mapQuery: "あしかがフラワーパーク",
    photo: { file: "あしかがフラワーパーク - panoramio.jpg", author: "Yoshio Kohara", license: "CC BY 3.0" },
  },
  {
    id: "kusatsu-onsen", name: "草津温泉", region: "関東", prefecture: "群馬県",
    categories: ["温泉", "街歩き"],
    description: "自然湧出量日本一。湯畑を中心に温泉情緒あふれる街が広がり、名物「湯もみ」も見学できる。",
    bestSeason: "通年", stayTime: "半日〜1泊", access: "長野原草津口駅からバスで約25分",
    nearby: ["ikaho-onsen", "shima-onsen"], mapQuery: "草津温泉 湯畑",
    photo: { file: "草津温泉 湯畑.JPG", author: "Volksoper", license: "CC BY-SA 3.0" },
  },
  {
    id: "ikaho-onsen", name: "伊香保温泉", region: "関東", prefecture: "群馬県",
    categories: ["温泉", "街歩き"],
    description: "365段の石段街の両側に宿と射的場が並ぶノスタルジックな温泉街。茶褐色の「黄金の湯」が名物。",
    bestSeason: "通年", stayTime: "半日〜1泊", access: "渋川駅からバスで約25分",
    nearby: ["kusatsu-onsen"], mapQuery: "伊香保温泉 石段街",
    photo: { file: "Ikaho Onsen 02.jpg", author: "Tomo", license: "CC BY 2.0" },
  },
  {
    id: "kawagoe", name: "川越", region: "関東", prefecture: "埼玉県",
    categories: ["歴史", "街歩き", "グルメ"],
    description: "「小江戸」と呼ばれる蔵造りの町並み。時の鐘や菓子屋横丁など、食べ歩きが楽しいエリア。",
    bestSeason: "通年", stayTime: "約3時間", access: "川越駅から徒歩約20分",
    nearby: ["nagatoro"], mapQuery: "川越 蔵造りの町並み",
    photo: { file: "Kurazukuri Street in Little Edo.jpg", author: "Dandy1022", license: "CC BY-SA 4.0" },
  },
  {
    id: "nagatoro", name: "長瀞", region: "関東", prefecture: "埼玉県",
    categories: ["自然", "絶景"],
    description: "岩畳の間を和舟で下るライン下りが名物の渓谷。かき氷の名店や宝登山からの眺望も楽しい。",
    bestSeason: "4〜11月", stayTime: "約3時間", access: "長瀞駅から徒歩約5分",
    nearby: ["kawagoe", "chichibu-hitsujiyama"], mapQuery: "長瀞 岩畳",
    photo: { file: "長瀞、岩畳対岸から - panoramio.jpg", author: "高橋文武", license: "CC BY 3.0" },
  },
  {
    id: "naritasan", name: "成田山新勝寺", region: "関東", prefecture: "千葉県",
    categories: ["歴史", "グルメ", "街歩き"],
    description: "1000年超の歴史を持つ不動尊信仰の総府。参道に並ぶうなぎの老舗での食べ歩きも楽しみ。",
    bestSeason: "通年", stayTime: "約2時間", access: "成田駅から徒歩約10分",
    nearby: [], mapQuery: "成田山新勝寺",
    photo: { file: "成田山新勝寺20220709-P1001018.jpg", author: "くろふね", license: "CC BY 4.0" },
  },
  {
    id: "yoro-valley", name: "養老渓谷", region: "関東", prefecture: "千葉県",
    categories: ["自然", "温泉"],
    description: "房総随一の渓谷美。粟又の滝の遊歩道散策と黒湯の温泉が楽しめる、都心から近い癒しの里。",
    bestSeason: "11月下旬〜12月上旬", stayTime: "約3時間", access: "養老渓谷駅から車で約10分",
    nearby: [], mapQuery: "養老渓谷 粟又の滝",
    photo: { file: "粟又の滝 - panoramio.jpg", author: "くろふね", license: "CC BY 3.0" },
  },
  {
    id: "asakusa-sensoji", name: "浅草・浅草寺", region: "関東", prefecture: "東京都",
    categories: ["歴史", "街歩き", "グルメ"],
    description: "雷門と仲見世通りで知られる東京最古の寺。下町グルメの食べ歩きや人力車も人気。",
    bestSeason: "通年", stayTime: "約2時間", access: "浅草駅からすぐ",
    nearby: ["tsukiji-market", "meiji-jingu", "ameyoko"], mapQuery: "浅草寺",
    photo: { file: "Sensoji 2023.jpg", author: "Akonnchiroll", license: "CC0" },
  },
  {
    id: "meiji-jingu", name: "明治神宮", region: "関東", prefecture: "東京都",
    categories: ["歴史", "自然"],
    description: "都心とは思えない深い杜に包まれた神域。原宿駅からすぐの大鳥居をくぐれば静寂の参道が続く。",
    bestSeason: "通年", stayTime: "約1時間30分", access: "原宿駅からすぐ",
    nearby: ["asakusa-sensoji", "shibuya-crossing"], mapQuery: "明治神宮",
    photo: { file: "Courtyard of Meiji Shrine 20220705a.jpg", author: "江戸村のとくぞう", license: "CC BY-SA 4.0" },
  },
  {
    id: "tsukiji-market", name: "築地場外市場", region: "関東", prefecture: "東京都",
    categories: ["グルメ", "街歩き"],
    description: "約400の店がひしめく食のワンダーランド。海鮮丼や玉子焼きの食べ歩きは朝から行くのが正解。",
    bestSeason: "通年", stayTime: "約2時間", access: "築地駅からすぐ",
    nearby: ["asakusa-sensoji"], mapQuery: "築地場外市場",
    photo: { file: "August 2007 Tsukiji fish market 3.jpg", author: "Syced", license: "CC0" },
  },
  {
    id: "kamakura", name: "鎌倉", region: "関東", prefecture: "神奈川県",
    categories: ["歴史", "街歩き", "グルメ"],
    description: "鶴岡八幡宮や大仏、小町通りの食べ歩き、江ノ電での海沿い移動など1日中楽しめる古都。",
    bestSeason: "通年", stayTime: "半日〜1日", access: "鎌倉駅から徒歩約10分",
    nearby: ["enoshima", "yokohama-chukagai"], mapQuery: "鎌倉 鶴岡八幡宮",
    photo: { file: "Tsurugaoka Hachimangu 001.jpg", author: "Ocdp", license: "CC0" },
  },
  {
    id: "hakone-ashinoko", name: "箱根・芦ノ湖", region: "関東", prefecture: "神奈川県",
    categories: ["温泉", "絶景", "自然"],
    description: "海賊船の浮かぶ湖越しに富士山を望む王道リゾート。大涌谷の黒たまごと名湯めぐりも欠かせない。",
    bestSeason: "通年", stayTime: "半日〜1泊", access: "箱根湯本駅からバスで約35分",
    nearby: ["atami-onsen"], mapQuery: "芦ノ湖 箱根神社",
    photo: { file: "Lake Ashi & Mt Fuji & Hakone Shrine.jpg", author: "Charlie fong", license: "CC BY-SA 4.0" },
  },

  {
    id: "kairakuen", name: "偕楽園", region: "関東", prefecture: "茨城県",
    categories: ["歴史", "自然"],
    description: "日本三名園のひとつ。約100種3000本の梅が咲き競う2〜3月の梅まつりが見どころ。",
    bestSeason: "2〜3月", stayTime: "約1時間30分", access: "水戸駅からバスで約20分",
    nearby: [], mapQuery: "偕楽園",
    photo: { file: "偕楽園 (13926341268).jpg", author: "M Murakami from Fukushima, Japan", license: "CC BY-SA 2.0" },
  },
  {
    id: "kegon-falls", name: "華厳の滝", region: "関東", prefecture: "栃木県",
    categories: ["絶景", "自然"],
    description: "中禅寺湖の水が高さ97mを一気に落ちる日本三名瀑。エレベーターで滝壺近くの観瀑台へ下りられる。",
    bestSeason: "10〜11月", stayTime: "約1時間", access: "東武日光駅からバスで約45分",
    nearby: ["nikko-toshogu"], mapQuery: "華厳の滝",
    photo: { file: "紅葉の華厳の滝.jpg", author: "くろふね", license: "CC BY-SA 4.0" },
  },
  {
    id: "utsunomiya-gyoza", name: "宇都宮餃子の街", region: "関東", prefecture: "栃木県",
    categories: ["グルメ", "街歩き"],
    description: "専門店が200店を超える「餃子のまち」。焼き・揚げ・水餃子を店ごとに食べ比べるハシゴが楽しい。",
    bestSeason: "通年", stayTime: "約2時間", access: "宇都宮駅から徒歩圏",
    nearby: ["nikko-toshogu"], mapQuery: "宇都宮 餃子通り",
    photo: { file: "Gyoza Street, Utsunomiya, April 2020.jpg", author: "Miyuki Meinaka", license: "CC BY-SA 4.0" },
  },
  {
    id: "tomioka-silk-mill", name: "富岡製糸場", region: "関東", prefecture: "群馬県",
    categories: ["歴史"],
    description: "明治5年開業の官営製糸場で世界遺産。繰糸所や繭倉庫がほぼ完全な形で残る。",
    bestSeason: "通年", stayTime: "約1時間30分", access: "上州富岡駅から徒歩約15分",
    nearby: [], mapQuery: "富岡製糸場",
    photo: { file: "Seidenfabrik in Tomioka 富岡製糸場 8.jpg", author: "Zluhcs", license: "CC BY-SA 4.0" },
  },
  {
    id: "shima-onsen", name: "四万温泉", region: "関東", prefecture: "群馬県",
    categories: ["温泉", "自然"],
    description: "「四万(よんまん)の病を癒す」と伝わる名湯。青く澄んだ四万川と奥四万湖の「四万ブルー」も見どころ。",
    bestSeason: "通年", stayTime: "半日", access: "中之条駅からバスで約40分",
    nearby: ["kusatsu-onsen"], mapQuery: "四万温泉",
    photo: { file: "四万温泉 中之条 2013 (9993444756).jpg", author: "Kentaro Ohno from Tokyo, Japan", license: "CC BY 2.0" },
  },
  {
    id: "chichibu-hitsujiyama", name: "秩父・羊山公園", region: "関東", prefecture: "埼玉県",
    categories: ["絶景", "自然"],
    description: "武甲山を背に約40万株の芝桜が丘を染める。見頃の4月中旬〜5月上旬は露店も並びにぎわう。",
    bestSeason: "4〜5月", stayTime: "約1時間30分", access: "西武秩父駅から徒歩約20分",
    nearby: ["nagatoro"], mapQuery: "羊山公園 芝桜の丘",
    photo: { file: "芝桜の丘（羊山公園）.JPG", author: "Mdkriko", license: "CC BY-SA 4.0" },
  },
  {
    id: "nokogiriyama", name: "鋸山・日本寺", region: "関東", prefecture: "千葉県",
    categories: ["絶景", "歴史"],
    description: "断崖から突き出た「地獄のぞき」と日本一の大きさを誇る磨崖大仏。ロープウェーで山頂へ。",
    bestSeason: "通年", stayTime: "半日", access: "浜金谷駅から徒歩とロープウェーで約20分",
    nearby: [], mapQuery: "鋸山 日本寺",
    photo: { file: "Nihon-ji Daibutsu.jpg", author: "Dandy1022", license: "CC BY-SA 4.0" },
  },
  {
    id: "shibuya-crossing", name: "渋谷スクランブル交差点", region: "関東", prefecture: "東京都",
    categories: ["街歩き"],
    description: "1回の青信号で最大3000人が行き交うといわれる世界的スポット。展望施設から見下ろす夜の交差点も人気。",
    bestSeason: "通年", stayTime: "約1時間", access: "渋谷駅から徒歩すぐ",
    nearby: ["meiji-jingu"], mapQuery: "渋谷スクランブル交差点",
    photo: { file: "Tokyo Shibuya Scramble Crossing 2018-10-09.jpg", author: "Benh LIEU SONG (Flickr)", license: "CC BY-SA 2.0" },
  },
  {
    id: "ameyoko", name: "上野・アメ横", region: "関東", prefecture: "東京都",
    categories: ["グルメ", "街歩き"],
    description: "ガード下に約400店がひしめく商店街。食べ歩きと威勢のいい呼び込みが楽しい下町の台所。",
    bestSeason: "通年", stayTime: "約2時間", access: "上野駅から徒歩すぐ",
    nearby: ["asakusa-sensoji"], mapQuery: "アメ横",
    photo: { file: "Ameyoko Shopping Streets, Ueno (53416667926).jpg", author: "Stephen Kelly", license: "CC BY 2.0" },
  },
  {
    id: "takaosan", name: "高尾山", region: "関東", prefecture: "東京都",
    categories: ["自然", "絶景"],
    description: "都心から電車で約1時間のミシュラン三つ星の山。ケーブルカーと名物の天狗焼、晴れれば山頂から富士山も。",
    bestSeason: "11月", stayTime: "半日", access: "高尾山口駅から徒歩すぐ",
    nearby: [], mapQuery: "高尾山",
    photo: { file: "Summit @ Mount Takao (9876510546).jpg", author: "Guilhem Vellut", license: "CC BY 2.0" },
  },
  {
    id: "yokohama-chukagai", name: "横浜中華街", region: "関東", prefecture: "神奈川県",
    categories: ["グルメ", "街歩き"],
    description: "約600店が集まる日本最大の中華街。食べ歩きから老舗の名店まで、胃袋がいくつあっても足りない。",
    bestSeason: "通年", stayTime: "約3時間", access: "元町・中華街駅から徒歩すぐ",
    nearby: ["kamakura"], mapQuery: "横浜中華街",
    photo: { file: "Yokohama Chinatown 4.jpg", author: "Syced", license: "CC0" },
  },
  {
    id: "enoshima", name: "江の島", region: "関東", prefecture: "神奈川県",
    categories: ["絶景", "街歩き"],
    description: "参道グルメとシーキャンドルからの相模湾の眺め。晴れた日には富士山も望む湘南のシンボル。",
    bestSeason: "通年", stayTime: "半日", access: "片瀬江ノ島駅から徒歩約15分",
    nearby: ["kamakura"], mapQuery: "江の島",
    photo: { file: "Enoshima Island.jpg", author: "Dandy1022", license: "CC BY-SA 4.0" },
  },
  // ---- 中部 ----
  {
    id: "kiyotsu-gorge", name: "清津峡", region: "中部", prefecture: "新潟県",
    categories: ["絶景", "自然"],
    description: "日本三大峡谷のひとつ。水鏡が渓谷を映すトンネル最奥の「パノラマステーション」は必見のアート空間。",
    bestSeason: "4〜11月", stayTime: "約1時間30分", access: "越後湯沢駅から車で約25分",
    nearby: [], mapQuery: "清津峡渓谷トンネル",
    photo: { file: "Find47 Niigata-Kiyotsu Gorge Tunnel-m.jpg", author: "Yasuyuki_Kawano", license: "CC BY 4.0" },
  },
  {
    id: "sado-island", name: "佐渡島", region: "中部", prefecture: "新潟県",
    categories: ["自然", "歴史"],
    description: "たらい舟と世界遺産の金山で知られる日本海最大の島。断崖の尖閣湾など手つかずの海岸美が続く。",
    bestSeason: "5〜10月", stayTime: "1日〜", access: "新潟港からフェリーで約2時間30分",
    nearby: [], mapQuery: "佐渡金山",
    photo: { file: "Taraibune in Sado Ogi.jpg", author: "rhodnite", license: "CC BY 2.0" },
  },
  {
    id: "tateyama-kurobe", name: "立山黒部アルペンルート", region: "中部", prefecture: "富山県",
    categories: ["絶景", "自然"],
    description: "標高3000m級の山々を乗り物で越える山岳観光ルート。春の「雪の大谷」と黒部ダムの放水が有名。",
    bestSeason: "4〜11月", stayTime: "1日", access: "立山駅または扇沢からケーブルカー等を乗り継ぎ",
    nearby: [], mapQuery: "立山黒部アルペンルート",
    photo: { file: "Kurobe Dam and rainbow.jpg", author: "Alpsdake", license: "CC BY-SA 3.0" },
  },
  {
    id: "ainokura", name: "五箇山・相倉合掌造り集落", region: "中部", prefecture: "富山県",
    categories: ["歴史", "絶景", "街歩き"],
    description: "白川郷とともに世界遺産に登録された山あいの合掌集落。観光地化されすぎない静けさが魅力。",
    bestSeason: "通年", stayTime: "約1時間30分", access: "城端駅から車で約25分",
    nearby: ["shirakawago"], mapQuery: "相倉合掌造り集落",
    photo: { file: "相倉合掌造り集落20221105-IMG 4691.jpg", author: "くろふね", license: "CC BY 4.0" },
  },
  {
    id: "kenrokuen", name: "金沢・兼六園", region: "中部", prefecture: "石川県",
    categories: ["歴史", "街歩き", "グルメ"],
    description: "日本三名園のひとつ。ひがし茶屋街の街歩きや近江町市場の海鮮も合わせて楽しみたい。",
    bestSeason: "通年", stayTime: "約2時間", access: "金沢駅からバスで約15分",
    nearby: ["chirihama", "higashi-chaya", "omicho-market"], mapQuery: "兼六園",
    photo: { file: "Kotoji Toro and Nijibashi Bridge in Kenroku Garden.JPG", author: "そらみみ", license: "CC BY-SA 4.0" },
  },
  {
    id: "chirihama", name: "千里浜なぎさドライブウェイ", region: "中部", prefecture: "石川県",
    categories: ["絶景"],
    description: "日本で唯一、波打ち際を車で走れる約8kmの砂浜。夕日の時間帯のドライブは映画のワンシーンのよう。",
    bestSeason: "4〜11月", stayTime: "約1時間", access: "金沢駅から車で約45分",
    nearby: ["kenrokuen"], mapQuery: "千里浜なぎさドライブウェイ",
    photo: { file: "Chirihama Driveway 200906.jpg", author: "Totti", license: "CC BY-SA 4.0" },
  },
  {
    id: "tojinbo", name: "東尋坊", region: "中部", prefecture: "福井県",
    categories: ["絶景", "自然"],
    description: "日本海の荒波が削った柱状節理の断崖絶壁。遊覧船から見上げる岩壁と夕日の眺めが圧巻。",
    bestSeason: "通年", stayTime: "約1時間30分", access: "芦原温泉駅からバスで約40分",
    nearby: ["eiheiji"], mapQuery: "東尋坊",
    photo: { file: "Tojinbo Oike 200507.jpg", author: "っ", license: "CC BY-SA 3.0" },
  },
  {
    id: "eiheiji", name: "永平寺", region: "中部", prefecture: "福井県",
    categories: ["歴史", "自然"],
    description: "道元禅師が開いた曹洞宗の大本山。老杉に囲まれた七堂伽藍を回廊で巡れば心が静まる。",
    bestSeason: "通年", stayTime: "約2時間", access: "福井駅からバスで約30分",
    nearby: ["tojinbo", "echizen-ono-castle"], mapQuery: "永平寺",
    photo: { file: "Eiheiji Temple (20392813818).jpg", author: "Tak H. from Chiba, Japan", license: "CC BY-SA 2.0" },
  },
  {
    id: "kawaguchiko", name: "河口湖", region: "中部", prefecture: "山梨県",
    categories: ["絶景", "温泉", "自然"],
    description: "富士山の絶景ポイントとして名高い湖。湖畔の温泉宿から望む逆さ富士は格別。",
    bestSeason: "通年", stayTime: "半日", access: "河口湖駅から周遊バス",
    nearby: ["oshino-hakkai", "arakurayama-sengen"], mapQuery: "河口湖 大石公園",
    photo: { file: "Mount Fuji from Oishi Park.jpg", author: "Alpsdake", license: "CC BY-SA 4.0" },
  },
  {
    id: "oshino-hakkai", name: "忍野八海", region: "中部", prefecture: "山梨県",
    categories: ["自然", "絶景", "街歩き"],
    description: "富士の伏流水が湧く8つの澄んだ池。茅葺きの里の風景と底まで見える青い水面が美しい。",
    bestSeason: "通年", stayTime: "約1時間30分", access: "富士山駅からバスで約20分",
    nearby: ["kawaguchiko", "arakurayama-sengen"], mapQuery: "忍野八海",
    photo: { file: "Oshino-Hakkai-Nakaike.jpg", author: "MaedaAkihiko", license: "CC BY-SA 4.0" },
  },
  {
    id: "kamikochi", name: "上高地", region: "中部", prefecture: "長野県",
    categories: ["自然", "絶景"],
    description: "穂高連峰を映す梓川と河童橋。標高1500mの山岳リゾートで、夏でも涼しく散策できる。",
    bestSeason: "5〜10月", stayTime: "半日", access: "松本駅からバス等で約1時間30分(マイカー規制)",
    nearby: ["matsumoto-castle"], mapQuery: "上高地 河童橋",
    photo: { file: "150920 Kappa-bashi Kamikochi Japan01n.jpg", author: "663highland", license: "CC BY 2.5" },
  },
  {
    id: "matsumoto-castle", name: "松本城", region: "中部", prefecture: "長野県",
    categories: ["歴史", "絶景"],
    description: "北アルプスを背にそびえる漆黒の現存天守。堀に映る「逆さ松本城」と城下町のクラフト店巡りも楽しい。",
    bestSeason: "通年", stayTime: "約2時間", access: "松本駅から徒歩約15分",
    nearby: ["kamikochi", "narai-juku"], mapQuery: "松本城",
    photo: { file: "Matsumoto Castle05s5s4592.jpg", author: "663highland", license: "CC BY 2.5" },
  },
  {
    id: "shirakawago", name: "白川郷", region: "中部", prefecture: "岐阜県",
    categories: ["歴史", "絶景", "街歩き"],
    description: "合掌造り集落の世界遺産。展望台から見下ろす集落の風景は四季それぞれに絵になる。",
    bestSeason: "通年", stayTime: "約3時間", access: "高山からバスで約50分",
    nearby: ["ainokura", "takayama"], mapQuery: "白川郷 合掌造り集落",
    photo: { file: "Ogi Shirakawa-gō, Gifu, Japan.jpg", author: "663highland", license: "CC BY 2.5" },
  },
  {
    id: "takayama", name: "飛騨高山・古い町並", region: "中部", prefecture: "岐阜県",
    categories: ["街歩き", "歴史", "グルメ"],
    description: "出格子の商家が連なる城下町。飛騨牛にぎりや朝市の食べ歩き、酒蔵巡りで「飛騨の小京都」を満喫。",
    bestSeason: "通年", stayTime: "約3時間", access: "高山駅から徒歩約10分",
    nearby: ["shirakawago", "gero-onsen"], mapQuery: "高山 さんまち通り",
    photo: { file: "Takayama sannomachi 1 - panoramio.jpg", author: "katsu696", license: "CC BY-SA 3.0" },
  },
  {
    id: "atami-onsen", name: "熱海温泉", region: "中部", prefecture: "静岡県",
    categories: ["温泉", "グルメ", "街歩き"],
    description: "都心からアクセス抜群の海辺の温泉街。商店街の食べ歩きや海上花火大会も人気。",
    bestSeason: "通年", stayTime: "半日〜1泊", access: "熱海駅から徒歩すぐ",
    nearby: ["hakone-ashinoko", "jogasaki"], mapQuery: "熱海温泉",
    photo: { file: "181122 Atami Onsen Shizuoka pref Japan03s.jpg", author: "663highland", license: "CC BY-SA 4.0" },
  },
  {
    id: "miho-no-matsubara", name: "三保松原", region: "中部", prefecture: "静岡県",
    categories: ["絶景", "歴史"],
    description: "羽衣伝説の松原越しに富士山を望む世界文化遺産。白砂青松と駿河湾のパノラマは浮世絵の世界そのもの。",
    bestSeason: "11〜2月(富士がよく見える)", stayTime: "約1時間30分", access: "清水駅からバスで約25分",
    nearby: [], mapQuery: "三保松原",
    photo: { file: "Miho no Matsubara 14.jpg", author: "Motokoka", license: "CC BY-SA 4.0" },
  },
  {
    id: "nagoya-castle", name: "名古屋城", region: "中部", prefecture: "愛知県",
    categories: ["歴史"],
    description: "金鯱が輝く尾張徳川家の居城。豪華絢爛な本丸御殿の復元障壁画は必見。金シャチ横丁でグルメも。",
    bestSeason: "通年", stayTime: "約2時間", access: "地下鉄名古屋城駅からすぐ",
    nearby: ["inuyama-castle", "atsuta-jingu", "osu"], mapQuery: "名古屋城",
    photo: { file: "Nagoya Castle(Larger).jpg", author: "Base64", license: "CC BY-SA 3.0" },
  },
  {
    id: "inuyama-castle", name: "犬山城と城下町", region: "中部", prefecture: "愛知県",
    categories: ["歴史", "街歩き", "グルメ"],
    description: "木曽川を見下ろす国宝天守と、食べ歩きグルメで賑わう城下町。天守最上階からの眺めは殿様気分。",
    bestSeason: "通年", stayTime: "約3時間", access: "犬山駅から徒歩約20分",
    nearby: ["nagoya-castle"], mapQuery: "犬山城",
    photo: { file: "Castle in Inuyama.JPG", author: "ThorstenS", license: "CC BY-SA 3.0" },
  },

  {
    id: "yahiko-shrine", name: "彌彦神社", region: "中部", prefecture: "新潟県",
    categories: ["歴史", "自然"],
    description: "2400年の歴史を持つ越後一宮。弥彦山ロープウェイで山頂へ上がれば越後平野と日本海の大パノラマ。",
    bestSeason: "10〜11月", stayTime: "約2時間", access: "弥彦駅から徒歩約15分",
    nearby: [], mapQuery: "彌彦神社",
    photo: { file: "上諏訪神社（彌彦神社末社）.jpg", author: "Bernie Ongewe", license: "CC BY-SA 4.0" },
  },
  {
    id: "echigo-yuzawa", name: "越後湯沢温泉", region: "中部", prefecture: "新潟県",
    categories: ["温泉", "グルメ"],
    description: "川端康成『雪国』の舞台となった温泉地。駅構内の「ぽんしゅ館」では新潟ほぼ全蔵の日本酒を利き酒できる。",
    bestSeason: "12〜3月", stayTime: "半日", access: "越後湯沢駅から徒歩すぐ",
    nearby: [], mapQuery: "越後湯沢温泉",
    photo: { file: "Yuzawa onsen street near skiing front.jpg", author: "Syced", license: "CC0" },
  },
  {
    id: "kurobe-gorge", name: "黒部峡谷トロッコ電車", region: "中部", prefecture: "富山県",
    categories: ["絶景", "自然"],
    description: "日本一深いV字峡谷を窓のないトロッコ電車で進む。眼下の黒部川と一面の紅葉は圧巻。",
    bestSeason: "10〜11月", stayTime: "半日", access: "宇奈月温泉駅すぐの宇奈月駅から乗車",
    nearby: [], mapQuery: "黒部峡谷鉄道 宇奈月駅",
    photo: { file: "Kurobe-Gorge-railway-bridges-2019-Luka-Peternel.jpg", author: "Luka Peternel", license: "CC BY-SA 4.0" },
  },
  {
    id: "amaharashi", name: "雨晴海岸", region: "中部", prefecture: "富山県",
    categories: ["絶景"],
    description: "富山湾越しに3000m級の立山連峰を望む奇跡の風景。冬の朝に海面から気嵐が立つと幻想的。",
    bestSeason: "11〜2月", stayTime: "約1時間", access: "雨晴駅から徒歩約5分",
    nearby: [], mapQuery: "雨晴海岸",
    photo: { file: "雨晴海岸（女岩・立山連峰）20250215-IMG 2822.jpg", author: "くろふね", license: "CC BY 4.0" },
  },
  {
    id: "higashi-chaya", name: "金沢・ひがし茶屋街", region: "中部", prefecture: "石川県",
    categories: ["街歩き", "歴史", "グルメ"],
    description: "出格子の茶屋建築が連なる金沢随一の風情。金箔ソフトや町家カフェの食べ歩きも楽しい。",
    bestSeason: "通年", stayTime: "約2時間", access: "金沢駅からバスで約10分",
    nearby: ["kenrokuen", "omicho-market"], mapQuery: "ひがし茶屋街",
    photo: { file: "Higashi Chaya district, Kanazawa (3810720612).jpg", author: "Andrea Schaffer", license: "CC BY 2.0" },
  },
  {
    id: "omicho-market", name: "近江町市場", region: "中部", prefecture: "石川県",
    categories: ["グルメ", "街歩き"],
    description: "約170店が並ぶ「金沢市民の台所」。カニ・甘エビ・のどぐろ、海鮮丼の名店には朝から行列ができる。",
    bestSeason: "11〜2月", stayTime: "約1時間30分", access: "金沢駅から徒歩約15分",
    nearby: ["kenrokuen", "higashi-chaya"], mapQuery: "近江町市場",
    photo: { file: "Kanazawa Omicho Market, Japan (48876956676).jpg", author: "dconvertini", license: "CC BY-SA 2.0" },
  },
  {
    id: "wakura-onsen", name: "和倉温泉", region: "中部", prefecture: "石川県",
    categories: ["温泉"],
    description: "七尾湾に面した「海の温泉」。開湯1200年、湯めぐりと能登の海の幸が自慢。",
    bestSeason: "通年", stayTime: "半日", access: "和倉温泉駅から車で約5分",
    nearby: [], mapQuery: "和倉温泉",
    photo: { file: "Wakura View.JPG", author: "Jpatokal", license: "CC BY-SA 4.0" },
  },
  {
    id: "mikatagoko", name: "三方五湖レインボーライン", region: "中部", prefecture: "福井県",
    categories: ["絶景", "自然"],
    description: "五つの湖がそれぞれ違う青に見える絶景ドライブウェイ。山頂公園の足湯とテラスから一望できる。",
    bestSeason: "4〜11月", stayTime: "約2時間", access: "三方駅から車で約15分",
    nearby: [], mapQuery: "三方五湖レインボーライン 山頂公園",
    photo: { file: "Lainbow Line Summit Park ac (1).jpg", author: "Asturio Cantabrio", license: "CC BY-SA 4.0" },
  },
  {
    id: "echizen-ono-castle", name: "越前大野城", region: "中部", prefecture: "福井県",
    categories: ["絶景", "歴史"],
    description: "秋から冬の明け方、雲海に浮かぶ「天空の城」。城下町は名水の里で、400年続く朝市も。",
    bestSeason: "10〜4月", stayTime: "約2時間", access: "越前大野駅から徒歩約30分",
    nearby: ["eiheiji"], mapQuery: "越前大野城",
    photo: { file: "EchizenOnoCastle-01.JPG", author: "User:Ajax", license: "CC BY-SA 3.0" },
  },
  {
    id: "arakurayama-sengen", name: "新倉山浅間公園", region: "中部", prefecture: "山梨県",
    categories: ["絶景", "歴史"],
    description: "五重塔と桜越しに富士山を望む、海外で最も有名な日本の風景のひとつ。398段の階段を上った先に絶景が待つ。",
    bestSeason: "4月", stayTime: "約1時間30分", access: "下吉田駅から徒歩約20分",
    nearby: ["kawaguchiko", "oshino-hakkai"], mapQuery: "新倉山浅間公園",
    photo: { file: "Mt Fuji and Tyureito pagoda 1.jpg", author: "Hrykt", license: "CC0" },
  },
  {
    id: "hottarakashi-onsen", name: "ほったらかし温泉", region: "中部", prefecture: "山梨県",
    categories: ["温泉", "絶景"],
    description: "標高700mから甲府盆地と富士山を見下ろす絶景露天風呂。日の出の1時間前に開く朝湯が名物。",
    bestSeason: "通年", stayTime: "約2時間", access: "山梨市駅から車で約10分",
    nearby: [], mapQuery: "ほったらかし温泉",
    photo: { file: "ほったらかし温泉.JPG", author: "kaidog", license: "CC0" },
  },
  {
    id: "zenkoji", name: "善光寺", region: "中部", prefecture: "長野県",
    categories: ["歴史"],
    description: "「一生に一度は善光寺参り」と親しまれる無宗派の古刹。真っ暗な回廊を進むお戒壇めぐりは必体験。",
    bestSeason: "通年", stayTime: "約2時間", access: "長野駅からバスで約10分",
    nearby: ["jigokudani-yaen"], mapQuery: "善光寺",
    photo: { file: "Zenko-ji (Bunkyo).JPG", author: "Abasaa", license: "Public domain" },
  },
  {
    id: "jigokudani-yaen", name: "地獄谷野猿公苑", region: "中部", prefecture: "長野県",
    categories: ["自然"],
    description: "温泉に浸かるニホンザル「スノーモンキー」を間近で観察できる世界で唯一の場所。",
    bestSeason: "12〜3月", stayTime: "約2時間", access: "湯田中駅からバスと徒歩で約1時間",
    nearby: ["zenkoji"], mapQuery: "地獄谷野猿公苑",
    photo: { file: "Macaca fuscata meditation.jpg", author: "Daisuke tashiro from Japan", license: "CC BY-SA 2.0" },
  },
  {
    id: "narai-juku", name: "奈良井宿", region: "中部", prefecture: "長野県",
    categories: ["歴史", "街歩き"],
    description: "中山道の宿場町として日本最長、約1kmの町並みが残る。漆器と五平餅、木曽路の風情をそぞろ歩き。",
    bestSeason: "4〜11月", stayTime: "約2時間", access: "奈良井駅から徒歩すぐ",
    nearby: ["matsumoto-castle"], mapQuery: "奈良井宿",
    photo: { file: "Narai-juku-facing-north-east-2019-Luka-Peternel.jpg", author: "Luka Peternel", license: "CC BY-SA 4.0" },
  },
  {
    id: "gero-onsen", name: "下呂温泉", region: "中部", prefecture: "岐阜県",
    categories: ["温泉", "街歩き"],
    description: "日本三名泉に数えられる「美人の湯」。温泉街には無料の足湯が点在し、湯めぐり手形で名湯をはしごできる。",
    bestSeason: "通年", stayTime: "半日", access: "下呂駅から徒歩すぐ",
    nearby: ["takayama"], mapQuery: "下呂温泉",
    photo: { file: "Gero OnsenTown.JPG", author: "Jpatokal", license: "CC BY-SA 3.0" },
  },
  {
    id: "gujo-hachiman", name: "郡上八幡", region: "中部", prefecture: "岐阜県",
    categories: ["街歩き", "歴史"],
    description: "町中に水路が巡る「水のまち」。夏の郡上おどりは32夜続き、お盆の徹夜おどりで最高潮を迎える。",
    bestSeason: "7〜8月", stayTime: "約2時間", access: "郡上八幡駅から徒歩約20分",
    nearby: [], mapQuery: "郡上八幡",
    photo: { file: "郡上八幡城から見た町並み (岐阜県郡上市八幡町) - panoramio.jpg", author: "gundam2345", license: "CC BY 3.0" },
  },
  {
    id: "shuzenji-onsen", name: "修善寺温泉", region: "中部", prefecture: "静岡県",
    categories: ["温泉", "歴史", "街歩き"],
    description: "伊豆最古の温泉場。竹林の小径と朱塗りの桂橋、川の中に湧く「独鈷の湯」が旅情を誘う。",
    bestSeason: "11月", stayTime: "半日", access: "修善寺駅からバスで約10分",
    nearby: ["jogasaki"], mapQuery: "修善寺温泉",
    photo: { file: "181124 Shuzenji Onsen Izu Shizuoka pref Japan01s3.jpg", author: "663highland", license: "CC BY-SA 4.0" },
  },
  {
    id: "jogasaki", name: "城ヶ崎海岸", region: "中部", prefecture: "静岡県",
    categories: ["絶景", "自然"],
    description: "溶岩が作った断崖絶壁の海岸線。高さ23mの海の吊り橋「門脇つり橋」はスリル満点。",
    bestSeason: "通年", stayTime: "約2時間", access: "伊豆高原駅から徒歩約35分",
    nearby: ["atami-onsen", "shuzenji-onsen"], mapQuery: "城ヶ崎海岸 門脇つり橋",
    photo: { file: "Jōgasaki -Kadowaki Bridge 01.jpg", author: "Takuya ASADA", license: "CC BY 2.0" },
  },
  {
    id: "atsuta-jingu", name: "熱田神宮", region: "中部", prefecture: "愛知県",
    categories: ["歴史"],
    description: "三種の神器・草薙神剣を祀る格式高い社。門前のひつまぶしの名店も参拝とセットで人気。",
    bestSeason: "通年", stayTime: "約1時間30分", access: "神宮前駅から徒歩約3分",
    nearby: ["nagoya-castle"], mapQuery: "熱田神宮",
    photo: { file: "Atsuta-jingū (Atsuta-ku, Nagoya) VLux5 hdsr sc05.jpg", author: "Hyppolyte de Saint-Rambert", license: "CC BY 4.0" },
  },
  {
    id: "osu", name: "大須商店街", region: "中部", prefecture: "愛知県",
    categories: ["街歩き", "グルメ"],
    description: "大須観音の門前に約1200店。電気街・古着・食べ歩きが混ざり合う名古屋のカオスな台所。",
    bestSeason: "通年", stayTime: "約2時間", access: "大須観音駅から徒歩すぐ",
    nearby: ["nagoya-castle"], mapQuery: "大須商店街",
    photo: { file: "大須商店街IMG 20220316 161800 03.jpg", author: "経済特区", license: "CC BY-SA 4.0" },
  },
  // ---- 近畿 ----
  {
    id: "ise-jingu", name: "伊勢神宮", region: "近畿", prefecture: "三重県",
    categories: ["歴史", "グルメ", "街歩き"],
    description: "「お伊勢さん」と親しまれる日本の総氏神。参拝後はおかげ横丁で伊勢うどんや赤福を。",
    bestSeason: "通年", stayTime: "約3時間", access: "五十鈴川駅からバスで約6分",
    nearby: ["meoto-iwa", "okage-yokocho"], mapQuery: "伊勢神宮 内宮",
    photo: { file: "伊勢神宮内宮 IseJingu-Naiku (48967647226).jpg", author: "nobu3withfoxy from Iga,Mie, Japan", license: "CC BY 2.0" },
  },
  {
    id: "meoto-iwa", name: "二見興玉神社・夫婦岩", region: "近畿", prefecture: "三重県",
    categories: ["歴史", "絶景"],
    description: "大注連縄で結ばれた大小の岩が沖に浮かぶ縁結びの聖地。5〜7月は岩の間から昇る朝日が拝める。",
    bestSeason: "5〜7月", stayTime: "約1時間", access: "二見浦駅から徒歩約15分",
    nearby: ["ise-jingu", "okage-yokocho"], mapQuery: "夫婦岩 二見興玉神社",
    photo: { file: "Meoto Iwa rocks (scan 2023).jpg", author: "Pierre André Leclercq", license: "CC BY-SA 4.0" },
  },
  {
    id: "hikone-castle", name: "彦根城", region: "近畿", prefecture: "滋賀県",
    categories: ["歴史"],
    description: "琵琶湖を望む国宝の現存天守。玄宮園からの借景と、ゆるキャラの元祖ひこにゃんにも会える。",
    bestSeason: "通年", stayTime: "約2時間", access: "彦根駅から徒歩約15分",
    nearby: [], mapQuery: "彦根城",
    photo: { file: "Hikone castle5537.JPG", author: "日:Jnn", license: "CC BY 2.1 jp" },
  },
  {
    id: "shirahige-shrine", name: "白鬚神社", region: "近畿", prefecture: "滋賀県",
    categories: ["絶景", "歴史"],
    description: "琵琶湖の湖中に朱の大鳥居が立つ「近江の厳島」。朝焼けや月夜に浮かぶ鳥居は息をのむ美しさ。",
    bestSeason: "通年", stayTime: "約30分", access: "近江高島駅から車で約5分",
    nearby: [], mapQuery: "白鬚神社 滋賀",
    photo: { file: "Shirahige shrine , 白鬚神社 - panoramio.jpg", author: "z tanuki", license: "CC BY 3.0" },
  },
  {
    id: "fushimi-inari", name: "伏見稲荷大社", region: "近畿", prefecture: "京都府",
    categories: ["歴史", "絶景"],
    description: "山頂まで続く千本鳥居はここでしか見られない光景。早朝の参拝が狙い目。",
    bestSeason: "通年", stayTime: "約2時間", access: "JR稲荷駅からすぐ",
    nearby: ["arashiyama", "kinkakuji", "kiyomizudera"], mapQuery: "伏見稲荷大社",
    photo: { file: "Torii path with lantern at Fushimi Inari Taisha Shrine, Kyoto, Japan.jpg", author: "Basile Morin", license: "CC BY-SA 4.0" },
  },
  {
    id: "arashiyama", name: "嵐山", region: "近畿", prefecture: "京都府",
    categories: ["自然", "街歩き", "グルメ"],
    description: "渡月橋と竹林の小径で知られる京都屈指の景勝地。トロッコ列車や保津川下りも楽しめる。",
    bestSeason: "11月", stayTime: "半日", access: "嵐山駅からすぐ",
    nearby: ["kinkakuji", "fushimi-inari"], mapQuery: "嵐山 渡月橋",
    photo: { file: "愛宕山からの嵐山・渡月橋.jpg", author: "Koda6029", license: "CC BY-SA 4.0" },
  },
  {
    id: "kinkakuji", name: "金閣寺", region: "近畿", prefecture: "京都府",
    categories: ["歴史", "絶景"],
    description: "鏡湖池に金色の楼閣が映える京都の代名詞。雪化粧の朝の金閣は一生ものの光景。",
    bestSeason: "通年", stayTime: "約1時間", access: "京都駅からバスで約40分",
    nearby: ["arashiyama"], mapQuery: "金閣寺",
    photo: { file: "Water reflection of Kinkaku-ji Temple a sunny day, Kyoto, Japan.jpg", author: "Basile Morin", license: "CC BY-SA 4.0" },
  },
  {
    id: "nara-park", name: "奈良公園・東大寺", region: "近畿", prefecture: "奈良県",
    categories: ["歴史", "自然"],
    description: "大仏殿と、園内を自由に歩き回る約1200頭の鹿。春日大社や興福寺も徒歩圏内。",
    bestSeason: "通年", stayTime: "約3時間", access: "近鉄奈良駅から徒歩約5分",
    nearby: ["horyuji"], mapQuery: "奈良公園",
    photo: { file: "Nara Park - panoramio (2).jpg", author: "Feri88", license: "CC BY 3.0" },
  },
  {
    id: "yoshinoyama", name: "吉野山", region: "近畿", prefecture: "奈良県",
    categories: ["絶景", "自然", "歴史"],
    description: "「一目千本」と讃えられる日本一の桜の名所。約3万本の山桜が下千本から奥千本へと咲き上がる。",
    bestSeason: "4月", stayTime: "半日", access: "吉野駅からロープウェイ",
    nearby: ["asuka"], mapQuery: "吉野山 中千本",
    photo: { file: "吉野山 中千本公園 2014.4.15 - panoramio.jpg", author: "Nankou Oronain (as36…", license: "CC BY-SA 3.0" },
  },
  {
    id: "dotonbori", name: "道頓堀", region: "近畿", prefecture: "大阪府",
    categories: ["グルメ", "街歩き"],
    description: "グリコ看板とネオンきらめく大阪ミナミの中心地。たこ焼き・串カツなど食い倒れの街。",
    bestSeason: "通年", stayTime: "約3時間", access: "なんば駅から徒歩約5分",
    nearby: ["osaka-castle", "shinsekai"], mapQuery: "道頓堀",
    photo: { file: "Dōtonbori Canal 1.jpg", author: "Zest", license: "CC BY-SA 4.0" },
  },
  {
    id: "osaka-castle", name: "大阪城", region: "近畿", prefecture: "大阪府",
    categories: ["歴史"],
    description: "豊臣秀吉が築いた天下の名城。巨石の石垣と広大な公園は都心のオアシスで、春は桜の名所になる。",
    bestSeason: "通年", stayTime: "約2時間", access: "大阪城公園駅から徒歩約15分",
    nearby: ["dotonbori"], mapQuery: "大阪城天守閣",
    photo: { file: "Osaka Castle 02bs3200.jpg", author: "663highland", license: "CC BY 2.5" },
  },
  {
    id: "himeji-castle", name: "姫路城", region: "近畿", prefecture: "兵庫県",
    categories: ["歴史", "絶景"],
    description: "白鷺城の名を持つ日本初の世界文化遺産。現存天守の白壁の美しさは別格。",
    bestSeason: "通年", stayTime: "約2時間30分", access: "姫路駅から徒歩約20分",
    nearby: [], mapQuery: "姫路城",
    photo: { file: "Château de Himeji02.jpg", author: "Bernard Gagnon", license: "CC BY-SA 3.0" },
  },
  {
    id: "kinosaki-onsen", name: "城崎温泉", region: "近畿", prefecture: "兵庫県",
    categories: ["温泉", "街歩き", "グルメ"],
    description: "柳並木の川沿いを浴衣と下駄で歩く外湯めぐりの温泉街。冬は松葉ガニの本場としても名高い。",
    bestSeason: "11〜3月", stayTime: "1泊", access: "城崎温泉駅から徒歩すぐ",
    nearby: ["takeda-castle"], mapQuery: "城崎温泉",
    photo: { file: "Kinosaki Onsen Otani River 2026-02 ac (2).jpg", author: "Asturio Cantabrio", license: "CC BY-SA 4.0" },
  },
  {
    id: "shirahama", name: "南紀白浜・白良浜", region: "近畿", prefecture: "和歌山県",
    categories: ["絶景", "温泉"],
    description: "真っ白な砂浜と青い海が続く関西屈指のリゾート。日本三古湯の白浜温泉と円月島の夕日も見どころ。",
    bestSeason: "6〜9月", stayTime: "半日〜1泊", access: "白浜駅からバスで約15分",
    nearby: [], mapQuery: "白良浜",
    photo: { file: "白良浜 - panoramio.jpg", author: "米田賢一", license: "CC BY 3.0" },
  },
  {
    id: "nachi-falls", name: "那智の滝・熊野那智大社", region: "近畿", prefecture: "和歌山県",
    categories: ["歴史", "絶景", "自然"],
    description: "落差133m・日本一の名瀑と朱の三重塔が並ぶ熊野信仰の聖地。大門坂の石畳から歩いて詣でたい。",
    bestSeason: "通年", stayTime: "約3時間", access: "紀伊勝浦駅からバスで約30分",
    nearby: ["kumano-kodo"], mapQuery: "那智の滝",
    photo: { file: "那智の滝2 - panoramio.jpg", author: "baggio4ever", license: "CC BY 3.0" },
  },

  {
    id: "okage-yokocho", name: "おかげ横丁", region: "近畿", prefecture: "三重県",
    categories: ["グルメ", "街歩き"],
    description: "伊勢神宮内宮前、おはらい町の中心で江戸〜明治の伊勢路を再現。赤福本店に伊勢うどん、食べ歩き天国。",
    bestSeason: "通年", stayTime: "約2時間", access: "伊勢市駅からバスで約15分",
    nearby: ["ise-jingu", "meoto-iwa"], mapQuery: "おかげ横丁",
    photo: { file: "Okage Yokocho02-r.jpg", author: "Oilstreet", license: "CC BY 2.5" },
  },
  {
    id: "enryakuji", name: "比叡山延暦寺", region: "近畿", prefecture: "滋賀県",
    categories: ["歴史", "自然"],
    description: "最澄が開き、1200年「不滅の法灯」が灯り続ける天台宗の総本山。世界遺産の山全体が修行の場。",
    bestSeason: "10〜11月", stayTime: "半日", access: "京都駅から電車とケーブルで約1時間",
    nearby: [], mapQuery: "比叡山延暦寺",
    photo: { file: "比叡山延暦寺 - panoramio (1).jpg", author: "baggio4ever", license: "CC BY 3.0" },
  },
  {
    id: "kiyomizudera", name: "清水寺", region: "近畿", prefecture: "京都府",
    categories: ["歴史", "街歩き"],
    description: "「清水の舞台」から京都市街を一望する世界遺産。二年坂・三年坂の参道歩きも旅の醍醐味。",
    bestSeason: "4月・11月", stayTime: "約2時間", access: "京都駅からバスと徒歩で約25分",
    nearby: ["gion", "fushimi-inari"], mapQuery: "清水寺",
    photo: { file: "Four ladies wearing a yukata in front of the North Gate of Kiyomizu-dera temple Kyoto Japan.jpg", author: "Basile Morin", license: "CC BY-SA 4.0" },
  },
  {
    id: "gion", name: "祇園・花見小路", region: "近畿", prefecture: "京都府",
    categories: ["街歩き", "歴史"],
    description: "お茶屋が連なる石畳の花街。夕暮れどきには舞妓さんに出会えることも。",
    bestSeason: "通年", stayTime: "約1時間30分", access: "祇園四条駅から徒歩約5分",
    nearby: ["kiyomizudera", "nishiki-market"], mapQuery: "祇園 花見小路",
    photo: { file: "Kyoto, cleaning ladies 2.jpg", author: "Marie-Sophie Mejan", license: "CC BY 4.0" },
  },
  {
    id: "nishiki-market", name: "錦市場", region: "近畿", prefecture: "京都府",
    categories: ["グルメ", "街歩き"],
    description: "400年の歴史を持つ「京の台所」。約130店の京漬物・湯葉・豆乳ドーナツを食べ歩き。",
    bestSeason: "通年", stayTime: "約1時間30分", access: "烏丸駅から徒歩約3分",
    nearby: ["gion"], mapQuery: "錦市場",
    photo: { file: "Tsukemono shop by collinox in Nishiki Ichiba, Kyoto.jpg", author: "collinox", license: "CC BY 2.0" },
  },
  {
    id: "amanohashidate", name: "天橋立", region: "近畿", prefecture: "京都府",
    categories: ["絶景"],
    description: "日本三景のひとつ、全長3.6kmの砂州。展望所から「股のぞき」で見ると天に架かる橋のよう。",
    bestSeason: "通年", stayTime: "半日", access: "天橋立駅から徒歩すぐ",
    nearby: ["ine-funaya"], mapQuery: "天橋立",
    photo: { file: "Amanohashidate view from Kasamatsu Park01s3s4410.jpg", author: "663highland", license: "CC BY 2.5" },
  },
  {
    id: "ine-funaya", name: "伊根の舟屋", region: "近畿", prefecture: "京都府",
    categories: ["街歩き", "絶景"],
    description: "海の上に約230軒の舟屋が並ぶ漁村。海上タクシーから見る町並みはまるで水上都市。",
    bestSeason: "通年", stayTime: "約2時間", access: "天橋立駅からバスで約1時間",
    nearby: ["amanohashidate"], mapQuery: "伊根の舟屋",
    photo: { file: "Funaya in Ine Town, Yosa District, Kyoto Prefecture 003.jpg", author: "Naokijp", license: "CC BY-SA 4.0" },
  },
  {
    id: "horyuji", name: "法隆寺", region: "近畿", prefecture: "奈良県",
    categories: ["歴史"],
    description: "現存する世界最古の木造建築群。五重塔と百済観音、教科書で見た飛鳥の世界を歩く。",
    bestSeason: "通年", stayTime: "約2時間", access: "法隆寺駅から徒歩約20分",
    nearby: ["nara-park"], mapQuery: "法隆寺",
    photo: { file: "Horyu-ji10s3200.jpg", author: "663highland", license: "CC BY 2.5" },
  },
  {
    id: "hasedera", name: "長谷寺", region: "近畿", prefecture: "奈良県",
    categories: ["歴史", "絶景"],
    description: "399段の登廊を上る「花の御寺」。牡丹にあじさい、紅葉と、四季の花に埋もれる山寺。",
    bestSeason: "4〜6月", stayTime: "約2時間", access: "長谷寺駅から徒歩約15分",
    nearby: [], mapQuery: "奈良 長谷寺",
    photo: { file: "Hasedera Sakurai Nara pref58s5s4272.jpg", author: "663highland", license: "CC BY 2.5" },
  },
  {
    id: "asuka", name: "明日香村", region: "近畿", prefecture: "奈良県",
    categories: ["歴史", "自然"],
    description: "石舞台古墳や高松塚古墳が田園に点在する日本の原風景。レンタサイクルで飛鳥時代をめぐる。",
    bestSeason: "3〜5月・9〜11月", stayTime: "半日", access: "飛鳥駅から自転車で各所へ",
    nearby: ["yoshinoyama"], mapQuery: "石舞台古墳",
    photo: { file: "Ishibutai-kofun Asuka Nara pref05n4592.jpg", author: "663highland", license: "CC BY 2.5" },
  },
  {
    id: "shinsekai", name: "新世界・通天閣", region: "近畿", prefecture: "大阪府",
    categories: ["街歩き", "グルメ"],
    description: "串カツにどて焼き、ド派手な看板。通天閣を中心に昭和レトロ全開の大阪ディープゾーン。",
    bestSeason: "通年", stayTime: "約2時間", access: "恵美須町駅から徒歩約3分",
    nearby: ["dotonbori"], mapQuery: "新世界 通天閣",
    photo: { file: "Tsutenkaku and Shinsekai at night 20110122.jpg", author: "Shift", license: "CC BY-SA 3.0" },
  },
  {
    id: "minoo-falls", name: "箕面大滝", region: "近畿", prefecture: "大阪府",
    categories: ["自然", "絶景"],
    description: "大阪市内から電車で30分で行ける落差33mの名瀑。滝道の紅葉と名物「もみじの天ぷら」が秋の風物詩。",
    bestSeason: "11月", stayTime: "約2時間", access: "箕面駅から徒歩約40分",
    nearby: [], mapQuery: "箕面大滝",
    photo: { file: "Minoh Falls Minoh Osaka pref Japan08s3.jpg", author: "663highland", license: "CC BY 2.5" },
  },
  {
    id: "arima-onsen", name: "有馬温泉", region: "近畿", prefecture: "兵庫県",
    categories: ["温泉", "街歩き"],
    description: "太閤秀吉も愛した日本三古湯。鉄分で赤褐色に濁る「金泉」と無色透明の「銀泉」を湯めぐり。",
    bestSeason: "通年", stayTime: "半日", access: "神戸電鉄有馬温泉駅から徒歩約5分",
    nearby: [], mapQuery: "有馬温泉",
    photo: { file: "170811 Rokko-Arima Ropeway Kobe Japan00n.jpg", author: "663highland", license: "CC BY 2.5" },
  },
  {
    id: "takeda-castle", name: "竹田城跡", region: "近畿", prefecture: "兵庫県",
    categories: ["絶景", "歴史"],
    description: "秋の明け方、雲海に浮かぶ「天空の城」。向かいの立雲峡から望む石垣のシルエットは息をのむ。",
    bestSeason: "9〜11月", stayTime: "約2時間", access: "竹田駅から天空バスで約20分",
    nearby: ["kinosaki-onsen"], mapQuery: "竹田城跡",
    photo: { file: "20130507 takeda castle 10.jpg", author: "Baku13", license: "CC BY-SA 3.0" },
  },
  {
    id: "koyasan", name: "高野山", region: "近畿", prefecture: "和歌山県",
    categories: ["歴史", "自然"],
    description: "空海が開いた標高800mの宗教都市。奥之院の杉木立、宿坊の精進料理と朝のお勤めで心が整う。",
    bestSeason: "5〜11月", stayTime: "1日", access: "極楽橋駅からケーブルで約5分",
    nearby: [], mapQuery: "高野山 奥之院",
    photo: { file: "高野山 根本大塔1 Koyasan (Mount Koya) - panoramio.jpg", author: "baggio4ever", license: "CC BY 3.0" },
  },
  {
    id: "kumano-kodo", name: "熊野古道・大門坂", region: "近畿", prefecture: "和歌山県",
    categories: ["歴史", "自然"],
    description: "樹齢800年の杉並木に苔むした石畳が続く熊野詣の道。大門坂から那智の滝まで、聖地への約2.5kmを歩く。",
    bestSeason: "3〜5月・10〜11月", stayTime: "約2時間", access: "紀伊勝浦駅からバスで約20分",
    nearby: ["nachi-falls"], mapQuery: "熊野古道 大門坂",
    photo: { file: "Kumano Kodo pilgrimage route Daimon-zaka World heritage 熊野古道 大門坂03.JPG", author: "Nekosuki", license: "CC BY-SA 4.0" },
  },
  // ---- 中国 ----
  {
    id: "tottori-sakyu", name: "鳥取砂丘", region: "中国", prefecture: "鳥取県",
    categories: ["絶景", "自然"],
    description: "日本最大級の砂丘。ラクダ遊覧やサンドボードも体験でき、隣接の砂の美術館も見応えあり。",
    bestSeason: "通年", stayTime: "約2時間", access: "鳥取駅からバスで約20分",
    nearby: [], mapQuery: "鳥取砂丘",
    photo: { file: "Tottori-Sakyu Tottori Japan.JPG", author: "Hashi photo", license: "CC BY-SA 3.0" },
  },
  {
    id: "mizuki-shigeru-road", name: "水木しげるロード", region: "中国", prefecture: "鳥取県",
    categories: ["街歩き", "グルメ"],
    description: "177体の妖怪ブロンズ像が並ぶ境港の商店街。夜は妖怪影絵が路面に浮かび、昼と別の顔を見せる。",
    bestSeason: "通年", stayTime: "約2時間", access: "境港駅からすぐ",
    nearby: [], mapQuery: "水木しげるロード",
    photo: { file: "Mizuki shigeru road , 水木しげるロード - panoramio.jpg", author: "z tanuki", license: "CC BY 3.0" },
  },
  {
    id: "izumo-taisha", name: "出雲大社", region: "中国", prefecture: "島根県",
    categories: ["歴史"],
    description: "縁結びの神様として名高い古社。巨大なしめ縄は迫力満点。門前町の出雲そばも名物。",
    bestSeason: "通年", stayTime: "約2時間", access: "出雲市駅からバスで約25分",
    nearby: ["adachi-museum", "matsue-castle", "tamatsukuri-onsen"], mapQuery: "出雲大社",
    photo: { file: "Haiden of Izumo-taisha-1.JPG", author: "Saigen Jiro", license: "CC0" },
  },
  {
    id: "adachi-museum", name: "足立美術館", region: "中国", prefecture: "島根県",
    categories: ["絶景", "歴史"],
    description: "「生きた日本画」と称される庭園が米誌の日本庭園ランキングで連続日本一。横山大観コレクションも必見。",
    bestSeason: "通年", stayTime: "約2時間", access: "安来駅から無料シャトルバスで約20分",
    nearby: ["izumo-taisha", "matsue-castle"], mapQuery: "足立美術館",
    photo: { file: "Adachi Museum of Art Garden.jpg", author: "Bernard Gagnon", license: "CC BY-SA 3.0" },
  },
  {
    id: "kurashiki", name: "倉敷美観地区", region: "中国", prefecture: "岡山県",
    categories: ["街歩き", "歴史"],
    description: "白壁の蔵屋敷と柳並木が続く運河の町。川舟流しやデニムストリートの散策が楽しい。",
    bestSeason: "通年", stayTime: "約3時間", access: "倉敷駅から徒歩約15分",
    nearby: ["korakuen", "bitchu-matsuyama-castle"], mapQuery: "倉敷美観地区",
    photo: { file: "倉敷美観地区にて Kurashiki Bikan historical quarter 2009.8.24 - panoramio.jpg", author: "Nankou Oronain (as36…", license: "CC BY-SA 3.0" },
  },
  {
    id: "korakuen", name: "岡山後楽園", region: "中国", prefecture: "岡山県",
    categories: ["歴史", "自然"],
    description: "岡山城を借景にした日本三名園のひとつ。広々とした芝生と曲水が生む開放感は他の名園にない魅力。",
    bestSeason: "通年", stayTime: "約1時間30分", access: "岡山駅からバスで約15分",
    nearby: ["kurashiki"], mapQuery: "岡山後楽園",
    photo: { file: "Korakuen Okayama26s3872.jpg", author: "663highland", license: "CC BY 2.5" },
  },
  {
    id: "itsukushima", name: "厳島神社", region: "中国", prefecture: "広島県",
    categories: ["歴史", "絶景"],
    description: "海に浮かぶ大鳥居で知られる世界遺産。干潮時は鳥居まで歩ける。宮島名物のあなご飯ももみじ饅頭も。",
    bestSeason: "通年", stayTime: "約3時間", access: "宮島口からフェリーで約10分",
    nearby: ["genbaku-dome"], mapQuery: "厳島神社",
    photo: { file: "Itsukushima Gate.jpg", author: "JordyMeow", license: "CC BY-SA 3.0" },
  },
  {
    id: "genbaku-dome", name: "原爆ドーム・平和記念公園", region: "中国", prefecture: "広島県",
    categories: ["歴史"],
    description: "核兵器の惨禍を今に伝える世界遺産。資料館とあわせて、静かに平和への祈りを捧げたい場所。",
    bestSeason: "通年", stayTime: "約2時間", access: "広島駅から路面電車で約15分",
    nearby: ["itsukushima"], mapQuery: "原爆ドーム",
    photo: { file: "Genbaku Dome04-r.JPG", author: "Oilstreet", license: "CC BY 2.5" },
  },
  {
    id: "onomichi", name: "尾道", region: "中国", prefecture: "広島県",
    categories: ["街歩き", "絶景", "グルメ"],
    description: "坂と猫と寺の町。千光寺からの尾道水道の眺め、路地歩き、尾道ラーメンと楽しみが詰まっている。",
    bestSeason: "通年", stayTime: "半日", access: "尾道駅から徒歩すぐ",
    nearby: ["shimanami-kaido", "okunoshima"], mapQuery: "千光寺公園",
    photo: { file: "Senkoji-koen sakura.JPG", author: "アラツク", license: "CC BY-SA 4.0" },
  },
  {
    id: "tsunoshima-bridge", name: "角島大橋", region: "中国", prefecture: "山口県",
    categories: ["絶景"],
    description: "エメラルドグリーンの海に一直線に伸びる約1780mの橋。ドライブの定番絶景スポット。",
    bestSeason: "5〜9月", stayTime: "約1時間", access: "新下関駅から車で約1時間",
    nearby: ["motonosumi-shrine"], mapQuery: "角島大橋",
    photo: { file: "角島大橋１.jpg", author: "吉田宅浪", license: "CC BY-SA 3.0" },
  },
  {
    id: "kintaikyo", name: "錦帯橋", region: "中国", prefecture: "山口県",
    categories: ["歴史", "絶景"],
    description: "5連の木造アーチが錦川に架かる日本三名橋のひとつ。桜と鵜飼の季節はひときわ絵になる。",
    bestSeason: "4月・6〜8月", stayTime: "約1時間30分", access: "岩国駅からバスで約20分",
    nearby: ["itsukushima"], mapQuery: "錦帯橋",
    photo: { file: "20100724 Iwakuni 5235.jpg", author: "Jakub Hałun", license: "CC BY-SA 4.0" },
  },
  {
    id: "motonosumi-shrine", name: "元乃隅神社", region: "中国", prefecture: "山口県",
    categories: ["絶景", "歴史"],
    description: "123基の朱鳥居が海へ向かって連なる絶景神社。日本一入れにくい賽銭箱(鳥居の上)にも挑戦を。",
    bestSeason: "通年", stayTime: "約1時間", access: "長門市駅から車で約20分",
    nearby: ["tsunoshima-bridge"], mapQuery: "元乃隅神社",
    photo: { file: "元乃隅稲荷神社 (33131861841).jpg", author: "yuki5287", license: "CC BY 2.0" },
  },

  {
    id: "misasa-onsen", name: "三朝温泉", region: "中国", prefecture: "鳥取県",
    categories: ["温泉", "街歩き"],
    description: "世界屈指のラドン泉。三徳川のせせらぎを聞きながら入る河原風呂と、レトロな温泉本通りが魅力。",
    bestSeason: "通年", stayTime: "半日", access: "倉吉駅からバスで約25分",
    nearby: [], mapQuery: "三朝温泉",
    photo: { file: "Misasa onsen kawaranoyu 202106.jpg", author: "三塚", license: "CC BY-SA 4.0" },
  },
  {
    id: "matsue-castle", name: "松江城", region: "中国", prefecture: "島根県",
    categories: ["歴史"],
    description: "全国に12しかない現存天守のひとつで国宝。堀川めぐりの小舟から眺める城下町も風情たっぷり。",
    bestSeason: "通年", stayTime: "約2時間", access: "松江駅からバスで約10分",
    nearby: ["izumo-taisha", "tamatsukuri-onsen", "adachi-museum"], mapQuery: "松江城",
    photo: { file: "Matsue castle01bs4592.jpg", author: "663highland", license: "CC BY 2.5" },
  },
  {
    id: "tamatsukuri-onsen", name: "玉造温泉", region: "中国", prefecture: "島根県",
    categories: ["温泉"],
    description: "『出雲国風土記』にも登場する美肌の湯。玉湯川沿いに勾玉の橋と足湯が並び、夜は灯りがともる。",
    bestSeason: "通年", stayTime: "半日", access: "玉造温泉駅から車で約5分",
    nearby: ["matsue-castle", "izumo-taisha"], mapQuery: "玉造温泉",
    photo: { file: "Tamatsukuri-onsen-matsue-japan-tamayu-river-and-hot-spring2.jpg", author: "Matsue", license: "CC BY-SA 4.0" },
  },
  {
    id: "bitchu-matsuyama-castle", name: "備中松山城", region: "中国", prefecture: "岡山県",
    categories: ["絶景", "歴史"],
    description: "標高430m、現存天守で最も高い場所に建つ山城。秋の朝は雲海に浮かぶ姿を展望台から狙える。",
    bestSeason: "9〜4月", stayTime: "約2時間", access: "備中高梁駅から乗合タクシーと徒歩で約30分",
    nearby: ["kurashiki"], mapQuery: "備中松山城",
    photo: { file: "Bitchu Matsuyama Castle 1.JPG", author: "by Reggaeman", license: "CC BY-SA 3.0" },
  },
  {
    id: "okunoshima", name: "大久野島", region: "中国", prefecture: "広島県",
    categories: ["自然"],
    description: "約500羽の野生のうさぎが暮らす「うさぎ島」。フェリーで15分、島一周は自転車で約1時間。",
    bestSeason: "通年", stayTime: "半日", access: "忠海港からフェリーで約15分",
    nearby: ["onomichi"], mapQuery: "大久野島",
    photo: { file: "Okunoshima 2.JPG", author: "Vickerman625", license: "Public domain" },
  },
  {
    id: "saijo-sakagura", name: "東広島・西条酒蔵通り", region: "中国", prefecture: "広島県",
    categories: ["グルメ", "街歩き"],
    description: "赤煉瓦の煙突と白壁の酒蔵が並ぶ日本三大酒どころ。7つの蔵をめぐって試飲ができる。",
    bestSeason: "10月", stayTime: "約2時間", access: "西条駅から徒歩約5分",
    nearby: [], mapQuery: "西条酒蔵通り",
    photo: { file: "酒蔵通り.JPG", author: "Inaji", license: "CC BY-SA 3.0" },
  },
  {
    id: "akiyoshido", name: "秋芳洞・秋吉台", region: "中国", prefecture: "山口県",
    categories: ["自然", "絶景"],
    description: "日本最大級のカルスト台地と、その地下に広がる大鍾乳洞。百枚皿と黄金柱は必見。",
    bestSeason: "通年", stayTime: "半日", access: "新山口駅からバスで約40分",
    nearby: [], mapQuery: "秋芳洞",
    photo: { file: "Mount Fuji of cave in Akiyoshi Cave 1.jpg", author: "そらみみ (Soramimi)", license: "CC BY-SA 4.0" },
  },
  {
    id: "hagi", name: "萩城下町", region: "中国", prefecture: "山口県",
    categories: ["歴史", "街歩き"],
    description: "吉田松陰と維新の志士たちを生んだ城下町。夏みかんの土塀と武家屋敷を自転車でめぐる。",
    bestSeason: "通年", stayTime: "半日", access: "東萩駅から自転車で約10分",
    nearby: [], mapQuery: "萩城下町",
    photo: { file: "View in Hagi Castle Town.jpg", author: "そらみみ", license: "CC BY-SA 4.0" },
  },
  // ---- 四国 ----
  {
    id: "iya-kazurabashi", name: "祖谷のかずら橋", region: "四国", prefecture: "徳島県",
    categories: ["自然", "絶景"],
    description: "深い渓谷に架かるシラクチカズラ製の吊り橋。足元の隙間からのぞく谷はスリル満点。",
    bestSeason: "4〜11月", stayTime: "約1時間", access: "大歩危駅から車で約20分",
    nearby: ["oboke-koboke"], mapQuery: "祖谷のかずら橋",
    photo: { file: "Tokushima Miyoshi Okuiya Double Kazurabashi 5.JPG", author: "京浜にけ at Japanese Wikipedia", license: "CC BY-SA 3.0" },
  },
  {
    id: "naruto-whirlpools", name: "鳴門の渦潮", region: "四国", prefecture: "徳島県",
    categories: ["自然", "絶景"],
    description: "世界最大級の渦が巻く鳴門海峡。観潮船で間近に迫るか、渦の道のガラス床から真上をのぞくか。",
    bestSeason: "春・秋の大潮", stayTime: "約2時間", access: "鳴門駅からバスで約20分",
    nearby: ["awaodori-kaikan"], mapQuery: "鳴門 渦の道",
    photo: { file: "Whirlpools from Uzunomichi Promenade 1.jpg", author: "そらみみ (Soramimi)", license: "CC BY-SA 4.0" },
  },
  {
    id: "kotohiragu", name: "金刀比羅宮", region: "四国", prefecture: "香川県",
    categories: ["歴史", "グルメ"],
    description: "「こんぴらさん」の愛称で親しまれる785段の石段の先の本宮。参道の讃岐うどんも欠かせない。",
    bestSeason: "通年", stayTime: "約3時間", access: "琴平駅から徒歩+石段785段",
    nearby: ["chichibugahama", "ritsurin"], mapQuery: "金刀比羅宮",
    photo: { file: "金刀比羅宮12 - panoramio.jpg", author: "baggio4ever", license: "CC BY 3.0" },
  },
  {
    id: "chichibugahama", name: "父母ヶ浜", region: "四国", prefecture: "香川県",
    categories: ["絶景"],
    description: "干潮の夕暮れに潮だまりが鏡になる「日本のウユニ塩湖」。写真映え抜群の夕日の名所。",
    bestSeason: "通年", stayTime: "約1時間30分", access: "詫間駅から車で約10分",
    nearby: ["kotohiragu"], mapQuery: "父母ヶ浜",
    photo: { file: "Titibugahama 01.jpg", author: "Dokudami", license: "CC BY-SA 4.0" },
  },
  {
    id: "dogo-onsen", name: "道後温泉", region: "四国", prefecture: "愛媛県",
    categories: ["温泉", "歴史", "街歩き"],
    description: "日本最古級の温泉。重要文化財の道後温泉本館での入浴と、浴衣での商店街散策が定番。",
    bestSeason: "通年", stayTime: "半日〜1泊", access: "道後温泉駅からすぐ",
    nearby: ["shimanami-kaido", "matsuyama-castle", "uchiko"], mapQuery: "道後温泉本館",
    photo: { file: "Dogo Onsen Honkan (Main building), 道後温泉 本館 - panoramio.jpg", author: "z tanuki", license: "CC BY 3.0" },
  },
  {
    id: "shimanami-kaido", name: "しまなみ海道", region: "四国", prefecture: "愛媛県",
    categories: ["絶景", "自然"],
    description: "瀬戸内の島々を橋でつなぐサイクリストの聖地。亀老山展望公園から見る多島美と橋のパノラマは圧巻。",
    bestSeason: "3〜11月", stayTime: "半日〜1日", access: "今治駅・尾道駅からレンタサイクル",
    nearby: ["onomichi", "dogo-onsen"], mapQuery: "亀老山展望公園",
    photo: { file: "Kirousan 20240521 1.jpg", author: "Araiyasushige", license: "CC0" },
  },
  {
    id: "shimanto-river", name: "四万十川", region: "四国", prefecture: "高知県",
    categories: ["自然", "絶景"],
    description: "「日本最後の清流」。欄干のない沈下橋と屋形舟の川下りでゆったりした時間を過ごせる。",
    bestSeason: "5〜10月", stayTime: "半日", access: "中村駅から車で約15分(佐田沈下橋)",
    nearby: [], mapQuery: "四万十川 佐田沈下橋",
    photo: { file: "Shimanto sada chinkabashi fukin.jpg", author: "四万十人", license: "CC BY-SA 3.0" },
  },
  {
    id: "katsurahama", name: "桂浜", region: "四国", prefecture: "高知県",
    categories: ["絶景", "歴史"],
    description: "坂本龍馬像が太平洋を見つめる弓状の浜。月の名所として名高く、ひろめ市場のカツオのたたきとセットで。",
    bestSeason: "通年", stayTime: "約1時間30分", access: "高知駅からバスで約40分",
    nearby: ["hirome-ichiba"], mapQuery: "桂浜",
    photo: { file: "Kochi Katsurahama Daytime 1.JPG", author: "京浜にけ", license: "CC BY-SA 3.0" },
  },

  {
    id: "oboke-koboke", name: "大歩危・小歩危", region: "四国", prefecture: "徳島県",
    categories: ["絶景", "自然"],
    description: "吉野川の激流が2億年かけて刻んだ渓谷。遊覧船やラフティングで、エメラルドの流れと奇岩を間近に。",
    bestSeason: "4〜11月", stayTime: "約2時間", access: "大歩危駅から徒歩約20分",
    nearby: ["iya-kazurabashi"], mapQuery: "大歩危峡",
    photo: { file: "Oboke gorge pleasure boat 2106 August 13.B.jpg", author: "さかおり", license: "CC BY-SA 4.0" },
  },
  {
    id: "awaodori-kaikan", name: "阿波おどり会館", region: "四国", prefecture: "徳島県",
    categories: ["街歩き", "歴史"],
    description: "400年続く阿波おどりを一年中体験できる。専属連の実演で一緒に踊れば、あなたも「踊る阿呆」に。",
    bestSeason: "通年", stayTime: "約1時間30分", access: "徳島駅から徒歩約10分",
    nearby: ["naruto-whirlpools"], mapQuery: "阿波おどり会館",
    photo: { file: "阿波おどり会館 (34947062726).jpg", author: "Wei-Te Wong from Taipei City, Taiwan, Republic of China", license: "CC BY-SA 2.0" },
  },
  {
    id: "ritsurin", name: "栗林公園", region: "四国", prefecture: "香川県",
    categories: ["歴史", "自然"],
    description: "「一歩一景」と称される大名庭園の最高峰。飛来峰から見下ろす偃月橋と築山の景は見事のひと言。",
    bestSeason: "通年", stayTime: "約2時間", access: "栗林公園北口駅から徒歩約3分",
    nearby: ["kotohiragu"], mapQuery: "栗林公園",
    photo: { file: "Ritsurin.JPG", author: "Leela Soden", license: "CC BY-SA 3.0" },
  },
  {
    id: "naoshima", name: "直島", region: "四国", prefecture: "香川県",
    categories: ["街歩き", "絶景"],
    description: "草間彌生のかぼちゃと安藤忠雄建築が点在する現代アートの島。港から自転車でアートめぐり。",
    bestSeason: "3〜11月", stayTime: "1日", access: "高松港からフェリーで約50分",
    nearby: [], mapQuery: "直島 宮浦港",
    photo: { file: "Naoshima Pavilion 2.jpg", author: "Bea Phi", license: "CC BY-SA 4.0" },
  },
  {
    id: "matsuyama-castle", name: "松山城", region: "四国", prefecture: "愛媛県",
    categories: ["歴史", "絶景"],
    description: "現存12天守のひとつ。リフトで上がる本丸広場から、松山市街と瀬戸内海を一望できる。",
    bestSeason: "通年", stayTime: "約2時間", access: "大街道電停から徒歩とリフトで約15分",
    nearby: ["dogo-onsen"], mapQuery: "松山城",
    photo: { file: "Matsuyama Castle , 松山城 - panoramio (8).jpg", author: "z tanuki", license: "CC BY 3.0" },
  },
  {
    id: "uchiko", name: "内子の町並み", region: "四国", prefecture: "愛媛県",
    categories: ["歴史", "街歩き"],
    description: "木蝋で栄えた商家の白壁が続く八日市護国地区。現役の芝居小屋・内子座も見学できる。",
    bestSeason: "通年", stayTime: "約2時間", access: "内子駅から徒歩約10分",
    nearby: ["dogo-onsen"], mapQuery: "内子 八日市護国",
    photo: { file: "Uchiko1,Uchiko-town,Japan.JPG", author: "katorisi", license: "CC BY-SA 3.0" },
  },
  {
    id: "hirome-ichiba", name: "高知・ひろめ市場", region: "四国", prefecture: "高知県",
    categories: ["グルメ", "街歩き"],
    description: "藁焼きカツオのたたきを昼から一杯やりながら。60余りの店がひしめく高知の社交場。",
    bestSeason: "通年", stayTime: "約2時間", access: "高知城前電停から徒歩約2分",
    nearby: ["katsurahama"], mapQuery: "ひろめ市場",
    photo: { file: "Hirome ichiba(Market) ひろめ市場 - Panoramio 130692260.jpg", author: "z tanuki", license: "CC BY 3.0" },
  },
  {
    id: "nikobuchi", name: "にこ淵", region: "四国", prefecture: "高知県",
    categories: ["絶景", "自然"],
    description: "「仁淀ブルー」の代名詞となった神秘の滝壺。晴れた日の正午前後、水面がもっとも青く輝く。",
    bestSeason: "通年", stayTime: "約1時間", access: "伊野駅から車で約40分",
    nearby: [], mapQuery: "にこ淵",
    photo: { file: "Nikobuti03.jpg", author: "Dokudami", license: "CC BY-SA 4.0" },
  },
  // ---- 九州・沖縄 ----
  {
    id: "nakasu-yatai", name: "福岡・中洲屋台街", region: "九州・沖縄", prefecture: "福岡県",
    categories: ["グルメ", "街歩き"],
    description: "川沿いに屋台が連なる博多の夜の名物。豚骨ラーメン・焼きラーメン・餃子をはしごしたい。",
    bestSeason: "通年", stayTime: "約2時間", access: "中洲川端駅から徒歩約5分",
    nearby: ["dazaifu-tenmangu", "itoshima"], mapQuery: "中洲屋台街",
    photo: { file: "Hakata yatai and yatai food - 2024 Sept 24 various 11 27 44 788000.jpeg", author: "Nesnad", license: "CC BY 4.0" },
  },
  {
    id: "dazaifu-tenmangu", name: "太宰府天満宮", region: "九州・沖縄", prefecture: "福岡県",
    categories: ["歴史", "グルメ"],
    description: "学問の神様・菅原道真公を祀る全国天満宮の総本宮。参道の焼きたて梅ヶ枝餅は外せない。",
    bestSeason: "通年", stayTime: "約2時間", access: "太宰府駅から徒歩約5分",
    nearby: ["nakasu-yatai", "yanagawa"], mapQuery: "太宰府天満宮",
    photo: { file: "20100719 Dazaifu Tenmangu Shrine 3328.jpg", author: "Jakub Hałun", license: "CC BY-SA 4.0" },
  },
  {
    id: "mifuneyama-rakuen", name: "御船山楽園", region: "九州・沖縄", prefecture: "佐賀県",
    categories: ["絶景", "自然"],
    description: "断崖を借景にした武雄の大庭園。春は20万本のツツジ、夏はチームラボの光のアートで幻想的に染まる。",
    bestSeason: "4〜5月・7〜10月", stayTime: "約2時間", access: "武雄温泉駅から車で約5分",
    nearby: ["yutoku-inari"], mapQuery: "御船山楽園",
    photo: { file: "Azalea Valley in Mifuneyama Garden and Mount Mifuneyama 3.jpg", author: "そらみみ", license: "CC BY-SA 4.0" },
  },
  {
    id: "yutoku-inari", name: "祐徳稲荷神社", region: "九州・沖縄", prefecture: "佐賀県",
    categories: ["歴史", "絶景"],
    description: "「鎮西日光」と称される日本三大稲荷のひとつ。崖に張り出した朱塗りの本殿は懸造りの傑作。",
    bestSeason: "通年", stayTime: "約1時間30分", access: "肥前鹿島駅からバスで約10分",
    nearby: ["mifuneyama-rakuen"], mapQuery: "祐徳稲荷神社",
    photo: { file: "祐徳稲荷神社 楼門.JPG", author: "JNN360", license: "CC BY-SA 4.0" },
  },
  {
    id: "inasayama", name: "稲佐山の夜景", region: "九州・沖縄", prefecture: "長崎県",
    categories: ["絶景", "街歩き"],
    description: "すり鉢状の街に灯りがきらめく「世界新三大夜景」。ロープウェイで5分、山頂展望台から1000万ドルの夜景を。",
    bestSeason: "通年", stayTime: "約2時間", access: "長崎駅から車+ロープウェイで約20分",
    nearby: ["gunkanjima"], mapQuery: "稲佐山展望台",
    photo: { file: "Nagasaki night view (49658801407).jpg", author: "Raita Futo from Tokyo, Japan", license: "CC BY 2.0" },
  },
  {
    id: "gunkanjima", name: "軍艦島(端島)", region: "九州・沖縄", prefecture: "長崎県",
    categories: ["歴史", "絶景"],
    description: "海上に浮かぶ廃墟の炭鉱島。往時は世界一の人口密度を誇った世界遺産に、上陸ツアーで渡れる。",
    bestSeason: "4〜10月", stayTime: "半日(ツアー)", access: "長崎港からツアー船で約40分",
    nearby: ["inasayama"], mapQuery: "軍艦島",
    photo: { file: "Hashima, Nagasaki, Japan, 20240814 1424 3410.jpg", author: "Jakub Hałun", license: "CC BY 4.0" },
  },
  {
    id: "aso-daikanbo", name: "阿蘇・大観峰", region: "九州・沖縄", prefecture: "熊本県",
    categories: ["自然", "絶景"],
    description: "世界有数のカルデラと草原が広がる雄大な風景。大観峰からの眺めと阿蘇のあか牛丼が名物。",
    bestSeason: "4〜11月", stayTime: "約1時間", access: "阿蘇駅から車で約30分",
    nearby: ["kurokawa-onsen", "takachiho-gorge"], mapQuery: "阿蘇 大観峰",
    photo: { file: "Mt.Aso and caldera01.jpg", author: "Miya.m", license: "CC BY-SA 3.0" },
  },
  {
    id: "kurokawa-onsen", name: "黒川温泉", region: "九州・沖縄", prefecture: "熊本県",
    categories: ["温泉", "自然"],
    description: "山あいに和風旅館が寄り添う「入湯手形」の温泉郷。3枚綴りの手形で好きな宿の露天風呂をはしごできる。",
    bestSeason: "通年", stayTime: "半日〜1泊", access: "阿蘇駅からバスで約50分",
    nearby: ["aso-daikanbo", "yufuin-onsen", "kokonoe-yume-bridge"], mapQuery: "黒川温泉",
    photo: { file: "黒川温泉1.JPG", author: "No machine-readable author provided. おぉたむすねィく探検隊 assumed (ba", license: "CC BY 2.5" },
  },
  {
    id: "yufuin-onsen", name: "由布院温泉", region: "九州・沖縄", prefecture: "大分県",
    categories: ["温泉", "街歩き", "グルメ"],
    description: "由布岳を望む人気温泉地。湯の坪街道の食べ歩きと朝霧に包まれる金鱗湖が見どころ。",
    bestSeason: "通年", stayTime: "半日〜1泊", access: "由布院駅から徒歩約15分(金鱗湖)",
    nearby: ["beppu-jigoku", "kurokawa-onsen", "kokonoe-yume-bridge"], mapQuery: "由布院温泉 金鱗湖",
    photo: { file: "Lake Kinrin with Morning fog.jpg", author: "Tzu-hsun, Hsu", license: "CC BY-SA 4.0" },
  },
  {
    id: "beppu-jigoku", name: "別府・地獄めぐり", region: "九州・沖縄", prefecture: "大分県",
    categories: ["温泉", "絶景"],
    description: "コバルトブルーの海地獄や真っ赤な血の池地獄など、7つの源泉を巡る別府名物。湧出量は日本一。",
    bestSeason: "通年", stayTime: "約3時間", access: "別府駅からバスで約15分",
    nearby: ["yufuin-onsen", "usa-jingu"], mapQuery: "海地獄",
    photo: { file: "Beppu Umi-jigoku04n4272.jpg", author: "663highland", license: "CC BY 2.5" },
  },
  {
    id: "takachiho-gorge", name: "高千穂峡", region: "九州・沖縄", prefecture: "宮崎県",
    categories: ["絶景", "自然"],
    description: "柱状節理の断崖に真名井の滝が流れ落ちる神秘的な峡谷。ボートで滝の間近まで行ける。",
    bestSeason: "通年", stayTime: "約2時間", access: "延岡駅から車で約1時間",
    nearby: ["aso-daikanbo"], mapQuery: "高千穂峡",
    photo: { file: "秋色の高千穂峡 (Autumn Colored Takachiho Gorge) 24 Nov, 2012 - panoramio.jpg", author: "Hiroaki Kaneko", license: "CC BY-SA 3.0" },
  },
  {
    id: "aoshima", name: "青島", region: "九州・沖縄", prefecture: "宮崎県",
    categories: ["絶景", "自然"],
    description: "「鬼の洗濯板」と呼ばれる波状岩に囲まれた亜熱帯の小島。ヤシ並木と青島神社が南国ムード満点。",
    bestSeason: "通年", stayTime: "約1時間30分", access: "青島駅から徒歩約10分",
    nearby: ["udo-jingu"], mapQuery: "青島神社",
    photo: { file: "Aoshima Oni no Sentaku ita 200408.jpg", author: "Suikotei", license: "CC BY-SA 4.0" },
  },
  {
    id: "yakushima", name: "屋久島", region: "九州・沖縄", prefecture: "鹿児島県",
    categories: ["自然", "絶景"],
    description: "樹齢数千年の縄文杉と苔むす森の世界自然遺産。白谷雲水峡のトレッキングが人気。",
    bestSeason: "3〜11月", stayTime: "1日〜", access: "鹿児島港から高速船で約2〜3時間",
    nearby: [], mapQuery: "屋久島 白谷雲水峡",
    photo: { file: "Shiratani Unsui Gorge 18.jpg", author: "Σ64", license: "CC BY 4.0" },
  },
  {
    id: "sakurajima", name: "桜島", region: "九州・沖縄", prefecture: "鹿児島県",
    categories: ["自然", "絶景"],
    description: "今も噴煙を上げる鹿児島のシンボル。フェリーでわずか15分、溶岩なぎさ公園の足湯から迫力の山容を。",
    bestSeason: "通年", stayTime: "約3時間", access: "鹿児島港からフェリーで約15分",
    nearby: ["kirishima-jingu"], mapQuery: "桜島",
    photo: { file: "Sakurajima55.jpg", author: "TANAKA Juuyoh (talk)", license: "CC BY 3.0" },
  },
  {
    id: "churaumi", name: "沖縄美ら海水族館", region: "九州・沖縄", prefecture: "沖縄県",
    categories: ["自然"],
    description: "巨大水槽「黒潮の海」を悠々と泳ぐジンベエザメは圧巻。周辺の海洋博公園やエメラルドビーチも。",
    bestSeason: "通年", stayTime: "約3時間", access: "那覇空港から車で約2時間",
    nearby: ["kouri-island", "manzamo"], mapQuery: "沖縄美ら海水族館",
    photo: { file: "Okinawa Aquarium.jpg", author: "Jordy Meow", license: "CC BY-SA 3.0" },
  },
  {
    id: "kouri-island", name: "古宇利島", region: "九州・沖縄", prefecture: "沖縄県",
    categories: ["絶景", "自然"],
    description: "「恋の島」と呼ばれる離島へ、澄んだ海の上を古宇利大橋で一直線。ハートロックと絶景カフェが人気。",
    bestSeason: "4〜10月", stayTime: "約2時間", access: "那覇空港から車で約1時間30分",
    nearby: ["churaumi", "manzamo"], mapQuery: "古宇利大橋",
    photo: { file: "古宇利大橋 古宇利ビーチ 20100814a.jpg", author: "hasano_jp", license: "CC BY 3.0" },
  },
  {
    id: "taketomi-island", name: "竹富島", region: "九州・沖縄", prefecture: "沖縄県",
    categories: ["絶景", "街歩き", "自然"],
    description: "赤瓦の集落と白砂の道が残る八重山の離島。水牛車での集落巡りとコンドイビーチの遠浅の海。",
    bestSeason: "通年", stayTime: "半日", access: "石垣港からフェリーで約15分",
    nearby: ["kabira-bay"], mapQuery: "竹富島 コンドイビーチ",
    photo: { file: "Kondoi Beach 01.jpg", author: "ajari from Japan", license: "CC BY 2.0" },
  },
  {
    id: "yanagawa", name: "柳川川下り", region: "九州・沖縄", prefecture: "福岡県",
    categories: ["街歩き", "自然", "グルメ"],
    description: "どんこ舟で城下町の掘割をゆらりと下る。名物うなぎのせいろ蒸しで締めるのが柳川流。",
    bestSeason: "通年", stayTime: "半日", access: "西鉄柳川駅から徒歩約8分",
    nearby: ["dazaifu-tenmangu"], mapQuery: "柳川 川下り",
    photo: { file: "橋が低いので伏せる 柳川川下り (19016709711).jpg", author: "Thomas Au", license: "CC BY 2.0" },
  },
  {
    id: "itoshima", name: "糸島・桜井二見ヶ浦", region: "九州・沖縄", prefecture: "福岡県",
    categories: ["絶景", "グルメ"],
    description: "白い鳥居と夫婦岩に沈む夕日が名物。海沿いのカフェと冬の牡蠣小屋、福岡市内から日帰りドライブの定番。",
    bestSeason: "4〜10月", stayTime: "半日", access: "筑前前原駅から車で約20分",
    nearby: ["nakasu-yatai"], mapQuery: "桜井二見ヶ浦",
    photo: { file: "Futamigaura Beach from observation deck of Futamigaura Cemetery 1.JPG", author: "そらみみ (Soramimi)", license: "CC BY-SA 4.0" },
  },
  {
    id: "yobuko", name: "呼子朝市", region: "九州・沖縄", prefecture: "佐賀県",
    categories: ["グルメ", "街歩き"],
    description: "日本三大朝市のひとつ。名物イカの活造りは透きとおる身と、あとから天ぷらになるゲソまで楽しめる。",
    bestSeason: "通年", stayTime: "約2時間", access: "唐津駅からバスで約30分",
    nearby: [], mapQuery: "呼子朝市",
    photo: { file: "Yobuko Asa-ichi (Yobuko, Karatsu, Saga, Japan).jpg", author: "flickr ID; gtknj (URL)", license: "CC BY 2.0" },
  },
  {
    id: "unzen-jigoku", name: "雲仙地獄", region: "九州・沖縄", prefecture: "長崎県",
    categories: ["温泉", "絶景"],
    description: "硫黄の噴気が立ちのぼる地獄めぐりと、日本初の国立公園に指定された雲仙温泉。名物は温泉たまご。",
    bestSeason: "通年", stayTime: "半日", access: "諫早駅からバスで約1時間20分",
    nearby: [], mapQuery: "雲仙地獄",
    photo: { file: "140322 Unzen Onsen Jigoku Unzen Nagasaki pref Japan13o.JPG", author: "663highland", license: "CC BY 2.5" },
  },
  {
    id: "kujukushima", name: "九十九島", region: "九州・沖縄", prefecture: "長崎県",
    categories: ["絶景", "自然"],
    description: "佐世保沖に208の島々が浮かぶリアス海岸。遊覧船クルーズと展海峰から眺める夕景が有名。",
    bestSeason: "通年", stayTime: "半日", access: "佐世保駅からバスで約25分",
    nearby: [], mapQuery: "九十九島パールシーリゾート",
    photo: { file: "200320 Kujukushima Islands Sasebo Nagasaki pref Japan01s3.jpg", author: "663highland", license: "CC BY-SA 4.0" },
  },
  {
    id: "kumamoto-castle", name: "熊本城", region: "九州・沖縄", prefecture: "熊本県",
    categories: ["歴史"],
    description: "「武者返し」の石垣で名高い天下の名城。地震からの復旧が進み、特別見学通路から往時の姿が戻る様子を見られる。",
    bestSeason: "通年", stayTime: "約2時間", access: "熊本駅から市電で約15分",
    nearby: [], mapQuery: "熊本城",
    photo: { file: "Kumamoto Castle 02n3200.jpg", author: "663highland", license: "CC BY 2.5" },
  },
  {
    id: "amakusa-sakitsu", name: "天草・﨑津集落", region: "九州・沖縄", prefecture: "熊本県",
    categories: ["歴史", "街歩き"],
    description: "漁村の家並みに教会の尖塔が立つ、世界遺産の潜伏キリシタン集落。海に開けた祈りの里をゆっくり歩く。",
    bestSeason: "通年", stayTime: "約2時間", access: "本渡バスセンターから車で約30分",
    nearby: [], mapQuery: "崎津教会",
    photo: { file: "Sakitsu Church stone & wood mix building.jpg", author: "Indiana jo", license: "CC BY-SA 4.0" },
  },
  {
    id: "kokonoe-yume-bridge", name: "九重\"夢\"大吊橋", region: "九州・沖縄", prefecture: "大分県",
    categories: ["絶景", "自然"],
    description: "高さ173m、歩行者専用では日本一の高さの吊橋。眼下に震動の滝と九酔渓の大樹海が広がる。",
    bestSeason: "10〜11月", stayTime: "約1時間", access: "豊後中村駅からバスで約20分",
    nearby: ["yufuin-onsen", "kurokawa-onsen"], mapQuery: "九重夢大吊橋",
    photo: { file: "九重夢大吊橋 - panoramio (4).jpg", author: "kajikawa", license: "CC BY 3.0" },
  },
  {
    id: "usa-jingu", name: "宇佐神宮", region: "九州・沖縄", prefecture: "大分県",
    categories: ["歴史"],
    description: "全国に4万社ある八幡さまの総本宮。国宝の朱塗りの本殿と、神代の森の澄んだ空気に包まれる。",
    bestSeason: "通年", stayTime: "約2時間", access: "宇佐駅からバスで約10分",
    nearby: ["beppu-jigoku"], mapQuery: "宇佐神宮",
    photo: { file: "Usa Shrine Nanchu Romon.JPG", author: "ja:User:Sanjo", license: "CC BY-SA 3.0" },
  },
  {
    id: "udo-jingu", name: "鵜戸神宮", region: "九州・沖縄", prefecture: "宮崎県",
    categories: ["歴史", "絶景"],
    description: "太平洋に面した断崖の洞窟に本殿が鎮座する。運玉を亀石のくぼみに投げ入れて縁結び祈願。",
    bestSeason: "通年", stayTime: "約1時間30分", access: "宮崎駅からバスで約1時間30分",
    nearby: ["aoshima"], mapQuery: "鵜戸神宮",
    photo: { file: "鵜戸神宮 - panoramio.jpg", author: "iwaseta", license: "CC BY-SA 3.0" },
  },
  {
    id: "ebino-kogen", name: "えびの高原", region: "九州・沖縄", prefecture: "宮崎県",
    categories: ["自然", "絶景"],
    description: "霧島連山に抱かれた標高1200mの高原。韓国岳登山と池めぐりコース、秋はススキの原が黄金色に。",
    bestSeason: "5〜11月", stayTime: "半日", access: "小林駅から車で約30分",
    nearby: ["kirishima-jingu"], mapQuery: "えびの高原",
    photo: { file: "Mount Karakuni from Ebino Plateau.jpg", author: "STA3816", license: "CC BY-SA 3.0" },
  },
  {
    id: "kirishima-jingu", name: "霧島神宮", region: "九州・沖縄", prefecture: "鹿児島県",
    categories: ["歴史", "自然"],
    description: "天孫降臨の地に建つ朱塗りの社。樹齢800年の御神木と苔むす参道が神話の世界へ誘う。",
    bestSeason: "通年", stayTime: "約1時間30分", access: "霧島神宮駅からバスで約10分",
    nearby: ["ebino-kogen", "sakurajima"], mapQuery: "霧島神宮",
    photo: { file: "霧島神宮（鹿児島）.jpg", author: "矢野弘幸", license: "CC BY-SA 4.0" },
  },
  {
    id: "ibusuki-onsen", name: "指宿温泉", region: "九州・沖縄", prefecture: "鹿児島県",
    categories: ["温泉"],
    description: "波打ち際で楽しむ世界でも珍しい天然の砂むし温泉。浴衣で砂に埋まれば10分で汗が噴き出す。",
    bestSeason: "通年", stayTime: "半日", access: "指宿駅から徒歩約20分",
    nearby: [], mapQuery: "指宿 砂むし会館砂楽",
    photo: { file: "Sand steaming hall Saraku.jpg", author: "ブルーノ・プラス", license: "CC BY 4.0" },
  },
  {
    id: "amami-oshima", name: "奄美大島", region: "九州・沖縄", prefecture: "鹿児島県",
    categories: ["自然", "絶景"],
    description: "金作原の亜熱帯原生林と透明度抜群の土盛海岸。アマミノクロウサギが息づく世界自然遺産の島。",
    bestSeason: "4〜10月", stayTime: "1日〜", access: "奄美空港から車で各所へ",
    nearby: [], mapQuery: "奄美大島 土盛海岸",
    photo: { file: "Amami-Tomori beach 20040712.JPG", author: "投稿者自身による撮影", license: "Public domain" },
  },
  {
    id: "shurijo", name: "首里城", region: "九州・沖縄", prefecture: "沖縄県",
    categories: ["歴史"],
    description: "琉球王国の栄華を伝える王城。2019年の火災から正殿の復元が進み、「見せる復興」の現場を見学できる。",
    bestSeason: "通年", stayTime: "約2時間", access: "ゆいレール首里駅から徒歩約15分",
    nearby: ["kokusai-dori"], mapQuery: "首里城公園",
    photo: { file: "Shureimon 20150211.jpg", author: "Suicasmo", license: "CC BY-SA 4.0" },
  },
  {
    id: "kokusai-dori", name: "国際通り", region: "九州・沖縄", prefecture: "沖縄県",
    categories: ["街歩き", "グルメ"],
    description: "那覇のメインストリート約1.6km。ステーキにブルーシール、脇道の市場本通りの先には牧志公設市場。",
    bestSeason: "通年", stayTime: "約3時間", access: "ゆいレール県庁前駅から徒歩約3分",
    nearby: ["shurijo"], mapQuery: "那覇 国際通り",
    photo: { file: "Kokusai-dori08s3s4440.jpg", author: "663highland", license: "CC BY 2.5" },
  },
  {
    id: "manzamo", name: "万座毛", region: "九州・沖縄", prefecture: "沖縄県",
    categories: ["絶景"],
    description: "「万人が座れる草原」と讃えられた、象の鼻の形の断崖。東シナ海に沈む夕日の名所。",
    bestSeason: "通年", stayTime: "約1時間", access: "那覇空港から車で約1時間",
    nearby: ["churaumi", "kouri-island"], mapQuery: "万座毛",
    photo: { file: "Onna Okinawa Japan Cape-Manzamo-01.jpg", author: "CEphoto, Uwe Aranas", license: "CC BY-SA 3.0" },
  },
  {
    id: "kabira-bay", name: "石垣島・川平湾", region: "九州・沖縄", prefecture: "沖縄県",
    categories: ["絶景", "自然"],
    description: "白砂にエメラルドのグラデーションが広がるミシュラン三つ星の湾。グラスボートでサンゴ礁をのぞく。",
    bestSeason: "通年", stayTime: "約2時間", access: "石垣港から車で約30分",
    nearby: ["taketomi-island"], mapQuery: "川平湾",
    photo: { file: "Kabira Bay Ishigaki Island40bs3s4592.jpg", author: "663highland", license: "CC BY 2.5" },
  },
];
// スポットを追加するときは、上のオブジェクトをひとつコピーして書き換えるだけでOK。
// photo が空のままでも動く(地域色のプレースホルダーが表示される)。
